-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/amc_model_w16a16/amc_cnn_16w16a_src_SinglePortRAM_generic_block417.vhd
-- Created: 2023-08-04 11:27:24
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: amc_cnn_16w16a_src_SinglePortRAM_generic_block417
-- Source Path: amc_model_w16a16/DUT HDL/Dense Layer 1/Dense Layer 1/Weight Storage63/SinglePortRAM_generic
-- Hierarchy Level: 4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY amc_cnn_16w16a_src_SinglePortRAM_generic_block417 IS
  GENERIC( AddrWidth                      : integer := 1;
           DataWidth                      : integer := 1
           );
  PORT( clk                               :   IN    std_logic;
        enb                               :   IN    std_logic;
        din                               :   IN    std_logic_vector(DataWidth - 1 DOWNTO 0);  -- generic width
        addr                              :   IN    std_logic_vector(AddrWidth - 1 DOWNTO 0);  -- generic width
        we                                :   IN    std_logic;  -- ufix1
        dout                              :   OUT   std_logic_vector(DataWidth - 1 DOWNTO 0)  -- generic width
        );
END amc_cnn_16w16a_src_SinglePortRAM_generic_block417;


ARCHITECTURE rtl OF amc_cnn_16w16a_src_SinglePortRAM_generic_block417 IS

  -- Local Type Definitions
  TYPE ram_type IS ARRAY (2**AddrWidth - 1 DOWNTO 0) of std_logic_vector(DataWidth - 1 DOWNTO 0);

  -- Signals
  SIGNAL ram                              : ram_type := (X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"f922", X"0a93", X"e060", X"0a7d", X"f18c", X"fb1d",
                                                        X"06fb", X"09e5", X"e74f", X"fa12", X"0625", X"fcd2", X"fcde", X"0d0a", X"fb47", X"f56d", X"1433", X"f181", X"15e6", X"ee48",
                                                        X"f277", X"e7d3", X"02a5", X"17d5", X"05e8", X"fcd1", X"fbff", X"05fc", X"0e64", X"0bad", X"059f", X"fe59", X"1dc4", X"e7af",
                                                        X"23be", X"06fa", X"f937", X"0da7", X"16fe", X"197b", X"155d", X"f1d6", X"fc98", X"0d67", X"1723", X"20b8", X"01d6", X"f69a",
                                                        X"07a8", X"f795", X"d9be", X"1cf6", X"062c", X"0554", X"fa13", X"fb6c", X"f199", X"f7ad", X"01ad", X"f966", X"0fc1", X"f8a6",
                                                        X"fd5f", X"f5cf", X"180c", X"fe30", X"2b73", X"1150", X"0035", X"23bb", X"1603", X"110a", X"1f8f", X"0dfd", X"04a9", X"061d",
                                                        X"ecff", X"f5a0", X"098c", X"10b1", X"1703", X"fd69", X"f28d", X"0ff0", X"0ba5", X"1b17", X"e9d8", X"1707", X"fccf", X"ed3e",
                                                        X"f6ab", X"06c1", X"fc57", X"f76b", X"f401", X"0df6", X"f850", X"f3cf", X"f0fe", X"f0ba", X"ec28", X"21d4", X"f597", X"05ec",
                                                        X"1d12", X"1e62", X"015c", X"f618", X"0517", X"fb72", X"f96e", X"099c", X"f4b8", X"f8ff", X"186e", X"ef9e", X"e2cb", X"2731",
                                                        X"0e6f", X"1832", X"d5db", X"f815", X"f582", X"ff87", X"0e44", X"0b6f", X"f167", X"1207", X"1202", X"f5de", X"fae9", X"f760",
                                                        X"1280", X"e9af", X"06e7", X"1e92", X"0f9a", X"0102", X"ff99", X"0234", X"f9f5", X"0ae0", X"06df", X"16e4", X"0128", X"1784",
                                                        X"ea0d", X"f037", X"f236", X"0847", X"fd97", X"f8d6", X"f7f5", X"eab9", X"05e3", X"07a3", X"fa98", X"fd73", X"0654", X"1043",
                                                        X"04a5", X"f9e1", X"ebd6", X"0f27", X"fcf2", X"1c81", X"070a", X"f99e", X"e86d", X"e4ef", X"fb1b", X"0833", X"07d2", X"0f1d",
                                                        X"e4c8", X"0453", X"166e", X"fb5d", X"0cfe", X"0ac6", X"fa21", X"1fe3", X"f9f9", X"0419", X"eddd", X"f8e7", X"0c23", X"010d",
                                                        X"fc86", X"05e3", X"f93b", X"063c", X"1655", X"1490", X"1c34", X"069e", X"0ac0", X"fe25", X"fafa", X"0578", X"eec4", X"0f25",
                                                        X"dd31", X"fa18", X"f794", X"f532", X"1a4a", X"f6e5", X"e5ee", X"1061", X"08ff", X"f7f3", X"fe73", X"2142", X"f55d", X"0ae0",
                                                        X"0844", X"fa72", X"012d", X"0473", X"0604", X"2012", X"0737", X"2820", X"0e86", X"edbe", X"f8af", X"fe51", X"ec73", X"23dd",
                                                        X"ef94", X"fe08", X"f21f", X"2e8c", X"e5ce", X"f6e9", X"f48f", X"04af", X"d190", X"219c", X"1258", X"e9e8", X"1f54", X"0aa9",
                                                        X"04ea", X"f59c", X"0b01", X"11b0", X"246e", X"23e2", X"f63c", X"f038", X"0ab1", X"017c", X"f7fb", X"2296", X"0758", X"1ddc",
                                                        X"0d08", X"1054", X"e472", X"11ee", X"ec98", X"fd03", X"e2a5", X"0f87", X"fb14", X"0691", X"e4e0", X"eee8", X"fcae", X"0c59",
                                                        X"14f2", X"e75f", X"e311", X"0c3f", X"012e", X"f1aa", X"072a", X"ff55", X"f4ed", X"e457", X"0e4e", X"fae4", X"fdc5", X"0a27",
                                                        X"15ba", X"0b0a", X"08d0", X"0790", X"f05d", X"0efe", X"0f19", X"fb6b", X"0179", X"ff1e", X"17c1", X"dedf", X"f2e4", X"fd4c",
                                                        X"0de5", X"024b", X"f26c", X"0a7e", X"0272", X"e4c5", X"efc4", X"194f", X"06e9", X"f546", X"2a7a", X"f7a0", X"0125", X"f486",
                                                        X"09d1", X"ffd5", X"1467", X"0edc", X"f81b", X"ffe9", X"058c", X"0310", X"fe8f", X"fa09", X"f884", X"fa7f", X"07e1", X"1338",
                                                        X"ef03", X"fb66", X"007c", X"0510", X"f248", X"fc56", X"04c0", X"01c0", X"f92d", X"ffbc", X"f566", X"f8a1", X"f4f8", X"1bbf",
                                                        X"13d8", X"e221", X"ee38", X"fb01", X"0d16", X"0349", X"f282", X"f9c6", X"f80f", X"f329", X"f605", X"dbb1", X"d201", X"f84b",
                                                        X"ec79", X"047a", X"1b84", X"ec51", X"1247", X"e82d", X"f607", X"0e7c", X"065d", X"1222", X"1285", X"f974", X"f4cd", X"1003",
                                                        X"fac2", X"f29a", X"fcdd", X"0b78", X"0c63", X"13a4", X"f2a4", X"fd86", X"0f3c", X"f30f", X"f6da", X"0c76", X"01bd", X"fe66",
                                                        X"16eb", X"edf8", X"d599", X"fbd4", X"ee19", X"1443", X"0664", X"1843", X"f75a", X"fe5f", X"ecf9", X"e6e0", X"fb93", X"f11c",
                                                        X"f9a2", X"fe75", X"eda6", X"f44f", X"0535", X"e5d1", X"06ec", X"0006", X"17fb", X"f6cf", X"1787", X"e4bf", X"ee36", X"fd3a",
                                                        X"04b7", X"1642", X"0bf4", X"f25e", X"163b", X"19c2", X"f0d7", X"0ca4", X"0128", X"fc6a", X"1fed", X"e2b7", X"fd40", X"0183",
                                                        X"e79c", X"fde5", X"fe86", X"f80d", X"e5ca", X"07b1", X"1063", X"fff2", X"f796", X"18dc", X"1136", X"1b2c", X"fc43", X"0f6c",
                                                        X"108c", X"ee9d", X"1694", X"f2cd", X"0b95", X"16a7", X"065a", X"0a2b", X"078f", X"f53f", X"145e", X"0a99", X"fbb8", X"fd45",
                                                        X"f475", X"0f78", X"edd1", X"0eff", X"fcf6", X"2419", X"0581", X"0ca7", X"10c0", X"018e", X"0ccf", X"08c2", X"f120", X"e7f6",
                                                        X"18a2", X"0ecb", X"0e24", X"0998", X"feef", X"f87b", X"031e", X"f1a3", X"fe5b", X"feeb", X"0060", X"16ec", X"fe18", X"f0ce",
                                                        X"ffbc", X"079a", X"07d9", X"fd10", X"ebbc", X"1c89", X"f180", X"0055", X"1d48", X"04c4", X"f996", X"fb7d", X"e5df", X"0ac5",
                                                        X"f010", X"205b", X"dc11", X"e94a", X"fc3b", X"f6ae", X"d643", X"e570", X"0ef8", X"149c", X"efd8", X"0276", X"0ab4", X"0c33",
                                                        X"ffbe", X"1b26", X"f8c1", X"f5c5", X"ef2b", X"0fea", X"0750", X"ff93", X"10aa", X"2312", X"1bbc", X"1acb", X"f5b2", X"0d0b",
                                                        X"0a33", X"0859", X"01a6", X"09ea", X"0af3", X"16a7", X"e6d0", X"ef24", X"065e", X"049f", X"e580", X"ece5", X"0cc5", X"f310",
                                                        X"06d8", X"fb63", X"0149", X"fd5c", X"fbef", X"e925", X"ef62", X"13d4", X"f6d2", X"fc37", X"f628", X"08f0", X"f657", X"d667",
                                                        X"0e0b", X"dd50", X"f6ad", X"0ba7", X"0cf2", X"fbf3", X"efe6", X"f1e0", X"09c2", X"0516", X"efee", X"0c79", X"f775", X"064b",
                                                        X"e69b", X"e124", X"0f88", X"1147", X"f891", X"fa50", X"f43d", X"1106", X"046e", X"0dd7", X"1382", X"f39f", X"f33b", X"f6af",
                                                        X"0786", X"fad1", X"02db", X"fb6c", X"e413", X"f72a", X"f76e", X"ee72", X"0023", X"f7de", X"fbfa", X"0037", X"067e", X"f11e",
                                                        X"df3c", X"f148", X"0caa", X"f821", X"0daa", X"f60f", X"16bb", X"fde9", X"eca6", X"ebe5", X"0042", X"db0a", X"02ac", X"0368",
                                                        X"00d1", X"e31e", X"0087", X"0e02", X"1081", X"ecb0", X"e668", X"20bc", X"fee2", X"01b0", X"08a7", X"0a94", X"00f4", X"f939",
                                                        X"f468", X"0d35", X"0190", X"f5f9", X"0eb8", X"0301", X"0264", X"f1fb", X"2030", X"fde7", X"e37a", X"0e9b", X"fc21", X"f51e",
                                                        X"ed8a", X"0191", X"fe5f", X"1551", X"f6e9", X"f20b", X"d6e3", X"e9b2", X"edf8", X"f2fa", X"f112", X"e37f", X"1d29", X"1005",
                                                        X"1273", X"020b", X"00f5", X"fe83", X"edaa", X"119c", X"11e0", X"eb28", X"0d8b", X"fcdd", X"13f1", X"01bd", X"f376", X"e2d7",
                                                        X"fa88", X"0118", X"ed6d", X"ee1d", X"fcb6", X"f98d", X"e145", X"0176", X"008b", X"0ed4", X"e967", X"fbc7", X"121e", X"ec34",
                                                        X"149d", X"e360", X"feb2", X"f90a", X"eab9", X"0095", X"eb4a", X"fb34", X"e455", X"ea46", X"053c", X"0580", X"e3cc", X"01e0",
                                                        X"fa92", X"e546", X"fe03", X"e89f", X"e0a2", X"f235", X"e957", X"e41e", X"04cc", X"f179", X"fc71", X"ef08", X"eaac", X"f282",
                                                        X"f812", X"1829", X"0b6e", X"016e", X"df4b", X"fef1", X"01c9", X"0df6", X"06ca", X"fa70", X"15e5", X"0c97", X"f815", X"ff35",
                                                        X"0a44", X"ffde", X"d38f", X"f533", X"f9c2", X"fb0f", X"f976", X"f8d1", X"fe4e", X"eefe", X"10b6", X"f3c1", X"f167", X"feca",
                                                        X"1265", X"1312", X"e898", X"f422", X"156a", X"fa69", X"ecce", X"01a2", X"fb5a", X"033d", X"e71b", X"1630", X"f369", X"050e",
                                                        X"098b", X"01cc", X"ed35", X"02ac", X"02c8", X"0888", X"059b", X"eb22", X"f770", X"ed91", X"07c4", X"f9f6", X"f4a0", X"f86d",
                                                        X"0257", X"e66e", X"fcf2", X"0375", X"f30b", X"04e4", X"ee0a", X"0b0f", X"d75f", X"fa68", X"f820", X"ef7d", X"feb5", X"f2fb",
                                                        X"eaae", X"e396", X"e9c5", X"f99e", X"0f5d", X"090c", X"0906", X"008d", X"0862", X"f6b2", X"d1e1", X"0dd7", X"f2e3", X"f49a",
                                                        X"0a25", X"f5de", X"119f", X"07a9", X"2370", X"0229", X"09a8", X"ff11", X"090a", X"08fb", X"fbee", X"0dd6", X"030d", X"fb84",
                                                        X"1034", X"0a50", X"0db6", X"ea46", X"f26c", X"e89f", X"0feb", X"ec66", X"016d", X"f58f", X"026c", X"035f", X"04e2", X"edfe",
                                                        X"01e0", X"ee6c", X"24bd", X"fc28", X"17f9", X"e303", X"221c", X"1725", X"fce5", X"093f", X"180d", X"053d", X"101b", X"fb1b",
                                                        X"fd67", X"116e", X"0c3c", X"0629", X"0775", X"ec0a", X"14f3", X"27f1", X"1bda", X"1756", X"1de5", X"f88e", X"1923", X"fdc4",
                                                        X"0b1a", X"f79a", X"04bd", X"f289", X"f6d4", X"0235", X"fc34", X"0f5a", X"edb9", X"f685", X"20d4", X"fcfb", X"0437", X"138a",
                                                        X"0c0c", X"0c12", X"0477", X"1816", X"117e", X"0a0d", X"144f", X"02b8", X"f735", X"fee6", X"034a", X"f67a", X"14be", X"0c56",
                                                        X"ec73", X"eb99", X"f7f8", X"f4c8", X"0832", X"127b", X"f88d", X"e973", X"f12f", X"0099", X"0651", X"1312", X"09f6", X"0cba",
                                                        X"1326", X"1a9a", X"0b1f", X"10ca", X"0f97", X"eda2", X"fb12", X"fb32", X"f47e", X"e5d0", X"255a", X"1341", X"13ae", X"0ef1",
                                                        X"fc9e", X"0e33", X"20eb", X"1f5e", X"ed83", X"ebd4", X"fdd4", X"09f0", X"fa80", X"16bd", X"f8ca", X"f0bf", X"0d9c", X"0f3f",
                                                        X"0787", X"068c", X"e4b8", X"2524", X"15e6", X"0eee", X"1714", X"f100", X"056f", X"eaae", X"f4a7", X"1c2f", X"ffe1", X"1784",
                                                        X"0dd7", X"0905", X"fbec", X"f5c0", X"d94d", X"092d", X"ee77", X"f9a9", X"f3d9", X"0a2a", X"fd0a", X"f5a7", X"f78e", X"0bbb",
                                                        X"fd7f", X"f4c6", X"0000", X"fbd6", X"0d50", X"f525", X"fd09", X"fe0a", X"f587", X"eeac", X"0060", X"06e4", X"fa3b", X"044a",
                                                        X"e415", X"0270", X"e20c", X"20c6", X"0137", X"09bc", X"ffee", X"ff7f", X"e535", X"f257", X"0a44", X"f53d", X"ee29", X"167a",
                                                        X"ff06", X"f995", X"f244", X"146e", X"07b4", X"f9bc", X"f860", X"0762", X"0e90", X"0025", X"0476", X"0191", X"f0c1", X"f438",
                                                        X"dc2e", X"e87c", X"fc9d", X"f0ce", X"fadd", X"ec61", X"06b1", X"fed7", X"02c1", X"f3e3", X"f53d", X"f090", X"f839", X"0008",
                                                        X"f537", X"fdb9", X"0230", X"fcc2", X"fe28", X"0946", X"ef6e", X"f933", X"f9b8", X"f2c8", X"ec35", X"14d9", X"f2b5", X"eb91",
                                                        X"f3eb", X"f81a", X"de44", X"f7cf", X"1196", X"f872", X"0860", X"f07f", X"0ae6", X"08db", X"02b1", X"f76f", X"f2a8", X"f152",
                                                        X"ebbc", X"f342", X"ff46", X"103d", X"0cc7", X"dff8", X"1ef6", X"f106", X"0603", X"f9ad", X"0c9c", X"1787", X"035d", X"e8d0",
                                                        X"10ce", X"f271", X"08c3", X"027e", X"0b0e", X"ea3b", X"f40f", X"09a0", X"ee6d", X"fb85", X"078f", X"f5ee", X"fa4e", X"01a0",
                                                        X"1e45", X"02a7", X"fce2", X"e3d6", X"0504", X"00dc", X"2108", X"1095", X"f67d", X"da3c", X"1ba5", X"de8b", X"093d", X"167d",
                                                        X"117f", X"f142", X"ff7b", X"ef6c", X"e72f", X"eebe", X"fe00", X"076a", X"02c6", X"0301", X"f4b5", X"e101", X"0b99", X"06bb",
                                                        X"f140", X"f389", X"0d85", X"dbbb", X"ff78", X"e8b5", X"05d9", X"fe7c", X"1bbd", X"f33c", X"184f", X"19d2", X"0616", X"048e",
                                                        X"2496", X"f437", X"0b72", X"e7cf", X"ff61", X"f38c", X"0294", X"d53c", X"1115", X"fe7e", X"f80c", X"0d2d", X"00a5", X"f5ca",
                                                        X"0fce", X"f2e7", X"0d39", X"0708", X"053a", X"fce3", X"0b9c", X"ed51", X"f683", X"e66e", X"2cd5", X"04aa", X"f6b2", X"0508",
                                                        X"1e6c", X"117a", X"0a1d", X"f898", X"12b2", X"efac", X"0a43", X"fb6c", X"048e", X"19be", X"0b6d", X"15bb", X"fa59", X"f80b",
                                                        X"fd30", X"f87a", X"f3c2", X"ee47", X"edde", X"0eb4", X"e74e", X"0518", X"efb2", X"039b", X"0f11", X"16bc", X"1b2a", X"17d2",
                                                        X"ff7b", X"013c", X"116d", X"068d", X"fd21", X"eef0", X"1494", X"ffc0", X"2102", X"fb52", X"0235", X"02fb", X"0c20", X"1d8e",
                                                        X"f1d9", X"e871", X"0e9d", X"ed5f", X"f816", X"f059", X"fcb1", X"0899", X"1869", X"e00e", X"f453", X"f349", X"f84b", X"f147",
                                                        X"055b", X"f493", X"e96a", X"fb89", X"f827", X"13f3", X"0170", X"0e6b", X"f4f5", X"21b5", X"f289", X"1416", X"035d", X"eeeb",
                                                        X"0047", X"0447", X"e5c8", X"09da", X"21c4", X"03b8", X"18f7", X"fad6", X"04e3", X"0865", X"fba4", X"e516", X"0963", X"048f",
                                                        X"1547", X"f6db", X"08a1", X"f0e9", X"0242", X"ddc0", X"0b86", X"1b8d", X"f7d8", X"f476", X"f965", X"1078", X"07c1", X"f3a3",
                                                        X"e62a", X"efc0", X"0b71", X"03a3", X"fb41", X"feca", X"f1a7", X"13f2", X"0f49", X"dcbe", X"e62a", X"04ce", X"f577", X"f1fb",
                                                        X"039d", X"f1ac", X"0542", X"115b", X"1892", X"0417", X"09af", X"0c3d", X"e78d", X"1290", X"f089", X"069a", X"0ed8", X"f507",
                                                        X"0552", X"0f0a", X"fe33", X"1129", X"255a", X"fe5b", X"10b2", X"10a3", X"f3e6", X"017d", X"0085", X"1640", X"ff06", X"f494",
                                                        X"25cc", X"10b4", X"00a3", X"fc62", X"0610", X"23cb", X"0c62", X"073c", X"10ca", X"ffda", X"fc48", X"fc0a", X"0d8e", X"fe2e",
                                                        X"fb56", X"ef0b", X"e6b4", X"0e4d", X"d381", X"e8d7", X"e8b0", X"0aa0", X"edea", X"1064", X"f881", X"089e", X"02c3", X"0ad7",
                                                        X"f2c3", X"fd6c", X"0896", X"f30b", X"2578", X"05ed", X"dd42", X"0ccd", X"0bc2", X"f704", X"f574", X"108a", X"e23c", X"1c56",
                                                        X"10ae", X"080b", X"f836", X"09a4", X"ff34", X"f1aa", X"f2f4", X"063c", X"ff98", X"f758", X"f8fb", X"dfb5", X"0b79", X"ec30",
                                                        X"f764", X"f734", X"f25b", X"ed04", X"f632", X"ff0d", X"f580", X"f541", X"f449", X"0c00", X"0874", X"19f3", X"04f1", X"f4d7",
                                                        X"07a9", X"f97e", X"eb7a", X"0745", X"f2f1", X"f826", X"0c14", X"e4c3", X"0683", X"0203", X"0e7f", X"034d", X"0c1e", X"f52e",
                                                        X"12a8", X"1e5a", X"d598", X"f550", X"11ab", X"1081", X"fee3", X"fa99", X"fc8e", X"0117", X"00dc", X"10a7", X"e290", X"f7e4",
                                                        X"e6fa", X"f847", X"1d56", X"ff55", X"0e13", X"f630", X"f94a", X"02bb", X"1a81", X"e8ec", X"04cc", X"eb49", X"002d", X"0915",
                                                        X"1ba5", X"e1d0", X"1b61", X"012a", X"e336", X"149c", X"08ff", X"f804", X"fd69", X"f421", X"0015", X"eb5f", X"1e10", X"0f41",
                                                        X"f67d", X"1f1a", X"0e42", X"fe47", X"0534", X"02ff", X"e87a", X"fcd5", X"d915", X"0624", X"05e2", X"081c", X"f737", X"01c1",
                                                        X"16cb", X"f5a4", X"f746", X"1ca4", X"d418", X"e58f", X"f5d4", X"0944", X"fbae", X"fd14", X"084d", X"ed81", X"fb68", X"0520",
                                                        X"ffac", X"0419", X"f789", X"0ba2", X"05d8", X"0fb5", X"06fb", X"f902", X"ec51", X"f25f", X"ea7a", X"fdc5", X"f2f2", X"f74d",
                                                        X"fb8b", X"fc8a", X"09c5", X"f428", X"13a9", X"097f", X"f3e6", X"ff9f", X"030e", X"f4b5", X"e90c", X"ed29", X"0234", X"12ca",
                                                        X"fe35", X"0f6f", X"0188", X"fd40", X"f714", X"0c1e", X"0c38", X"f9e9", X"feba", X"03b5", X"18e2", X"fb36", X"f695", X"f789",
                                                        X"0dd5", X"ef70", X"e3af", X"02fb", X"f079", X"0efc", X"ed55", X"f80f", X"0820", X"0e04", X"1581", X"f5e8", X"e7c9", X"0b9f",
                                                        X"1348", X"1f41", X"eb04", X"065e", X"22ab", X"0078", X"ec88", X"1646", X"071e", X"0b5d", X"069d", X"e6df", X"fae8", X"14e4",
                                                        X"1abf", X"0688", X"0bf9", X"06ef", X"e7c2", X"f36d", X"29ba", X"f488", X"0159", X"ddf6", X"083e", X"0f09", X"f968", X"f77c",
                                                        X"f1d1", X"fe98", X"1ca5", X"0d7f", X"0628", X"fb6a", X"06de", X"179d", X"f31b", X"1b76", X"f962", X"00ff", X"1154", X"fee9",
                                                        X"e912", X"fb73", X"0711", X"1ab6", X"f49b", X"ea1e", X"0195", X"1085", X"fb02", X"04e7", X"2966", X"fd6b", X"feff", X"18da",
                                                        X"fddd", X"0720", X"fe7c", X"f6df", X"14cd", X"1c40", X"e86a", X"fd1b", X"f9f0", X"ef00", X"0708", X"f343", X"ef4e", X"14e3",
                                                        X"d68d", X"f005", X"ec4a", X"0b35", X"f238", X"f0e6", X"fd01", X"ff44", X"166e", X"fa2c", X"f763", X"07ba", X"1247", X"18ce",
                                                        X"e9db", X"1e75", X"fede", X"fa5d", X"f37a", X"0db4", X"eb62", X"001e", X"0149", X"022d", X"1e31", X"0d6f", X"f1c0", X"033b",
                                                        X"03c8", X"ff63", X"002c", X"0c2d", X"f99b", X"05d7", X"f30c", X"0a07", X"067e", X"1077", X"020f", X"155f", X"f384", X"fb9d",
                                                        X"f52f", X"fc27", X"f320", X"f68d", X"ebd0", X"15d3", X"0856", X"068e", X"1045", X"e6ee", X"0bbb", X"e83c", X"1bc0", X"14f1",
                                                        X"168e", X"f9a8", X"ffce", X"0ae3", X"0b3e", X"0e76", X"1e79", X"e7bf", X"ea5e", X"11ca", X"0d72", X"1b83", X"f4de", X"e9a3",
                                                        X"0579", X"f11e", X"e295", X"f475", X"f891", X"163a", X"0136", X"122f", X"2576", X"f6eb", X"0aec", X"1405", X"07fa", X"03e0",
                                                        X"15a3", X"f283", X"16fc", X"fe38", X"12b8", X"f68b", X"1cfc", X"03a3", X"06e9", X"f0ef", X"20c3", X"0460", X"f64b", X"0a26",
                                                        X"f39b", X"deac", X"0e60", X"1915", X"0389", X"05cd", X"f44c", X"e622", X"0d27", X"eb4c", X"eb75", X"12da", X"f5f7", X"13f1",
                                                        X"ef2d", X"0bda", X"1d0d", X"0e8a", X"fdc5", X"1261", X"f7d3", X"fce6", X"ec5d", X"024f", X"e9f1", X"1b8e", X"fd7f", X"2194",
                                                        X"f1b4", X"1d2f", X"0c49", X"0a05", X"f2b9", X"09d1", X"141d", X"0434", X"1cb6", X"f8db", X"2190", X"0779", X"f65c", X"f5e6",
                                                        X"f099", X"1651", X"f1ee", X"e45d", X"1787", X"fed9", X"fbb6", X"fad0", X"023b", X"2887", X"ef0a", X"0b42", X"d770", X"f695",
                                                        X"02c8", X"18e5", X"16c2", X"2583", X"0906", X"147a", X"e69f", X"004c", X"0610", X"f44e", X"0814", X"039f", X"fc87", X"f891",
                                                        X"2577", X"0a4f", X"ecc0", X"1343", X"ed18", X"fc2e", X"e6b3", X"0745", X"ff42", X"f349", X"f36c", X"03e5", X"f609", X"f053",
                                                        X"0bcd", X"1069", X"121c", X"1795", X"e2d6", X"0716", X"07c4", X"1941", X"0f2f", X"f5ef", X"0b63", X"08b8", X"1214", X"02ae",
                                                        X"f113", X"0680", X"1da6", X"e2ba", X"1a31", X"fab9", X"0751", X"fd91", X"1143", X"ee50", X"00fc", X"f348", X"f3a3", X"e848",
                                                        X"ff2e", X"000b", X"feb6", X"10e8", X"0e8b", X"e739", X"105b", X"04ce", X"f1dc", X"ffb3", X"0bd2", X"f9ce", X"0055", X"0365",
                                                        X"fd70", X"fe05", X"f715", X"ebd4", X"ee5a", X"05dc", X"0644", X"1841", X"f272", X"fdcb", X"08a3", X"f860", X"0149", X"26a5",
                                                        X"e804", X"f469", X"0de3", X"ee9e", X"068d", X"0945", X"eed3", X"f18c", X"0ee9", X"0619", X"ef6a", X"02c3", X"01e0", X"ffa9",
                                                        X"02a1", X"115f", X"e795", X"ebc4", X"fb6c", X"f871", X"efe5", X"0cb0", X"e331", X"035a", X"0a53", X"fb76", X"086d", X"0d32",
                                                        X"fe11", X"0e93", X"0014", X"07fd", X"f07f", X"e64f", X"18ae", X"ea17", X"f982", X"0115", X"00c0", X"180a", X"f120", X"0f97",
                                                        X"1b8a", X"fe6b", X"00d6", X"f3c1", X"f80b", X"e7a6", X"f1ca", X"0f8e", X"0158", X"f034", X"f0ad", X"0f33", X"fc87", X"fae6",
                                                        X"e7a3", X"f734", X"de7b", X"0341", X"f5ef", X"f904", X"f98d", X"154a", X"e870", X"d667", X"f677", X"fe76", X"f502", X"06e2",
                                                        X"fd88", X"0ad8", X"febf", X"f468", X"080e", X"ff8a", X"1121", X"0e4b", X"fc5f", X"06a4", X"f1b2", X"fded", X"f3b9", X"f8ca",
                                                        X"fad7", X"0994", X"140d", X"e9ae", X"1886", X"0f90", X"f151", X"ebd5", X"0672", X"ff13", X"fe71", X"2169", X"f206", X"e061",
                                                        X"fe93", X"04f7", X"1f23", X"f482", X"0669", X"04b0", X"08e4", X"ec8e", X"d3e8", X"0208", X"068c", X"fbd3", X"e89a", X"04b8",
                                                        X"eb1c", X"f29a", X"007b", X"056d", X"0495", X"ed96", X"06e0", X"f7f4", X"f83c", X"0357", X"d5b3", X"07e4", X"f570", X"fdbd",
                                                        X"e8a5", X"00bb", X"db6d", X"f14d", X"f288", X"1aac", X"06c3", X"ee76", X"02d0", X"ef95", X"f166", X"f7bb", X"e3a9", X"e296",
                                                        X"ee3f", X"0177", X"079b", X"11a6", X"019f", X"0038", X"06fb", X"f1db", X"fc7d", X"08db", X"094b", X"fb6c", X"ffe3", X"f29a",
                                                        X"d62a", X"e643", X"f581", X"03b0", X"ecd2", X"f1fd", X"021f", X"f824", X"1046", X"eeea", X"f1fe", X"073a", X"010b", X"01db",
                                                        X"0a78", X"f794", X"ec70", X"e237", X"fa41", X"f9f6", X"039b", X"1d94", X"e1c6", X"d6b2", X"fc7e", X"f2bb", X"0e2d", X"e31e",
                                                        X"177c", X"fa06", X"ef04", X"e2d4", X"cc1a", X"f028", X"15d0", X"fb7f", X"e43d", X"e12d", X"d7bf", X"f5af", X"f7e7", X"039f",
                                                        X"fb90", X"ff59", X"fb7e", X"e9a2");
  SIGNAL data_int                         : std_logic_vector(DataWidth - 1 DOWNTO 0) := X"e9a2";
  SIGNAL addr_unsigned                    : unsigned(AddrWidth - 1 DOWNTO 0);  -- generic width

BEGIN
  addr_unsigned <= unsigned(addr);

  SinglePortRAM_generic_process: PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF enb = '1' THEN
        IF we = '1' THEN
          ram(to_integer(addr_unsigned)) <= din;
          data_int <= din;
        ELSE
          data_int <= ram(to_integer(addr_unsigned));
        END IF;
      END IF;
    END IF;
  END PROCESS SinglePortRAM_generic_process;

  dout <= data_int;

END rtl;

