-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/amc_model_w16a16/amc_cnn_16w16a_src_SinglePortRAM_generic_block7.vhd
-- Created: 2023-08-04 11:27:08
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: amc_cnn_16w16a_src_SinglePortRAM_generic_block7
-- Source Path: amc_model_w16a16/DUT HDL/Dense Layer 2/Dense Layer 2/Weight Storage 6/SinglePortRAM_generic
-- Hierarchy Level: 4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY amc_cnn_16w16a_src_SinglePortRAM_generic_block7 IS
  GENERIC( AddrWidth                      : integer := 1;
           DataWidth                      : integer := 1
           );
  PORT( clk                               :   IN    std_logic;
        enb                               :   IN    std_logic;
        din                               :   IN    std_logic_vector(DataWidth - 1 DOWNTO 0);  -- generic width
        addr                              :   IN    std_logic_vector(AddrWidth - 1 DOWNTO 0);  -- generic width
        we                                :   IN    std_logic;  -- ufix1
        dout                              :   OUT   std_logic_vector(DataWidth - 1 DOWNTO 0)  -- generic width
        );
END amc_cnn_16w16a_src_SinglePortRAM_generic_block7;


ARCHITECTURE rtl OF amc_cnn_16w16a_src_SinglePortRAM_generic_block7 IS

  -- Local Type Definitions
  TYPE ram_type IS ARRAY (2**AddrWidth - 1 DOWNTO 0) of std_logic_vector(DataWidth - 1 DOWNTO 0);

  -- Signals
  SIGNAL ram                              : ram_type := (X"1d5f", X"8052", X"dd4a", X"6a4d", X"66c1", X"c44d", X"7faf", X"6098", X"8000", X"7f88", X"8abd", X"f9f3", X"b6ca", X"ca73",
                                                        X"33b0", X"7fb0", X"6548", X"c36a", X"be83", X"ec21", X"ea0b", X"ea05", X"ebf5", X"cd6f", X"1054", X"8029", X"eec7", X"6749",
                                                        X"04e5", X"e4fc", X"1158", X"beba", X"268f", X"6239", X"7f5d", X"f0dc", X"f0c4", X"6e41", X"881f", X"9247", X"ff74", X"13e9",
                                                        X"0f90", X"7fd5", X"e628", X"48b8", X"abf7", X"e2d6", X"2614", X"007c", X"4232", X"23dc", X"f02e", X"4c0d", X"0462", X"7821",
                                                        X"5f8e", X"0b55", X"8002", X"01fa", X"0acf", X"7f1f", X"f687", X"cc2f", X"082e", X"8015", X"0273", X"5ca9", X"646d", X"fac6",
                                                        X"690e", X"061a", X"80b8", X"0213", X"9cdc", X"7ee4", X"0c45", X"7f85", X"fa7c", X"fb7b", X"2865", X"5af6", X"0425", X"106d",
                                                        X"a5c7", X"04e1", X"c138", X"fa19", X"7f12", X"1d8b", X"87fa", X"0321", X"12a3", X"ee44", X"7fb6", X"cf09", X"366c", X"0000",
                                                        X"ff8b", X"e10c", X"801d", X"dfe8", X"7421", X"1215", X"0787", X"8009", X"03ab", X"78e8", X"6b8e", X"4f7b", X"2932", X"df49",
                                                        X"01ef", X"2a83", X"95b5", X"4244", X"2252", X"92df", X"8000", X"b893", X"eb36", X"7fdf", X"803d", X"0246", X"7320", X"1475",
                                                        X"d7ca", X"5627");
  SIGNAL data_int                         : std_logic_vector(DataWidth - 1 DOWNTO 0) := X"5627";
  SIGNAL addr_unsigned                    : unsigned(AddrWidth - 1 DOWNTO 0);  -- generic width

BEGIN
  addr_unsigned <= unsigned(addr);

  SinglePortRAM_generic_process: PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF enb = '1' THEN
        IF we = '1' THEN
          ram(to_integer(addr_unsigned)) <= din;
          data_int <= din;
        ELSE
          data_int <= ram(to_integer(addr_unsigned));
        END IF;
      END IF;
    END IF;
  END PROCESS SinglePortRAM_generic_process;

  dout <= data_int;

END rtl;

