-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/amc_model_w16a16/amc_cnn_16w16a_src_SinglePortRAM_generic_block413.vhd
-- Created: 2023-08-04 11:27:24
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: amc_cnn_16w16a_src_SinglePortRAM_generic_block413
-- Source Path: amc_model_w16a16/DUT HDL/Dense Layer 1/Dense Layer 1/Weight Storage6/SinglePortRAM_generic
-- Hierarchy Level: 4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY amc_cnn_16w16a_src_SinglePortRAM_generic_block413 IS
  GENERIC( AddrWidth                      : integer := 1;
           DataWidth                      : integer := 1
           );
  PORT( clk                               :   IN    std_logic;
        enb                               :   IN    std_logic;
        din                               :   IN    std_logic_vector(DataWidth - 1 DOWNTO 0);  -- generic width
        addr                              :   IN    std_logic_vector(AddrWidth - 1 DOWNTO 0);  -- generic width
        we                                :   IN    std_logic;  -- ufix1
        dout                              :   OUT   std_logic_vector(DataWidth - 1 DOWNTO 0)  -- generic width
        );
END amc_cnn_16w16a_src_SinglePortRAM_generic_block413;


ARCHITECTURE rtl OF amc_cnn_16w16a_src_SinglePortRAM_generic_block413 IS

  -- Local Type Definitions
  TYPE ram_type IS ARRAY (2**AddrWidth - 1 DOWNTO 0) of std_logic_vector(DataWidth - 1 DOWNTO 0);

  -- Signals
  SIGNAL ram                              : ram_type := (X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"2880", X"e9e1", X"0746", X"1662", X"fb9e", X"3272",
                                                        X"02e2", X"f029", X"0602", X"1d08", X"0401", X"d635", X"ec1e", X"219c", X"0589", X"1008", X"fc72", X"0a99", X"f27a", X"0a4b",
                                                        X"f74a", X"ec6c", X"0803", X"f1e8", X"3b34", X"dbf9", X"d265", X"ef81", X"e618", X"2104", X"fef4", X"fbf2", X"0efe", X"0f43",
                                                        X"ff7f", X"12f1", X"f419", X"fb83", X"1a6e", X"2c47", X"0c45", X"ef28", X"d667", X"fe5c", X"ee56", X"0871", X"01c6", X"f715",
                                                        X"007f", X"fb9a", X"ef6e", X"ea6a", X"ff4c", X"084e", X"feeb", X"069c", X"ea02", X"16c3", X"f75e", X"1673", X"1946", X"067b",
                                                        X"0f1d", X"0bf2", X"fe7f", X"ed25", X"0a12", X"f13e", X"138f", X"ef93", X"fdcc", X"f404", X"021a", X"fe97", X"0fa1", X"196f",
                                                        X"fe0f", X"0caa", X"04fb", X"fc8c", X"09a4", X"0bd0", X"225b", X"e2bc", X"f4b2", X"f15e", X"12b6", X"fedc", X"14bd", X"0414",
                                                        X"ec77", X"1900", X"0e61", X"004d", X"f3b4", X"ff65", X"0c29", X"0a98", X"1fce", X"fe2a", X"fffa", X"f416", X"0e8a", X"ea66",
                                                        X"e9f3", X"e67b", X"2be8", X"ffa5", X"2b48", X"f98e", X"1dce", X"03e3", X"f272", X"ea48", X"e7d0", X"d2cf", X"e874", X"fba4",
                                                        X"0786", X"017c", X"e723", X"ed91", X"0e59", X"fbe9", X"1b31", X"ee64", X"0791", X"f999", X"fff6", X"ed88", X"0e23", X"e40d",
                                                        X"f453", X"fd9d", X"0f3d", X"05a8", X"d7c9", X"fae7", X"ec3d", X"e5dc", X"f6c7", X"084a", X"1f67", X"0b96", X"e2ff", X"1264",
                                                        X"0ef7", X"df0e", X"1ac6", X"e73f", X"11c8", X"0909", X"f07f", X"f1ba", X"ed8f", X"ee43", X"f459", X"06de", X"fc1c", X"f98a",
                                                        X"0405", X"f45d", X"1c75", X"fc96", X"ddf0", X"f7e6", X"f0c4", X"0adc", X"fcc0", X"eeba", X"ef5e", X"f3f4", X"fd2d", X"f908",
                                                        X"0ae5", X"080e", X"fe75", X"fa0f", X"020b", X"0e34", X"01c5", X"f451", X"2837", X"00db", X"15ae", X"f791", X"fe9f", X"f766",
                                                        X"000e", X"eba4", X"0222", X"099b", X"f1d3", X"e77c", X"e53f", X"1f9b", X"f62b", X"f1bd", X"1a8d", X"162c", X"f0e3", X"1004",
                                                        X"f235", X"fb7e", X"f9e2", X"eee8", X"1a2b", X"0598", X"fee1", X"f521", X"08b8", X"f5fb", X"ff58", X"10ae", X"1df6", X"dff3",
                                                        X"f200", X"f7f6", X"19f3", X"1eac", X"0ca2", X"e237", X"0306", X"008e", X"1e31", X"0986", X"e7ea", X"f74d", X"fe18", X"2195",
                                                        X"0219", X"f1b4", X"e86b", X"005b", X"0926", X"fe91", X"0e2d", X"0b46", X"007e", X"f8d4", X"0209", X"056f", X"e4d9", X"f5a5",
                                                        X"f54c", X"0f2f", X"1f3c", X"04dd", X"0d54", X"0cb2", X"0b28", X"f4aa", X"096c", X"f6d9", X"fc0e", X"08e6", X"17ed", X"faba",
                                                        X"f8ac", X"104a", X"f2c5", X"0299", X"f981", X"ff71", X"0dc0", X"0a54", X"1191", X"f45e", X"00bd", X"189f", X"1082", X"0ed7",
                                                        X"0b8b", X"124c", X"0ad8", X"eda9", X"f564", X"1045", X"0ce5", X"0863", X"fef2", X"f907", X"1117", X"e817", X"edb8", X"0db8",
                                                        X"080c", X"0566", X"0342", X"faa6", X"fd47", X"f81e", X"034a", X"efa2", X"f782", X"219c", X"fa42", X"f369", X"f25b", X"e9bb",
                                                        X"eaa7", X"0da6", X"e70b", X"0137", X"139e", X"f1f8", X"0b1d", X"f478", X"025c", X"f575", X"0dbb", X"1451", X"33dd", X"0376",
                                                        X"e635", X"f565", X"f2f5", X"096f", X"f836", X"f77e", X"0df9", X"0ef3", X"190b", X"f29b", X"fa7d", X"eb0b", X"f139", X"fe99",
                                                        X"fd94", X"e6fd", X"05de", X"1470", X"0cc7", X"0484", X"f6a6", X"f261", X"fccc", X"efaa", X"eda4", X"06b6", X"f671", X"fbed",
                                                        X"0d1a", X"fee6", X"fd44", X"10b3", X"223e", X"12dc", X"2220", X"194e", X"f174", X"0c48", X"0ce9", X"f4af", X"fbb3", X"01fd",
                                                        X"e82b", X"f950", X"f062", X"fc33", X"09a1", X"141e", X"08f2", X"2abf", X"0c39", X"0397", X"0237", X"1900", X"0e94", X"e87d",
                                                        X"fc5f", X"f2d1", X"ef26", X"ea93", X"0ac4", X"f4dc", X"d471", X"faef", X"30eb", X"f55b", X"1100", X"0737", X"0c3b", X"07ba",
                                                        X"0119", X"f77a", X"decb", X"ee71", X"e28d", X"e6b8", X"09c7", X"fc42", X"e843", X"0586", X"0f5a", X"e6e3", X"0e09", X"f18e",
                                                        X"0905", X"fe87", X"ec01", X"0ee9", X"1571", X"ec63", X"e4a2", X"ecd1", X"f6f3", X"eac1", X"212c", X"dc61", X"0a2c", X"e945",
                                                        X"efa8", X"fd18", X"f7b4", X"ee37", X"f5cd", X"181d", X"fa6f", X"ecc5", X"0113", X"e4c0", X"ed78", X"f565", X"f3fc", X"feb2",
                                                        X"ee35", X"ff2a", X"01e4", X"082c", X"0ffc", X"e4b0", X"fe2f", X"f4c9", X"f254", X"f971", X"011f", X"ed18", X"08c6", X"1e04",
                                                        X"11f1", X"0484", X"f8d8", X"f3fd", X"f046", X"fbc6", X"fcf5", X"e3b8", X"f0b6", X"20fc", X"cdcc", X"ed9b", X"ff78", X"10c6",
                                                        X"0522", X"0f99", X"0067", X"fca5", X"f773", X"074b", X"f0e5", X"05b1", X"002b", X"04af", X"0ed9", X"0d9a", X"eadd", X"0155",
                                                        X"e87d", X"292c", X"f969", X"e554", X"0255", X"f000", X"10c5", X"11e5", X"fe56", X"0c13", X"ff11", X"0ba1", X"12e6", X"0f19",
                                                        X"e1ab", X"29d2", X"f63c", X"0a7a", X"02d8", X"e97b", X"c9fc", X"ed65", X"15ce", X"0768", X"fd4c", X"03c2", X"ec11", X"ffdd",
                                                        X"1470", X"13a2", X"04ad", X"f832", X"f6e2", X"29c0", X"1425", X"067b", X"029f", X"0cb7", X"0cbf", X"0267", X"0404", X"f071",
                                                        X"06a7", X"02c2", X"09ac", X"f2b2", X"e24d", X"f0e4", X"fe02", X"1f74", X"fc60", X"0130", X"f9f3", X"fdf6", X"f1d6", X"0e06",
                                                        X"fadd", X"f615", X"fdf8", X"017b", X"f729", X"018b", X"e04a", X"072c", X"f537", X"15d6", X"05aa", X"d71b", X"0170", X"f68b",
                                                        X"ec5b", X"ecf2", X"e511", X"0c70", X"f583", X"ee27", X"09ad", X"13c6", X"edb7", X"0096", X"e250", X"f2f0", X"124e", X"043b",
                                                        X"225a", X"fa61", X"10d0", X"ef64", X"f1c5", X"1068", X"d83e", X"f8ff", X"08bd", X"0046", X"10be", X"e930", X"168c", X"f843",
                                                        X"0350", X"0a1a", X"2048", X"fd34", X"0566", X"f899", X"ed27", X"1190", X"e84d", X"09f7", X"07a1", X"093b", X"26b3", X"0ace",
                                                        X"fd13", X"06b5", X"0315", X"065a", X"022d", X"fd0c", X"fe79", X"f4db", X"06d3", X"0a32", X"0b16", X"f254", X"0895", X"1334",
                                                        X"eff0", X"ebf4", X"097d", X"f8e0", X"ff27", X"09b5", X"e9f1", X"e9a0", X"0905", X"12aa", X"0e8e", X"1592", X"fa1c", X"f40f",
                                                        X"16dc", X"01b0", X"f95c", X"e653", X"e8c6", X"0799", X"fde7", X"05a5", X"066b", X"0681", X"0a18", X"0f6b", X"22d5", X"0741",
                                                        X"02e3", X"f778", X"fd58", X"ef96", X"e1ee", X"f8bf", X"0544", X"f79a", X"044e", X"dd78", X"2450", X"166e", X"2471", X"1177",
                                                        X"168e", X"0f08", X"fa71", X"fa56", X"03c2", X"f703", X"0421", X"f264", X"0170", X"f201", X"0311", X"fd71", X"ef4d", X"fcd9",
                                                        X"12a1", X"f635", X"0e92", X"faa9", X"025a", X"eb27", X"072b", X"051f", X"2f99", X"fc82", X"fc30", X"fdb1", X"03ce", X"139b",
                                                        X"0523", X"face", X"1a8c", X"f4e0", X"0d25", X"07fd", X"068f", X"f78b", X"fb05", X"f90d", X"f4e1", X"efae", X"e3d5", X"f452",
                                                        X"02a9", X"30f8", X"0161", X"07c0", X"f49b", X"f646", X"0041", X"0a6b", X"0918", X"f088", X"e96c", X"fd4b", X"0543", X"f329",
                                                        X"fb0b", X"082b", X"0d53", X"030b", X"08bd", X"e975", X"e69a", X"04d0", X"162b", X"0286", X"0f7b", X"f957", X"f197", X"17a6",
                                                        X"1149", X"f4bb", X"ffba", X"fed8", X"f76f", X"1614", X"eeaf", X"fa5a", X"1570", X"fb79", X"1013", X"02a2", X"1736", X"00ad",
                                                        X"f208", X"0bf0", X"f19e", X"09e9", X"ef98", X"fc49", X"1cfd", X"f1f8", X"d8cf", X"ff78", X"0504", X"e747", X"0876", X"e50e",
                                                        X"0525", X"e80b", X"005d", X"081b", X"d81d", X"176a", X"0ae1", X"fe79", X"0147", X"e9a4", X"066d", X"f699", X"f9be", X"f929",
                                                        X"f9a7", X"fc07", X"071b", X"0aa5", X"18cc", X"1060", X"f0be", X"f5b4", X"ec26", X"1960", X"0623", X"0c5e", X"f5c0", X"fd20",
                                                        X"041a", X"fc59", X"0cd6", X"f786", X"1276", X"12f4", X"087b", X"02d8", X"03f7", X"19e5", X"1d75", X"1304", X"003b", X"df81",
                                                        X"ff4a", X"f7b4", X"09c8", X"e6f9", X"f845", X"0b94", X"05db", X"e855", X"0eaf", X"eb53", X"0336", X"1827", X"eedf", X"1ce8",
                                                        X"fb41", X"f1c5", X"18b3", X"e7d3", X"052b", X"fbb6", X"e9f1", X"0d0c", X"f79a", X"0237", X"ee21", X"1add", X"d795", X"fb69",
                                                        X"ebcc", X"0d87", X"128f", X"fd46", X"1eb3", X"e579", X"f2d3", X"f542", X"eefe", X"07f1", X"fc60", X"f693", X"053b", X"09ab",
                                                        X"ca2b", X"fcc2", X"fd00", X"f39b", X"0902", X"0205", X"103b", X"f4e5", X"fc88", X"05bf", X"ef76", X"0865", X"fba4", X"fa1b",
                                                        X"09c7", X"fa7b", X"d551", X"ea6b", X"0844", X"fe81", X"0986", X"0fee", X"049c", X"ff74", X"0c25", X"0071", X"fe50", X"15fc",
                                                        X"093f", X"02a2", X"0257", X"f965", X"1c9e", X"d9b5", X"156a", X"e88b", X"0be5", X"0a4a", X"1cde", X"0e24", X"1fe2", X"1e70",
                                                        X"0467", X"0a34", X"0940", X"f92e", X"0685", X"0454", X"e709", X"fc89", X"09bb", X"f0e1", X"f0d3", X"e5f4", X"facb", X"f6e4",
                                                        X"147e", X"1815", X"0980", X"fde9", X"0ede", X"0e53", X"0a42", X"0a1d", X"e28c", X"e461", X"f23e", X"00ab", X"fad7", X"fd96",
                                                        X"052e", X"f9a7", X"0a37", X"222d", X"105a", X"f9bf", X"ffe7", X"0c0c", X"f36b", X"0032", X"e5e3", X"df83", X"14de", X"f371",
                                                        X"ecf7", X"e0af", X"0e11", X"0c0f", X"27d6", X"f792", X"049c", X"0b7b", X"096a", X"1124", X"f2e0", X"eaf7", X"11d5", X"e74a",
                                                        X"f9f9", X"e191", X"f9e9", X"f6fa", X"161f", X"f603", X"23a3", X"faa4", X"169c", X"f2f7", X"02db", X"16dd", X"f887", X"052f",
                                                        X"e229", X"e717", X"0a0f", X"ef13", X"02c6", X"2433", X"e867", X"fc65", X"0a7c", X"f493", X"08a7", X"f1e9", X"01eb", X"016e",
                                                        X"fd79", X"05c6", X"ed58", X"04fd", X"fdd9", X"ee4c", X"f4e5", X"2986", X"1ab8", X"feee", X"f0bf", X"01b0", X"f8bc", X"15b8",
                                                        X"144d", X"f373", X"fbbe", X"1121", X"175c", X"e1ea", X"f8e9", X"ed7c", X"09a1", X"041f", X"07d2", X"f044", X"fd1d", X"e9fd",
                                                        X"f6a5", X"f7e7", X"041c", X"fbb7", X"02c2", X"0dba", X"02db", X"0df2", X"fd25", X"01d6", X"f62e", X"fa5e", X"e0c4", X"0dc8",
                                                        X"ffa3", X"02b3", X"f490", X"f4e0", X"0a43", X"fce9", X"15ad", X"12d7", X"03ca", X"04e6", X"03df", X"095e", X"04c0", X"fb39",
                                                        X"13f4", X"06a4", X"fca9", X"fa3e", X"fae3", X"0a8a", X"0118", X"ef47", X"0af0", X"072c", X"ed9b", X"f534", X"ee3f", X"2101",
                                                        X"f0db", X"e31a", X"fcdd", X"102e", X"f1c4", X"1372", X"fc4e", X"0d46", X"ef86", X"f235", X"f9c8", X"1205", X"dd34", X"1548",
                                                        X"0375", X"1a35", X"1a97", X"01c7", X"d856", X"17f9", X"fa6f", X"05ba", X"0d9f", X"0286", X"f870", X"fcd9", X"22c7", X"ea88",
                                                        X"dae4", X"02c8", X"15e6", X"0bed", X"0bc2", X"0c34", X"0b9f", X"0396", X"1096", X"12ed", X"1ac6", X"0166", X"0c1a", X"1b80",
                                                        X"f826", X"2024", X"efad", X"102b", X"e0a5", X"f8ef", X"09b4", X"0fef", X"ebba", X"13f2", X"f82a", X"f451", X"f6c3", X"ea91",
                                                        X"f427", X"12cc", X"ff4d", X"0564", X"ed43", X"f425", X"f883", X"f95c", X"0dc6", X"ec75", X"0862", X"0587", X"f678", X"de0d",
                                                        X"ed97", X"09a8", X"10aa", X"f8d0", X"f177", X"0900", X"d28c", X"f726", X"123a", X"f79a", X"fa0b", X"e527", X"1290", X"ea24",
                                                        X"e585", X"f963", X"ff0a", X"fd69", X"f4e5", X"e6f3", X"ec6a", X"0927", X"1329", X"f854", X"f516", X"da68", X"2647", X"fefe",
                                                        X"e6ef", X"e55b", X"148c", X"0a00", X"0773", X"060e", X"fcec", X"ec55", X"0927", X"2098", X"dfdf", X"0be1", X"fc76", X"f996",
                                                        X"fc79", X"fc36", X"186d", X"edaf", X"1e0a", X"1023", X"13a7", X"f1d3", X"00fb", X"f8ce", X"ff3d", X"1943", X"06dc", X"d64b",
                                                        X"ffdb", X"1135", X"f386", X"f221", X"101a", X"1399", X"2694", X"1249", X"f988", X"f6c3", X"0c5f", X"0d1e", X"1048", X"01d5",
                                                        X"e85e", X"f3f1", X"eab1", X"e965", X"059c", X"f642", X"e90c", X"fe99", X"ff43", X"ea09", X"0250", X"10ef", X"0aa4", X"fbcc",
                                                        X"0d63", X"e719", X"0ada", X"f9da", X"09ce", X"ee05", X"fc17", X"dcaf", X"d7ed", X"01ce", X"f0d1", X"f2f1", X"1770", X"f755",
                                                        X"27ed", X"0417", X"faab", X"fbcb", X"26c8", X"e41c", X"023b", X"e5dc", X"e9e5", X"f57c", X"f816", X"0112", X"2abe", X"0a8c",
                                                        X"0e72", X"e52a", X"0047", X"08ef", X"e2f7", X"f2b2", X"0a1c", X"f30a", X"f2c7", X"d84b", X"f8b6", X"08ab", X"f777", X"f372",
                                                        X"f727", X"f17c", X"08cf", X"142f", X"031b", X"f5f7", X"00fc", X"1a35", X"0ea3", X"0db2", X"fc59", X"ef78", X"1b6c", X"ffdd",
                                                        X"1fe8", X"f47d", X"fdd5", X"f597", X"e949", X"e664", X"0ae3", X"ecd4", X"f996", X"15aa", X"f572", X"1164", X"0b19", X"ffb5",
                                                        X"137e", X"e911", X"ff7d", X"00b6", X"f3b1", X"01f9", X"fd07", X"13ff", X"0522", X"0f02", X"ffd1", X"2452", X"e860", X"0551",
                                                        X"dad5", X"1373", X"17e6", X"f1b3", X"fc1e", X"0823", X"1274", X"0e87", X"0035", X"ed8f", X"f934", X"1695", X"f59b", X"fc57",
                                                        X"e37b", X"0729", X"063c", X"0785", X"f7da", X"e139", X"f017", X"0a05", X"1312", X"0a7d", X"f9ab", X"f7a8", X"0cb3", X"01a6",
                                                        X"fdce", X"f921", X"ce1e", X"fc5a", X"0606", X"264c", X"f2d3", X"f48d", X"0881", X"052c", X"0c4c", X"0327", X"08e4", X"0658",
                                                        X"f7eb", X"0b57", X"09f6", X"0e68", X"1303", X"1d38", X"fd11", X"0854", X"e5fc", X"f090", X"f4a7", X"18f4", X"f894", X"fb1e",
                                                        X"0d8d", X"f807", X"fafe", X"1831", X"1ada", X"0872", X"f828", X"0db9", X"f78b", X"fcf1", X"0279", X"0176", X"f434", X"eb09",
                                                        X"f8e3", X"0c56", X"05be", X"0416", X"032e", X"0644", X"0270", X"2842", X"d4b7", X"02a6", X"f227", X"ff0e", X"0f6d", X"f1c2",
                                                        X"2e4d", X"f144", X"f112", X"ece6", X"f830", X"1b69", X"f10f", X"0dd0", X"ed9d", X"0cbe", X"d987", X"fe73", X"08d4", X"f2ec",
                                                        X"fb60", X"18ca", X"f9b0", X"fc89", X"1bb3", X"f219", X"ea6d", X"ff70", X"f9ce", X"fbe7", X"fcfb", X"0a0f", X"1225", X"ee5c",
                                                        X"147c", X"0640", X"0b90", X"ef2d", X"17ba", X"f949", X"195c", X"0176", X"00b4", X"0bac", X"03e3", X"ed68", X"0722", X"18f6",
                                                        X"f067", X"e9ea", X"02fb", X"0724", X"107f", X"fc6b", X"18c8", X"10c2", X"fcec", X"11b9", X"0560", X"078c", X"0332", X"061d",
                                                        X"f4c3", X"0661", X"1b6e", X"edc9", X"fc89", X"0369", X"fb9e", X"f428", X"ee15", X"1b28", X"06fa", X"0987", X"0f42", X"1239",
                                                        X"0a80", X"0c5e", X"01a4", X"08d6", X"f302", X"e831", X"0c4a", X"f43e", X"ff20", X"09b3", X"fc45", X"0865", X"f1e0", X"ff6a",
                                                        X"0c83", X"f5f0", X"140a", X"0ab4", X"f631", X"ed39", X"088c", X"f318", X"fe5f", X"e896", X"f137", X"d027", X"fa27", X"eb91",
                                                        X"0680", X"06ed", X"024b", X"030f", X"100c", X"068c", X"0304", X"06fe", X"0dbf", X"fc39", X"ed84", X"e5f7", X"016a", X"0d40",
                                                        X"e440", X"0ebd", X"1161", X"f697", X"0fe3", X"006c", X"14cd", X"04db", X"fd6a", X"01cb", X"0ca0", X"f243", X"fab8", X"f034",
                                                        X"fd0c", X"055c", X"e8b3", X"ff93", X"ec2b", X"f2a5", X"0ad9", X"f5b3", X"115e", X"02f2", X"efe2", X"00c9", X"03a9", X"ecbf",
                                                        X"f233", X"e2cd", X"e98a", X"e8e9", X"0206", X"fa41", X"f2d8", X"fa62", X"00eb", X"e293", X"1fef", X"f6db", X"fa5e", X"078c",
                                                        X"11a6", X"0709", X"f779", X"f320", X"fbbe", X"1341", X"0fc9", X"0d16", X"f369", X"0ec0", X"1190", X"fa85", X"03e1", X"f157",
                                                        X"e536", X"fb84", X"1217", X"1fad", X"fd97", X"0bd1", X"0f4d", X"1ef4", X"f0dd", X"fdb3", X"fc08", X"03f3", X"f8af", X"ff2b",
                                                        X"f233", X"e039", X"01cc", X"1200", X"e807", X"13a7", X"f7c1", X"fb50", X"fd55", X"0e90", X"e7a4", X"0c0f", X"fcb2", X"fc35",
                                                        X"0633", X"f632", X"075b", X"f9b0", X"07ba", X"0086", X"ec7b", X"1225", X"0052", X"2803", X"1735", X"e921", X"05c7", X"0488",
                                                        X"0a84", X"072f", X"0fac", X"e453", X"09e7", X"094b", X"0411", X"0632", X"20c3", X"eaea", X"ff8d", X"1b70", X"f729", X"e37d",
                                                        X"ecf4", X"02ce", X"f95a", X"f400", X"0257", X"ef48", X"1f0d", X"0c09", X"0cc3", X"1d7d", X"e5e1", X"fa7b", X"e97d", X"12e2",
                                                        X"0e69", X"d9f4", X"0cd6", X"217b", X"01a9", X"0d66", X"f348", X"0293", X"092b", X"17c4", X"00c9", X"0281", X"19cc", X"0af7",
                                                        X"e49c", X"02f4", X"0236", X"07b2", X"0770", X"062b", X"098e", X"0358", X"fbc8", X"090b", X"e9c7", X"ff10", X"fbb0", X"1d2d",
                                                        X"d78a", X"0447", X"fe54", X"0423", X"f7c5", X"f7bc", X"028d", X"ece6", X"1476", X"fa69", X"f48a", X"0ca1", X"f8dc", X"ffce",
                                                        X"02b9", X"0475", X"f96d", X"fcf1", X"f51a", X"fc43", X"14b6", X"f903", X"e692", X"ec14", X"f810", X"e8d3", X"ede5", X"fce1",
                                                        X"1066", X"f4e2", X"016c", X"f66d", X"fcb6", X"d729", X"fab3", X"edcb", X"026e", X"0544", X"0eb2", X"ef22", X"f298", X"0556",
                                                        X"f9c1", X"0011", X"0932", X"f341", X"0e17", X"0b70", X"186b", X"d9a5", X"049b", X"ffe3", X"0c14", X"0c88", X"0e20", X"f98a",
                                                        X"2ae8", X"1aa1", X"fe4d", X"04ea", X"172a", X"fcfe", X"0af4", X"f75d", X"0299", X"f37d", X"fe80", X"f08c", X"0b5b", X"fc0e",
                                                        X"e69c", X"0c7c", X"f78c", X"f4b0", X"1574", X"0f55", X"242f", X"0739", X"009a", X"e86d", X"e177", X"e1e5", X"0719", X"e914",
                                                        X"f437", X"d827", X"0bb4", X"0147", X"341a", X"0640", X"08e1", X"ea13", X"200e", X"052c", X"010b", X"ecc5", X"30ba", X"f067",
                                                        X"e7d1", X"df4d", X"01d6", X"f8b9", X"e612", X"17d0", X"1130", X"0460", X"1513", X"fe45", X"0b53", X"0ab8", X"ed76", X"fbca",
                                                        X"ef70", X"e606", X"e51e", X"f611", X"0085", X"ec6c", X"0462", X"f3a9", X"f6eb", X"eefe", X"06cc", X"e8a5", X"0a54", X"0bce",
                                                        X"f311", X"f7d4", X"e5ae", X"eb5e", X"fe15", X"fa8e", X"0097", X"08d9", X"17a3", X"ff3b", X"fcfa", X"09e5", X"0600", X"fd91",
                                                        X"07d0", X"ef70", X"0689", X"170f", X"03f8", X"fee9", X"0102", X"e94b", X"eff8", X"fb18", X"ffa6", X"f69d", X"e6ec", X"dc51",
                                                        X"ef98", X"fb1b", X"0b62", X"f972", X"071e", X"f493", X"1b98", X"235a", X"0bcc", X"fa89", X"0918", X"1932", X"e41f", X"ef8e",
                                                        X"1434", X"eb10", X"fac2", X"1334", X"0b1e", X"eff7", X"f071", X"2c94", X"1e52", X"fbd8", X"0c35", X"0e28", X"0a9b", X"fcf8",
                                                        X"0d12", X"0828", X"016b", X"1614", X"0880", X"f9ed", X"fcbd", X"fcf9", X"fe02", X"292a", X"0923", X"01a7", X"ff7b", X"1c79",
                                                        X"0f4f", X"dd33", X"d878", X"18c5", X"ed1e", X"11bd", X"f86e", X"f34d", X"fa79", X"fb8a", X"150f", X"15c5", X"1ee7", X"0353",
                                                        X"f58c", X"141c", X"fe9d", X"fa0e", X"e2ce", X"eea9", X"fe00", X"13c9", X"2226", X"0641", X"086d", X"098f", X"11e1", X"15e1",
                                                        X"f31e", X"2d3b", X"fc72", X"03a5", X"ff08", X"0804", X"116f", X"f5be", X"14a8", X"1460", X"fddc", X"0ce9", X"f80d", X"fd0e",
                                                        X"0dec", X"0e11", X"fb72", X"fe54", X"f99b", X"2229", X"1800", X"ef75", X"ea00", X"054f", X"0432", X"fba7", X"0155", X"fde8",
                                                        X"0e3e", X"06a9", X"f3e9", X"0530", X"d1b8", X"0a20", X"1748", X"0835", X"007f", X"efe5", X"208f", X"ee78", X"0296", X"f793",
                                                        X"eba1", X"2080", X"05d6", X"fa3f", X"fd01", X"18ab", X"04f1", X"0daf", X"f5f8", X"fb24", X"02c6", X"fd3a", X"0e54", X"0ff6",
                                                        X"0687", X"f884", X"fad7", X"04c2", X"f890", X"0079", X"f207", X"fbd0", X"e2fe", X"f2a3", X"f779", X"fd2e", X"015e", X"0cd9",
                                                        X"10da", X"010c", X"f702", X"fa6d", X"0311", X"0e1b", X"eeeb", X"0768", X"0a63", X"0a4a", X"0f1b", X"1702", X"ef81", X"e653",
                                                        X"02bf", X"facf", X"26f5", X"e19b", X"f9f7", X"0651", X"f0cf", X"f496", X"076d", X"00be", X"0910", X"f3ae", X"0b60", X"e2de",
                                                        X"044a", X"dbfd", X"f96e", X"eff9", X"dbce", X"fba4", X"10a9", X"00c0", X"0acc", X"ef6a", X"0e9b", X"f615", X"0d74", X"f791",
                                                        X"11af", X"d51c", X"e962", X"0865", X"0e09", X"dd23", X"f4ef", X"1444", X"0316", X"0fe1", X"1230", X"f37d", X"035f", X"fbee",
                                                        X"fe94", X"d32b", X"19b2", X"f4a2", X"fe25", X"12ab", X"f4fa", X"f0d7", X"f962", X"14bc", X"2203", X"fd4a", X"02ef", X"06f4",
                                                        X"1265", X"0d10", X"f9b2", X"e575", X"21be", X"dd80", X"051a", X"e8c8", X"0968", X"056d", X"eb19", X"006c", X"ebc3", X"e48d",
                                                        X"0ffe", X"0cd8", X"fc2f", X"f075");
  SIGNAL data_int                         : std_logic_vector(DataWidth - 1 DOWNTO 0) := X"f075";
  SIGNAL addr_unsigned                    : unsigned(AddrWidth - 1 DOWNTO 0);  -- generic width

BEGIN
  addr_unsigned <= unsigned(addr);

  SinglePortRAM_generic_process: PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF enb = '1' THEN
        IF we = '1' THEN
          ram(to_integer(addr_unsigned)) <= din;
          data_int <= din;
        ELSE
          data_int <= ram(to_integer(addr_unsigned));
        END IF;
      END IF;
    END IF;
  END PROCESS SinglePortRAM_generic_process;

  dout <= data_int;

END rtl;

