-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/amc_model_w16a16/amc_cnn_16w16a_src_SinglePortRAM_generic_block367.vhd
-- Created: 2023-08-04 11:27:17
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: amc_cnn_16w16a_src_SinglePortRAM_generic_block367
-- Source Path: amc_model_w16a16/DUT HDL/Dense Layer 1/Dense Layer 1/Weight Storage18/SinglePortRAM_generic
-- Hierarchy Level: 4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY amc_cnn_16w16a_src_SinglePortRAM_generic_block367 IS
  GENERIC( AddrWidth                      : integer := 1;
           DataWidth                      : integer := 1
           );
  PORT( clk                               :   IN    std_logic;
        enb                               :   IN    std_logic;
        din                               :   IN    std_logic_vector(DataWidth - 1 DOWNTO 0);  -- generic width
        addr                              :   IN    std_logic_vector(AddrWidth - 1 DOWNTO 0);  -- generic width
        we                                :   IN    std_logic;  -- ufix1
        dout                              :   OUT   std_logic_vector(DataWidth - 1 DOWNTO 0)  -- generic width
        );
END amc_cnn_16w16a_src_SinglePortRAM_generic_block367;


ARCHITECTURE rtl OF amc_cnn_16w16a_src_SinglePortRAM_generic_block367 IS

  -- Local Type Definitions
  TYPE ram_type IS ARRAY (2**AddrWidth - 1 DOWNTO 0) of std_logic_vector(DataWidth - 1 DOWNTO 0);

  -- Signals
  SIGNAL ram                              : ram_type := (X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"053f", X"0f3d", X"1589", X"fd16", X"20bd", X"0be2",
                                                        X"e5f3", X"f777", X"f302", X"0790", X"f81d", X"feeb", X"fe99", X"ff12", X"0272", X"0f8e", X"03c0", X"f55a", X"fffd", X"f9c8",
                                                        X"f99e", X"02b7", X"0778", X"024c", X"fbcc", X"dd09", X"1fc0", X"fa28", X"0266", X"fc4f", X"ffd6", X"feff", X"0caf", X"e738",
                                                        X"ff1e", X"fcac", X"023c", X"f797", X"1f93", X"034f", X"f9e6", X"db33", X"154f", X"0877", X"0fc4", X"0370", X"071f", X"fd70",
                                                        X"1470", X"f56f", X"fe29", X"fbf6", X"0fb1", X"09ae", X"11a1", X"f64e", X"e6f6", X"0a48", X"0e1f", X"0f81", X"1237", X"e9c9",
                                                        X"117a", X"f63a", X"08fb", X"fe5c", X"1b43", X"fd08", X"07b0", X"00d9", X"0465", X"facc", X"015b", X"09ee", X"1068", X"0efb",
                                                        X"0ac1", X"f12a", X"0b74", X"f5c0", X"0f93", X"0d0b", X"f793", X"ff00", X"f83c", X"0035", X"f206", X"fbcf", X"022e", X"f7ad",
                                                        X"f893", X"f534", X"0bd7", X"fd52", X"051e", X"0277", X"02e8", X"0963", X"0210", X"f3f8", X"fed5", X"f835", X"edfb", X"0dcd",
                                                        X"f9f8", X"04ed", X"e58b", X"f4b8", X"0803", X"faf7", X"0612", X"08e2", X"fc40", X"0519", X"eae3", X"cd4c", X"f888", X"fee7",
                                                        X"f64d", X"0b6a", X"0922", X"fa06", X"ef33", X"f9d6", X"fdcf", X"e675", X"f706", X"0769", X"0840", X"0f99", X"f220", X"e45c",
                                                        X"05a4", X"0264", X"f3b5", X"063b", X"e86d", X"09a9", X"11b4", X"04f6", X"face", X"f20b", X"0b5e", X"f3fe", X"147b", X"f4d6",
                                                        X"f599", X"f672", X"0943", X"f88a", X"09e5", X"061e", X"eada", X"ed7f", X"10f8", X"fae8", X"fac0", X"e3d8", X"16df", X"f6c7",
                                                        X"10ab", X"eca5", X"dba6", X"f3da", X"f7f4", X"f317", X"0696", X"01a7", X"f97d", X"fdc8", X"257e", X"f70f", X"28f1", X"ed05",
                                                        X"0785", X"0350", X"00f6", X"041b", X"fe63", X"ea3f", X"0cdb", X"ee6a", X"0cfb", X"0746", X"fb96", X"053c", X"1435", X"02d4",
                                                        X"fc37", X"fa97", X"fce5", X"ea44", X"ffc5", X"11cd", X"f0ef", X"fb7d", X"14fe", X"05b2", X"0247", X"0da7", X"fbb9", X"fe03",
                                                        X"1582", X"06aa", X"fe7f", X"fb47", X"023c", X"02bf", X"048c", X"f758", X"eb08", X"0c23", X"091c", X"150c", X"f1c0", X"01a4",
                                                        X"0df5", X"fa98", X"0ec4", X"0730", X"147c", X"0b01", X"095a", X"f22c", X"054d", X"f5e2", X"fc76", X"f3eb", X"0105", X"fba0",
                                                        X"e48a", X"098f", X"0400", X"1013", X"0677", X"0028", X"fdbd", X"10eb", X"fd64", X"f007", X"0d2b", X"f768", X"fce3", X"f197",
                                                        X"f996", X"015a", X"e8ba", X"1c49", X"0a37", X"1e8b", X"e5d5", X"093a", X"0990", X"e50d", X"fe2a", X"f9c9", X"0f73", X"04d4",
                                                        X"f158", X"ef26", X"f582", X"06f0", X"e8f7", X"15aa", X"fbaf", X"0755", X"de1f", X"f5cc", X"1578", X"076a", X"1133", X"1669",
                                                        X"ed07", X"f360", X"e9f5", X"f97d", X"fe76", X"02ed", X"f865", X"07b0", X"0099", X"1dda", X"1323", X"fc4e", X"ff9c", X"fae2",
                                                        X"1291", X"fb22", X"0644", X"f964", X"e5dd", X"ee77", X"088f", X"fde4", X"0a01", X"0065", X"fc93", X"063b", X"10d6", X"0938",
                                                        X"0774", X"0c3b", X"07e1", X"fe35", X"1569", X"f2e8", X"0a71", X"fba6", X"f085", X"0869", X"1248", X"f4c1", X"09c9", X"002c",
                                                        X"20cd", X"f6a0", X"10b8", X"e446", X"ff8a", X"e63d", X"0004", X"f12e", X"1e2d", X"f7b2", X"013c", X"03c4", X"08d0", X"fd71",
                                                        X"ff24", X"f835", X"1911", X"f172", X"fdc0", X"fc39", X"0e49", X"e433", X"064e", X"ff95", X"1a4d", X"fa30", X"05ba", X"fe4c",
                                                        X"0452", X"05b7", X"0a1c", X"062e", X"fcdc", X"fc4d", X"0a0f", X"00e3", X"0af9", X"01ec", X"fa15", X"f7e3", X"f9d3", X"0459",
                                                        X"f581", X"0e85", X"fca8", X"060c", X"0670", X"f875", X"03cf", X"0181", X"0633", X"f8c6", X"04c1", X"e7b0", X"0858", X"0f02",
                                                        X"f725", X"023a", X"f7de", X"0360", X"f984", X"16c5", X"00aa", X"0a8a", X"fe96", X"fb78", X"ffb1", X"f8dc", X"08f7", X"ee76",
                                                        X"1a8b", X"ee30", X"eee5", X"0093", X"09ae", X"076d", X"f0ac", X"078c", X"0541", X"0be6", X"ec12", X"fb93", X"e998", X"ee87",
                                                        X"06fa", X"0471", X"1588", X"fc90", X"ef0b", X"f941", X"fbe6", X"0803", X"ff72", X"fde1", X"f2f9", X"fcd4", X"012f", X"fd42",
                                                        X"084f", X"e637", X"0690", X"ef7d", X"0be9", X"fdb7", X"dcfc", X"fd26", X"f79a", X"0eb6", X"1148", X"00cb", X"029a", X"f15d",
                                                        X"16ca", X"f8c1", X"1f6b", X"f672", X"fb68", X"fda2", X"0e2c", X"1456", X"f353", X"f9a9", X"040c", X"0806", X"1671", X"0e1a",
                                                        X"ff0e", X"ed39", X"24a2", X"002a", X"fc7e", X"0677", X"0790", X"035e", X"fff4", X"fc60", X"03d6", X"fae8", X"e7e5", X"f637",
                                                        X"0647", X"0648", X"fb07", X"dbfa", X"29d0", X"00d2", X"1664", X"f95f", X"f87b", X"fb3e", X"ff26", X"f8f0", X"f947", X"ed7a",
                                                        X"e65c", X"102c", X"09ed", X"0a4d", X"f755", X"0c42", X"18dc", X"04dd", X"fdfe", X"fc3c", X"fa28", X"f863", X"09f9", X"ef16",
                                                        X"ee59", X"fb96", X"f680", X"05ca", X"eab9", X"016c", X"ed34", X"f13b", X"097a", X"fc8e", X"022d", X"06bd", X"f6b5", X"f683",
                                                        X"1a33", X"ff18", X"fcd2", X"f727", X"eb56", X"13ac", X"e958", X"11a3", X"f455", X"f285", X"046b", X"0093", X"0045", X"ee1e",
                                                        X"fe1a", X"0982", X"070b", X"0d45", X"eb21", X"f27d", X"f4ff", X"17e6", X"e2a9", X"0723", X"fa01", X"08b9", X"fe84", X"fab8",
                                                        X"028b", X"047b", X"0970", X"0071", X"0f8a", X"00d9", X"f42c", X"fbf3", X"eddd", X"186c", X"ff7f", X"0e91", X"f22c", X"138c",
                                                        X"01b0", X"fb5d", X"04fa", X"fdc1", X"0162", X"0c6d", X"16cb", X"f3e0", X"0209", X"047c", X"e09c", X"0898", X"105f", X"0f5a",
                                                        X"ea0c", X"edd1", X"1ba4", X"000b", X"fc18", X"ecf5", X"071f", X"0b0e", X"028b", X"f5df", X"fc67", X"feee", X"ea7b", X"fea6",
                                                        X"0f38", X"0792", X"ff47", X"f947", X"f9d8", X"fb39", X"1e55", X"16d2", X"14ac", X"ed4f", X"173e", X"eda0", X"e929", X"0242",
                                                        X"0ff1", X"0391", X"0b9e", X"0521", X"f8fb", X"dc14", X"1b2d", X"08a4", X"054f", X"f54b", X"12c3", X"e8fc", X"107f", X"f148",
                                                        X"e8be", X"f05c", X"eb21", X"0582", X"07ab", X"fd5d", X"f47c", X"f9e0", X"2065", X"feaf", X"10c7", X"fc75", X"f681", X"e8f2",
                                                        X"144d", X"081e", X"e5a8", X"0167", X"e7fb", X"f708", X"faab", X"057f", X"f27c", X"1851", X"1352", X"f6b4", X"0f6c", X"f038",
                                                        X"f77f", X"fdab", X"0a76", X"067b", X"f636", X"ff90", X"07e4", X"fdd1", X"eca6", X"11cc", X"0a7b", X"fa91", X"dfe5", X"ec30",
                                                        X"07fc", X"f83f", X"0572", X"035c", X"07aa", X"072f", X"0f2f", X"f9e8", X"f3f6", X"0495", X"ecf7", X"1722", X"fee3", X"fe90",
                                                        X"022f", X"03e2", X"f790", X"ea9a", X"e88c", X"fb3b", X"174b", X"f95b", X"fba6", X"fc7c", X"ef25", X"0967", X"0451", X"109e",
                                                        X"f844", X"11b7", X"f8dd", X"0b09", X"1045", X"e6e7", X"f6f4", X"0f78", X"05e1", X"fe56", X"04df", X"0819", X"03ce", X"1084",
                                                        X"1427", X"0923", X"f548", X"fda9", X"ffda", X"05ed", X"0eac", X"f28e", X"fce0", X"e5ef", X"1c97", X"ec7a", X"0818", X"075e",
                                                        X"f241", X"0881", X"259a", X"0a00", X"fc3e", X"ecb1", X"137a", X"fa70", X"25cc", X"fab2", X"0c48", X"edcb", X"1057", X"fc6a",
                                                        X"0fe7", X"ff23", X"0873", X"005a", X"18d3", X"fba1", X"0047", X"e840", X"0ce1", X"0126", X"2835", X"07b8", X"0a70", X"f383",
                                                        X"fcd7", X"fd31", X"0f6c", X"ff5d", X"f285", X"125d", X"166b", X"08d9", X"01d3", X"f987", X"2112", X"fa7b", X"0de7", X"0787",
                                                        X"fb7e", X"f949", X"09cd", X"fec0", X"15e9", X"08d3", X"e6c8", X"05bc", X"032a", X"09a2", X"fa4d", X"00a8", X"1a82", X"05fb",
                                                        X"0b28", X"fdd8", X"f802", X"f219", X"05c5", X"ff1c", X"fa92", X"fb37", X"e40e", X"085b", X"eb8e", X"0f23", X"f602", X"fd26",
                                                        X"fb0f", X"00b0", X"05e8", X"0836", X"f493", X"00f0", X"fe9f", X"f580", X"eb67", X"f2c0", X"f2a9", X"057b", X"e87d", X"1224",
                                                        X"f86e", X"0e50", X"da3e", X"f252", X"e6c5", X"fb66", X"f810", X"f85f", X"0382", X"083f", X"069b", X"f6f6", X"f394", X"0828",
                                                        X"f289", X"0b46", X"f1e2", X"0690", X"f9e6", X"fc91", X"f08e", X"f422", X"fca8", X"f836", X"1416", X"080b", X"0207", X"f0ef",
                                                        X"f6e2", X"0baf", X"0bc0", X"05b5", X"f883", X"031d", X"feb6", X"f412", X"f7aa", X"f2ef", X"07a5", X"fc1c", X"0d3a", X"f1ee",
                                                        X"07a2", X"f30d", X"f8b7", X"0fee", X"10a7", X"fb7c", X"ecee", X"f1ea", X"20f9", X"fed1", X"fe97", X"0823", X"052f", X"fd58",
                                                        X"17d4", X"f226", X"efee", X"f987", X"0479", X"034c", X"11f6", X"fc2f", X"f25f", X"f067", X"09cf", X"f9e1", X"0feb", X"f65a",
                                                        X"0626", X"f846", X"1665", X"fc22", X"ed4b", X"fdcc", X"f43d", X"fc94", X"1de9", X"02bd", X"f9fc", X"e395", X"1004", X"facb",
                                                        X"1b49", X"1814", X"19a9", X"eed3", X"16f4", X"f840", X"160a", X"ff0a", X"0fa8", X"0f68", X"0418", X"ff27", X"019e", X"0181",
                                                        X"2128", X"0b02", X"0881", X"0639", X"0af8", X"eb7d", X"fdfc", X"01dd", X"157d", X"fbad", X"e631", X"fe9e", X"0627", X"0cb3",
                                                        X"05bc", X"f41b", X"0ecc", X"03f9", X"f42c", X"0585", X"065f", X"f092", X"fcdd", X"09d8", X"feda", X"ff2d", X"e673", X"f06d",
                                                        X"ffc0", X"0886", X"0259", X"ff55", X"e099", X"f599", X"f491", X"0519", X"f60a", X"05b3", X"018a", X"187e", X"0d15", X"fb66",
                                                        X"ed65", X"f902", X"f21a", X"09c9", X"fa30", X"fbb2", X"e335", X"08bf", X"0650", X"ee26", X"023b", X"04c3", X"fdb5", X"f81f",
                                                        X"0b03", X"f0d1", X"fc4b", X"0c92", X"feae", X"0f9e", X"f2d9", X"fe3f", X"f1af", X"e771", X"033f", X"e429", X"fb60", X"f895",
                                                        X"1315", X"f77d", X"e020", X"fd15", X"063c", X"fa1d", X"0969", X"fc39", X"fd9d", X"e877", X"16f0", X"ff76", X"f264", X"1918",
                                                        X"07dd", X"f990", X"0eca", X"f7ea", X"136a", X"08d4", X"0789", X"0b86", X"1274", X"0149", X"0014", X"fc70", X"16cf", X"0387",
                                                        X"0829", X"e55a", X"fcd3", X"eb73", X"13bd", X"ecf8", X"00d8", X"fb5d", X"f304", X"14d4", X"1c12", X"1264", X"f857", X"064e",
                                                        X"1d19", X"f624", X"19bd", X"e85d", X"05b4", X"fdcf", X"0b21", X"fcdc", X"ea39", X"fee1", X"e8ef", X"0161", X"029f", X"ff14",
                                                        X"032b", X"ea37", X"1826", X"1058", X"fb62", X"0b53", X"f498", X"fe27", X"ff68", X"062b", X"f6ee", X"feda", X"f524", X"0a1e",
                                                        X"fef3", X"0481", X"094e", X"0b0a", X"0295", X"111a", X"0971", X"0c2f", X"01bc", X"faf7", X"09c9", X"fb67", X"0c0a", X"0201",
                                                        X"03b5", X"1184", X"f199", X"0ca3", X"ffcb", X"f3ee", X"f66a", X"1136", X"00f3", X"032d", X"113f", X"06be", X"0c2a", X"fdca",
                                                        X"1b48", X"fc4f", X"f26d", X"0558", X"ebfc", X"0e77", X"fb93", X"f62a", X"fc14", X"0435", X"f204", X"dc70", X"f92b", X"0a1e",
                                                        X"13f1", X"fa40", X"0b4d", X"f792", X"058f", X"02fa", X"ef0a", X"0783", X"fa01", X"e986", X"0aa0", X"f383", X"fcde", X"fad8",
                                                        X"0739", X"fa19", X"1348", X"fbe9", X"f1f3", X"e815", X"fd88", X"fc3e", X"094e", X"ff01", X"fac2", X"0f14", X"1be5", X"f336",
                                                        X"00df", X"fc14", X"0eba", X"e7e5", X"1344", X"ffca", X"ea8e", X"eee2", X"0582", X"fd3d", X"1bbd", X"fa7b", X"f623", X"fbf3",
                                                        X"252d", X"f9a3", X"10f0", X"f300", X"0450", X"f4e1", X"0b47", X"f9e2", X"f3b2", X"f53b", X"f213", X"0290", X"0ddb", X"09f0",
                                                        X"021d", X"fe5c", X"0f05", X"0361", X"06dc", X"f066", X"fd1f", X"f45b", X"184b", X"ef47", X"fc50", X"f710", X"fce6", X"ff7c",
                                                        X"fc69", X"0a8c", X"fe8e", X"f85d", X"07cd", X"ee9d", X"1e52", X"f709", X"08cf", X"e4b2", X"089d", X"02dd", X"f302", X"f139",
                                                        X"f96b", X"f16d", X"e86c", X"110b", X"fd6e", X"e34b", X"ed20", X"052a", X"f6c8", X"01af", X"f720", X"ea34", X"075c", X"fc22",
                                                        X"0b6c", X"f8a5", X"f412", X"fc43", X"e9f7", X"08cc", X"f49d", X"0953", X"11e2", X"fe37", X"f98c", X"f08f", X"f2d0", X"ff84",
                                                        X"fea5", X"0798", X"03cf", X"f1dc", X"fe27", X"0993", X"fa4e", X"1046", X"f95d", X"0ad3", X"f570", X"f217", X"f763", X"faf7",
                                                        X"ed3e", X"f492", X"11e2", X"0ccd", X"fcfe", X"fc75", X"e4f7", X"fc6d", X"f0fa", X"08bf", X"030c", X"f8aa", X"0993", X"04e3",
                                                        X"f965", X"f168", X"f972", X"07d8", X"09ef", X"0277", X"00b6", X"f292", X"e3b8", X"f42d", X"02ba", X"f3f3", X"f5e1", X"ec86",
                                                        X"f589", X"0271", X"09be", X"f01d", X"03b2", X"fe53", X"0ab1", X"f0aa", X"0095", X"efda", X"faac", X"f891", X"12ee", X"000b",
                                                        X"f331", X"ed21", X"060d", X"045b", X"2208", X"ee05", X"054a", X"003f", X"074f", X"001a", X"f64e", X"fa34", X"0efe", X"0142",
                                                        X"10c6", X"0421", X"017a", X"e5f7", X"2a7a", X"0983", X"0a71", X"e3a1", X"12fa", X"ec2f", X"08b1", X"0013", X"edd2", X"ffcb",
                                                        X"f8da", X"0492", X"0c9d", X"fb28", X"f701", X"0a5f", X"1143", X"fe0a", X"182a", X"f282", X"0457", X"e808", X"017d", X"0a47",
                                                        X"f090", X"fc83", X"f5de", X"f8d7", X"fe40", X"10f6", X"f184", X"0141", X"fbee", X"efe0", X"f4d4", X"f122", X"f73b", X"fd0c",
                                                        X"fd33", X"febe", X"02aa", X"f6e8", X"fa8f", X"f7ac", X"e58b", X"1211", X"03bf", X"e9a6", X"f4a5", X"05e8", X"f6bc", X"0aac",
                                                        X"fcaf", X"0784", X"10a3", X"0391", X"fea2", X"fa0e", X"ff82", X"0327", X"df3b", X"008b", X"f6a1", X"f260", X"031e", X"ffef",
                                                        X"f7d6", X"ef81", X"f756", X"0713", X"11ed", X"0c30", X"075e", X"f944", X"fbc5", X"f85a", X"e828", X"0a4e", X"f418", X"1dbe",
                                                        X"133b", X"fa99", X"2743", X"e6a1", X"fae0", X"0f1d", X"001d", X"03d1", X"f761", X"ead6", X"e457", X"04fb", X"f774", X"fdb0",
                                                        X"f54e", X"fa8f", X"073a", X"0139", X"f352", X"f873", X"0afa", X"0a2c", X"00d0", X"ea8b", X"06a0", X"f04d", X"054a", X"f548",
                                                        X"0fdf", X"fe0a", X"f12e", X"09f7", X"1371", X"0131", X"f30e", X"ef40", X"03d6", X"f1db", X"088c", X"e6c5", X"fa47", X"fe89",
                                                        X"e723", X"0811", X"20a5", X"f7dc", X"011b", X"f2e5", X"0d8a", X"0447", X"0bdd", X"ea62", X"0c26", X"0c32", X"0df5", X"f0b9",
                                                        X"ed5c", X"fbcf", X"fdb0", X"febc", X"0e4d", X"0a96", X"0b40", X"0050", X"1ada", X"0477", X"0f9f", X"0332", X"fe95", X"e8a7",
                                                        X"fefc", X"0826", X"fcd0", X"0a02", X"0a77", X"12be", X"fd08", X"04fb", X"0b43", X"ef34", X"219f", X"0e52", X"042d", X"0d26",
                                                        X"f71c", X"ed6d", X"13fc", X"0496", X"ecfb", X"0265", X"0afc", X"ffd4", X"eedf", X"017b", X"ffb8", X"ff57", X"0245", X"fd66",
                                                        X"ff8b", X"162c", X"fd62", X"09ed", X"f74e", X"0e13", X"10e2", X"03ab", X"05a8", X"0339", X"e097", X"fdfe", X"fe36", X"f6cb",
                                                        X"f7b9", X"f908", X"1bc0", X"09e5", X"fadf", X"062a", X"0194", X"136f", X"0fec", X"fe54", X"ebe6", X"eff3", X"f703", X"10ec",
                                                        X"f8d3", X"f37b", X"ed69", X"f6dc", X"f841", X"ecc4", X"fdf8", X"f72b", X"0550", X"0cab", X"06d5", X"0034", X"fa46", X"f5a0",
                                                        X"058e", X"0e6e", X"01a6", X"fd2c", X"0186", X"f84d", X"02fe", X"f911", X"05ee", X"09fb", X"0017", X"034b", X"fd2a", X"0212",
                                                        X"f4bc", X"f7b4", X"0d39", X"02f8", X"00c6", X"077f", X"04e9", X"0820", X"1b64", X"f53c", X"07fc", X"fb5d", X"0555", X"fc86",
                                                        X"ed84", X"0322", X"0f87", X"fd9f", X"1158", X"001c", X"fe51", X"ed4c", X"22c0", X"ffcd", X"fe38", X"0695", X"f444", X"fd2e",
                                                        X"0301", X"fed3", X"f1b7", X"facd", X"f293", X"0673", X"0a01", X"0878", X"efe5", X"f559", X"0f34", X"ff47", X"0543", X"0833",
                                                        X"0bb9", X"f182", X"00f1", X"f3ae", X"0717", X"fa81", X"f9af", X"ff65", X"07ac", X"f5a1", X"f55c", X"fc1f", X"1357", X"0e75",
                                                        X"ff78", X"02b1", X"10da", X"f058", X"fd70", X"02a7", X"18b2", X"f8fe", X"fda4", X"09bc", X"0336", X"0bb9", X"f93e", X"ff88",
                                                        X"f56d", X"ec7f", X"0ba9", X"f515", X"0474", X"fa65", X"029c", X"004a", X"18c3", X"01ce", X"fa6b", X"0e09", X"f32b", X"1505",
                                                        X"090d", X"00fa", X"04b1", X"e872", X"fbd3", X"fecc", X"02b3", X"ead0", X"04e1", X"009e", X"ede7", X"f2d1", X"ec27", X"022e",
                                                        X"f9f9", X"0ddb", X"0f74", X"eb32", X"1517", X"f571", X"f843", X"0446", X"facc", X"faf7", X"0988", X"0480", X"f0af", X"fd5b",
                                                        X"02ea", X"0eca", X"f253", X"08d0", X"fd7b", X"f31a", X"e802", X"fe6f", X"0952", X"0769", X"fecc", X"0858", X"0e71", X"0250",
                                                        X"01b2", X"fe2c", X"f44a", X"f210", X"04a8", X"07b9", X"f713", X"fb0d", X"0fb7", X"fe6b", X"f7bb", X"ef20", X"18d3", X"f20b",
                                                        X"09c5", X"fe7e", X"11ea", X"f8b8", X"03fa", X"fba9", X"0f23", X"fafb", X"faf6", X"01f5", X"1d44", X"f757", X"09a2", X"f5ea",
                                                        X"12e6", X"042e", X"0920", X"01f0", X"f896", X"f58d", X"0b8c", X"058b", X"10bf", X"fedf", X"f1f3", X"1397", X"056c", X"f50f",
                                                        X"17e6", X"f9e0", X"fa61", X"f549", X"f605", X"08cb", X"0dd9", X"f21b", X"e445", X"fc4a", X"ffe1", X"00cc", X"faea", X"0a62",
                                                        X"0691", X"059c", X"0572", X"0740", X"f5b9", X"e068", X"140a", X"0c0a", X"fa8a", X"f323", X"faf1", X"f838", X"fd1d", X"0e73",
                                                        X"fff9", X"e991", X"ec69", X"e7da", X"f4e9", X"ffb1", X"f37a", X"0696", X"f5c6", X"f506", X"fc43", X"0007", X"03c6", X"ea5a",
                                                        X"f386", X"0cc7", X"f37c", X"0509", X"e7be", X"04f1", X"05b9", X"f6fb", X"f063", X"08b5", X"0644", X"f822", X"0038", X"0374",
                                                        X"fbe3", X"f30c", X"e45d", X"0deb", X"f61d", X"0cca", X"ce03", X"fd1b", X"f656", X"fca2", X"032e", X"1058", X"0ec9", X"021d",
                                                        X"f353", X"0050", X"efea", X"0420", X"ef73", X"0573", X"fbd2", X"fbba", X"00f4", X"f601", X"0522", X"fadb", X"fc95", X"182a",
                                                        X"07d5", X"fd8c", X"078d", X"0708", X"fc78", X"0f6b", X"0ab3", X"0a4a", X"0460", X"fe72", X"0857", X"ff84", X"ebfc", X"00c8",
                                                        X"05aa", X"14c6", X"001a", X"f430", X"0e6a", X"01f0", X"e9e0", X"f3f6", X"0bde", X"fa7a", X"065a", X"0e51", X"072b", X"11b9",
                                                        X"ffe8", X"e9d0", X"f4f6", X"f4fc", X"022c", X"eb44", X"0152", X"0091", X"f3b2", X"f53b", X"0c6c", X"03d8", X"054a", X"d4de",
                                                        X"1269", X"fc6d", X"0d99", X"f76d", X"08e8", X"fcf2", X"08ee", X"fabb", X"02be", X"fe59", X"09d2", X"0bf9", X"11f6", X"0a9f",
                                                        X"1277", X"fcc3", X"228e", X"fe7f", X"2886", X"ea91", X"0645", X"f31e", X"0685", X"0415", X"09bb", X"f948", X"0920", X"0736",
                                                        X"0325", X"11e0", X"0abc", X"038b", X"04fd", X"144e", X"f09d", X"0fd4", X"fa7f", X"f2c5", X"03f1", X"0b14", X"e78d", X"046f",
                                                        X"f1a2", X"1458", X"e5f4", X"01a8", X"ef22", X"fe42", X"f856", X"0a18", X"f676", X"fc0a", X"03b2", X"0ed2", X"0a12", X"05b1",
                                                        X"f2a5", X"f60c", X"e6ad", X"f92f", X"eccc", X"03aa", X"faf8", X"f4a8", X"ff03", X"05b9", X"0747", X"f356", X"fd91", X"fa96",
                                                        X"0744", X"f4cd", X"ea06", X"0406", X"f3e0", X"0ed6", X"f40d", X"06ea", X"07aa", X"ebfd", X"09c5", X"0cc2", X"f978", X"ea63",
                                                        X"0978", X"f85a", X"0b1f", X"fde7", X"e452", X"f817", X"f210", X"0513", X"fd49", X"0919", X"fb13", X"1635", X"f758", X"f86d",
                                                        X"024b", X"e489", X"10fa", X"01f1", X"fd3f", X"eef1", X"f84f", X"00b5", X"f4d1", X"0748", X"057c", X"0013", X"02c4", X"104d",
                                                        X"1a7e", X"f42e", X"0f96", X"0f74", X"00de", X"fa71", X"0d0b", X"e970", X"f106", X"ef1c", X"07f7", X"f634", X"163f", X"fee8",
                                                        X"0143", X"e02d", X"2f48", X"f23f", X"f477", X"ffd4", X"09ee", X"0068", X"0a2d", X"fc91", X"f7fa", X"f876", X"0773", X"015b",
                                                        X"1107", X"001a", X"0223", X"d996", X"0d5a", X"f2d9", X"1951", X"e3a0", X"0661", X"f4fa", X"047f", X"00fd", X"0a07", X"fbfc",
                                                        X"1a32", X"02ff", X"038d", X"fdbd", X"0478", X"01c6", X"0e9e", X"f806", X"02cd", X"08c5", X"f8b9", X"f36d", X"0af0", X"ff5d",
                                                        X"04a7", X"fda2", X"edbf", X"ff15", X"fc7d", X"01eb", X"f99b", X"19c9", X"f871", X"fd2f", X"e250", X"ec09", X"fa01", X"0214",
                                                        X"05fd", X"045f", X"057a", X"f076", X"fa8a", X"fd65", X"ed40", X"1009", X"f8bf", X"0269", X"fe6f", X"ffda", X"ef34", X"ea42",
                                                        X"f0ba", X"fcf3", X"ff81", X"0f7b", X"eafe", X"f952", X"ff1c", X"08a0", X"f883", X"1f80", X"11d8", X"f7c6", X"f9c0", X"e54b",
                                                        X"0933", X"f107", X"f94d", X"087f");
  SIGNAL data_int                         : std_logic_vector(DataWidth - 1 DOWNTO 0) := X"087f";
  SIGNAL addr_unsigned                    : unsigned(AddrWidth - 1 DOWNTO 0);  -- generic width

BEGIN
  addr_unsigned <= unsigned(addr);

  SinglePortRAM_generic_process: PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF enb = '1' THEN
        IF we = '1' THEN
          ram(to_integer(addr_unsigned)) <= din;
          data_int <= din;
        ELSE
          data_int <= ram(to_integer(addr_unsigned));
        END IF;
      END IF;
    END IF;
  END PROCESS SinglePortRAM_generic_process;

  dout <= data_int;

END rtl;

