-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/amc_model_w16a16/amc_cnn_16w16a_src_SinglePortRAM_generic_block412.vhd
-- Created: 2023-08-04 11:27:24
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: amc_cnn_16w16a_src_SinglePortRAM_generic_block412
-- Source Path: amc_model_w16a16/DUT HDL/Dense Layer 1/Dense Layer 1/Weight Storage59/SinglePortRAM_generic
-- Hierarchy Level: 4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY amc_cnn_16w16a_src_SinglePortRAM_generic_block412 IS
  GENERIC( AddrWidth                      : integer := 1;
           DataWidth                      : integer := 1
           );
  PORT( clk                               :   IN    std_logic;
        enb                               :   IN    std_logic;
        din                               :   IN    std_logic_vector(DataWidth - 1 DOWNTO 0);  -- generic width
        addr                              :   IN    std_logic_vector(AddrWidth - 1 DOWNTO 0);  -- generic width
        we                                :   IN    std_logic;  -- ufix1
        dout                              :   OUT   std_logic_vector(DataWidth - 1 DOWNTO 0)  -- generic width
        );
END amc_cnn_16w16a_src_SinglePortRAM_generic_block412;


ARCHITECTURE rtl OF amc_cnn_16w16a_src_SinglePortRAM_generic_block412 IS

  -- Local Type Definitions
  TYPE ram_type IS ARRAY (2**AddrWidth - 1 DOWNTO 0) of std_logic_vector(DataWidth - 1 DOWNTO 0);

  -- Signals
  SIGNAL ram                              : ram_type := (X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"16ea", X"2613", X"b7cd", X"10fe", X"eecb", X"43c3",
                                                        X"1d40", X"fb3c", X"15cb", X"05b4", X"e51e", X"fa0b", X"1bbe", X"0c3b", X"1952", X"0b06", X"0650", X"f7c4", X"ec13", X"0baf",
                                                        X"ec57", X"1e9b", X"0687", X"0af8", X"0edb", X"f8a5", X"f002", X"f841", X"1a48", X"ff70", X"038b", X"0a09", X"0cac", X"fee3",
                                                        X"dc67", X"fc39", X"dbc2", X"0f89", X"fdf6", X"fd01", X"eeb2", X"ffd6", X"0acb", X"eb39", X"0fc8", X"0e06", X"f071", X"105e",
                                                        X"fb70", X"049b", X"1c02", X"09ef", X"fd68", X"07b8", X"13b2", X"1077", X"0d10", X"fd02", X"fbf9", X"fcba", X"073c", X"f01f",
                                                        X"068a", X"0d0b", X"f790", X"fbae", X"d65e", X"f49a", X"fcb2", X"f722", X"0d74", X"f5e5", X"20fa", X"ee55", X"deeb", X"fdea",
                                                        X"0234", X"fdab", X"017d", X"0c1a", X"09ef", X"f774", X"ffb2", X"e0e0", X"078a", X"f1c4", X"04a0", X"ef87", X"dc27", X"fc34",
                                                        X"0ed8", X"f92f", X"081d", X"01fd", X"eb09", X"110d", X"03c7", X"e5ee", X"dc67", X"e370", X"f1dd", X"ef07", X"0393", X"00c8",
                                                        X"f201", X"171c", X"ee43", X"014d", X"0294", X"f2e0", X"0d04", X"1447", X"e481", X"eec0", X"2841", X"e768", X"057a", X"e885",
                                                        X"d663", X"f3db", X"1005", X"f960", X"223e", X"09b1", X"09e0", X"0224", X"f04a", X"08f7", X"ee5b", X"e97f", X"2733", X"f7bf",
                                                        X"ffb7", X"e299", X"fa92", X"09b3", X"04c5", X"09f4", X"19dd", X"1616", X"fd02", X"1022", X"ef36", X"1842", X"00ad", X"f236",
                                                        X"d225", X"e1f2", X"fdd4", X"dc8f", X"063e", X"fcf8", X"076b", X"fcee", X"07be", X"2a34", X"0fec", X"0127", X"01e3", X"0536",
                                                        X"eb9d", X"f8cc", X"df21", X"fc57", X"05e8", X"f9fc", X"fb16", X"eca3", X"1a56", X"f96b", X"021c", X"fabf", X"0d09", X"f3f3",
                                                        X"03af", X"0927", X"f956", X"14e5", X"13af", X"17b3", X"0e66", X"ff5e", X"037f", X"0e87", X"0751", X"0722", X"fdda", X"028c",
                                                        X"ef69", X"ffa3", X"fc2d", X"ff48", X"fc5c", X"fbe7", X"f3a4", X"04d0", X"0853", X"00c0", X"0383", X"0526", X"fcd0", X"0d8a",
                                                        X"0c87", X"fc46", X"0f47", X"fef6", X"ffd6", X"fd67", X"f56c", X"1031", X"02bd", X"1953", X"0f45", X"10fe", X"1344", X"f24d",
                                                        X"0aae", X"fa31", X"e33d", X"048c", X"09cb", X"f640", X"f865", X"03a0", X"ee4a", X"01fb", X"0129", X"fcdf", X"03fb", X"16c7",
                                                        X"0b42", X"19e7", X"0695", X"fa37", X"e52c", X"ef09", X"fbb2", X"1601", X"fccb", X"f07e", X"f62a", X"0d18", X"f50c", X"235d",
                                                        X"e97d", X"0fd2", X"12aa", X"042a", X"efd2", X"f7e7", X"fbcf", X"f187", X"f0c2", X"1d6c", X"09a7", X"09fb", X"092d", X"08fc",
                                                        X"ef62", X"271c", X"e6ee", X"fcaa", X"fdf8", X"f189", X"27b7", X"0213", X"f0f0", X"f939", X"ff14", X"f507", X"0ec3", X"0e33",
                                                        X"ff77", X"129d", X"d124", X"fed0", X"0086", X"1f07", X"08ea", X"fc7b", X"dbb3", X"083c", X"ed40", X"028d", X"1c13", X"0017",
                                                        X"0129", X"0099", X"ff7b", X"2568", X"d97a", X"f938", X"eb02", X"13e3", X"f9cb", X"01ae", X"eee5", X"f8e6", X"e332", X"1c97",
                                                        X"1044", X"fec6", X"fa3d", X"11bb", X"f752", X"09af", X"e672", X"00a8", X"0ac8", X"1f84", X"18ec", X"f63b", X"15aa", X"0695",
                                                        X"fb4b", X"f328", X"f030", X"2077", X"071a", X"1626", X"0776", X"f85d", X"f427", X"e6ae", X"0b33", X"e9c8", X"013b", X"fef2",
                                                        X"1592", X"0a3d", X"ef56", X"f274", X"0e5b", X"00b3", X"0039", X"057c", X"f9fd", X"03bc", X"fabb", X"fa12", X"f84d", X"ebaf",
                                                        X"feec", X"07b5", X"fc0b", X"f842", X"2e1d", X"0ba0", X"f277", X"f9db", X"0790", X"1a45", X"f6b1", X"03db", X"2176", X"eba4",
                                                        X"04a8", X"0ba6", X"e7bd", X"16ee", X"e28c", X"f65a", X"1052", X"f1a4", X"0e43", X"fac2", X"05ed", X"0030", X"e989", X"0719",
                                                        X"f67e", X"f6e1", X"f6fd", X"fb3c", X"02f8", X"0892", X"1d10", X"060b", X"fd16", X"1720", X"0567", X"0a7a", X"ff26", X"026a",
                                                        X"fe88", X"f0f9", X"272b", X"e6e1", X"ff00", X"f725", X"ecc0", X"fc34", X"1b1a", X"07a3", X"eeb0", X"1452", X"063c", X"f6e5",
                                                        X"f491", X"039f", X"0015", X"14a8", X"074f", X"e717", X"1294", X"f986", X"1323", X"1ad5", X"042b", X"0a41", X"1cd8", X"04b2",
                                                        X"0978", X"03e1", X"0675", X"fae9", X"f5ea", X"fd0c", X"e048", X"ff8a", X"f6f3", X"0b85", X"0718", X"f0e9", X"f7a9", X"0501",
                                                        X"1f50", X"f512", X"10a0", X"f84c", X"fdd3", X"05b1", X"f3bd", X"0040", X"f5ed", X"0d1e", X"fc81", X"e468", X"f0cd", X"feec",
                                                        X"e8b4", X"fbf6", X"095c", X"069d", X"f7a7", X"0560", X"f048", X"fbdd", X"fb41", X"1600", X"23ac", X"1609", X"fdd8", X"f052",
                                                        X"0284", X"18e4", X"0d63", X"16cb", X"fdea", X"fe5e", X"fe9e", X"0e37", X"072a", X"0254", X"fdcc", X"157b", X"1750", X"1275",
                                                        X"f325", X"144e", X"04cb", X"1d77", X"172a", X"fd78", X"0402", X"0c02", X"1b87", X"efec", X"0864", X"fd0e", X"ffaf", X"fe35",
                                                        X"f786", X"01b6", X"0dd6", X"0138", X"fcfe", X"f461", X"e891", X"00da", X"f8f6", X"186d", X"0791", X"f1cb", X"14ec", X"fbeb",
                                                        X"fda2", X"1db3", X"ee2f", X"2163", X"0b9d", X"0a4f", X"25b2", X"f545", X"d5bc", X"00ea", X"e732", X"fe1e", X"08f1", X"0e21",
                                                        X"fe6b", X"0673", X"0a8f", X"0d1c", X"1189", X"0a0f", X"fb30", X"285f", X"ffb2", X"01a9", X"dec2", X"fd66", X"d2dd", X"02a9",
                                                        X"06ba", X"0367", X"f810", X"0127", X"2a63", X"1400", X"03fc", X"eeef", X"0133", X"f8e6", X"1669", X"005f", X"e9b8", X"f7c6",
                                                        X"e68b", X"07ce", X"1469", X"0ad6", X"09f3", X"f304", X"171f", X"fde9", X"1c18", X"254e", X"f579", X"f0e5", X"fd67", X"f552",
                                                        X"1b0a", X"f784", X"09a2", X"e62e", X"ee44", X"fac7", X"ff08", X"0c16", X"0765", X"067f", X"fb0c", X"0961", X"fdd2", X"1cc3",
                                                        X"09cb", X"00fe", X"fef1", X"f1ef", X"f615", X"e6c5", X"fbef", X"1748", X"045f", X"0129", X"f71a", X"00e3", X"1bbd", X"0d8f",
                                                        X"f55e", X"f76c", X"ef0e", X"12a0", X"0fcc", X"028b", X"0af6", X"f011", X"f62a", X"fc8d", X"eaca", X"0bb2", X"0081", X"fdd6",
                                                        X"f092", X"f8f6", X"f438", X"f50d", X"e4c8", X"fa7d", X"f3bc", X"09fa", X"eb0d", X"f8f9", X"1196", X"f1ab", X"e849", X"10f8",
                                                        X"fac5", X"0015", X"e49a", X"cfe8", X"01ac", X"e74e", X"1457", X"fae2", X"2763", X"00bd", X"057d", X"1c18", X"f3cd", X"0734",
                                                        X"1401", X"072c", X"ee23", X"f087", X"da6c", X"f0d0", X"07c5", X"fdb9", X"ef8a", X"f4c1", X"f0d2", X"f54a", X"20b1", X"0792",
                                                        X"f4a3", X"14ae", X"0111", X"0631", X"fd84", X"fd80", X"fdf7", X"e0b8", X"eadc", X"ed6f", X"f315", X"0ed0", X"f0be", X"fa9b",
                                                        X"0c05", X"192d", X"077e", X"0d7e", X"eb7a", X"febd", X"f1b7", X"fe29", X"f441", X"ea6d", X"f930", X"ded8", X"f0b5", X"de13",
                                                        X"0bc5", X"f5ff", X"1dce", X"04fe", X"0771", X"0292", X"f711", X"f7fd", X"fb1f", X"e377", X"fabc", X"f139", X"21c5", X"ea98",
                                                        X"0862", X"eefa", X"f084", X"f85d", X"02ad", X"0c3c", X"02d4", X"f8f5", X"1722", X"ffb3", X"fe0b", X"067f", X"fc2b", X"f849",
                                                        X"f9be", X"ef7f", X"f71f", X"f81b", X"04a4", X"f97d", X"0764", X"003b", X"faf6", X"07f3", X"1b04", X"fb81", X"f78a", X"0e81",
                                                        X"ec7a", X"084b", X"00e4", X"fa4c", X"0342", X"dfb1", X"00eb", X"0319", X"f5a6", X"06dd", X"ec3c", X"f058", X"242d", X"0b93",
                                                        X"fa53", X"1779", X"fd11", X"096e", X"05fa", X"0b51", X"02f7", X"2216", X"f3d1", X"edcf", X"fcf0", X"10ce", X"f133", X"1ac6",
                                                        X"0052", X"fe31", X"0a58", X"18f5", X"f164", X"25fd", X"0a5a", X"fa4d", X"40a1", X"03ee", X"ff99", X"fae9", X"0390", X"0dd5",
                                                        X"1016", X"fa06", X"f881", X"fab4", X"0381", X"1a66", X"eb7d", X"34d8", X"16ee", X"03a5", X"0f79", X"fa11", X"1492", X"03e1",
                                                        X"004f", X"0a73", X"e810", X"f8a5", X"0957", X"0836", X"fbf9", X"0c2c", X"da9b", X"0e54", X"0b22", X"260a", X"01f8", X"f505",
                                                        X"e280", X"fdd4", X"eaac", X"0268", X"fbed", X"0a3c", X"fd66", X"0385", X"f562", X"0438", X"fabb", X"10cb", X"eaff", X"014e",
                                                        X"fb84", X"0289", X"07e4", X"0131", X"effa", X"04f3", X"0c4e", X"f134", X"1a77", X"04b6", X"062d", X"0b88", X"0e1b", X"120f",
                                                        X"07a1", X"1212", X"0c6e", X"f6e3", X"1268", X"02ec", X"07dd", X"05d7", X"0c4b", X"ed8b", X"0358", X"0859", X"12c1", X"038a",
                                                        X"d79d", X"1bf1", X"0165", X"f53f", X"1201", X"f984", X"0a15", X"fd2d", X"0eb6", X"fecd", X"07ca", X"0531", X"f529", X"093d",
                                                        X"0eb8", X"ec22", X"d70d", X"ebfa", X"f09a", X"07da", X"1660", X"0ba6", X"eb09", X"0679", X"101b", X"f59c", X"ee10", X"1670",
                                                        X"0e50", X"0360", X"0991", X"0239", X"d77f", X"0f8c", X"fac7", X"f7fa", X"ffca", X"09a3", X"3676", X"f595", X"dd9f", X"10d5",
                                                        X"f8ec", X"1a9d", X"ecd9", X"0736", X"f8df", X"ef8d", X"f1fc", X"f9cf", X"11a4", X"f304", X"e963", X"edd9", X"ea07", X"0be4",
                                                        X"0911", X"ff3c", X"f90c", X"f5d9", X"fa23", X"1065", X"0559", X"eca8", X"f8ed", X"dbc7", X"0a57", X"ff9e", X"0dd9", X"fecd",
                                                        X"3119", X"ff7b", X"1998", X"1037", X"0c6f", X"10d7", X"13fb", X"1372", X"fc35", X"f7e8", X"fe3f", X"f314", X"04e3", X"f3f2",
                                                        X"09bc", X"030b", X"eaa1", X"0c7f", X"f3c7", X"16f7", X"1d6f", X"0eb9", X"1623", X"1373", X"d674", X"07ed", X"f8e0", X"ee39",
                                                        X"0228", X"dfe3", X"0449", X"02ab", X"125f", X"fe6b", X"196f", X"0d81", X"e1bc", X"efd2", X"fa50", X"089b", X"ff92", X"ff21",
                                                        X"2432", X"f920", X"e845", X"e92e", X"f610", X"0dfd", X"eff8", X"f883", X"19eb", X"0382", X"0feb", X"f34b", X"fa2d", X"0178",
                                                        X"eede", X"0aa3", X"053c", X"0d4d", X"06ee", X"f28d", X"01d4", X"19d5", X"e94c", X"f8a8", X"fd30", X"f07e", X"0d0a", X"11a8",
                                                        X"0360", X"fef3", X"fffd", X"196b", X"1468", X"ff17", X"0abf", X"ef78", X"075c", X"15f2", X"e756", X"fa31", X"fdd6", X"0bce",
                                                        X"1c6b", X"e1e5", X"01e3", X"fd45", X"f2bd", X"0b93", X"004a", X"fb44", X"ed3b", X"1126", X"026a", X"f405", X"0856", X"143c",
                                                        X"1616", X"f98c", X"f3d7", X"eb21", X"11c4", X"0b6d", X"ea16", X"1b3a", X"ea4b", X"21d7", X"e19f", X"12ff", X"fa77", X"fd12",
                                                        X"e0aa", X"ed15", X"da46", X"07d8", X"0499", X"f0a6", X"1117", X"0490", X"0ab1", X"1347", X"faab", X"0aae", X"f682", X"f4d1",
                                                        X"0671", X"ffc7", X"f1d2", X"f2c1", X"0717", X"ffa5", X"0473", X"fc49", X"1432", X"eb47", X"0aec", X"15b4", X"ed03", X"2773",
                                                        X"f0d6", X"f2be", X"0129", X"eb9e", X"fa28", X"fca1", X"f997", X"15b4", X"f5dd", X"081b", X"feb3", X"ffc1", X"0a9c", X"f343",
                                                        X"e9d4", X"0f94", X"fcaf", X"f2f1", X"00fb", X"020e", X"fffe", X"f47d", X"f65d", X"0311", X"f1d6", X"f4f8", X"fd86", X"034b",
                                                        X"1dfc", X"038f", X"fbb9", X"11fc", X"fd0d", X"0547", X"ff35", X"dba8", X"dca5", X"ffaf", X"fa76", X"0e14", X"0465", X"0cfc",
                                                        X"f773", X"f878", X"0ba6", X"0e3d", X"f7fa", X"0c06", X"ff9c", X"10aa", X"2092", X"f8c7", X"e64a", X"eafc", X"0b3d", X"ee47",
                                                        X"112c", X"0d80", X"ebd6", X"fe2d", X"f455", X"02f6", X"db7e", X"0fb5", X"094b", X"f753", X"17ba", X"f6c3", X"eff5", X"f29d",
                                                        X"0f9a", X"fd83", X"fd5f", X"13f0", X"fe3a", X"0f1c", X"fbf9", X"12af", X"f225", X"ef93", X"0dbe", X"118e", X"1e97", X"018f",
                                                        X"1cab", X"fdbd", X"0fb3", X"f1f2", X"0a75", X"1546", X"021d", X"0dde", X"fd06", X"0d0f", X"eacf", X"d95a", X"0f0c", X"0d11",
                                                        X"fbaf", X"fcaa", X"fb3b", X"06d5", X"05fd", X"06af", X"e54a", X"0f37", X"f3b6", X"ff2e", X"0142", X"0330", X"e0f3", X"da11",
                                                        X"0012", X"e988", X"f893", X"eeed", X"2381", X"fb79", X"03df", X"0361", X"0e12", X"0643", X"036a", X"08af", X"02c7", X"0842",
                                                        X"e13d", X"f2a2", X"f6d7", X"ee82", X"f470", X"0c2d", X"0a7f", X"0c58", X"f2c3", X"0ce6", X"00ea", X"0650", X"ff38", X"10aa",
                                                        X"ea68", X"f65f", X"18d5", X"dac5", X"f277", X"d084", X"f701", X"e938", X"e21c", X"0f0d", X"21ab", X"36da", X"18d0", X"fe7f",
                                                        X"f6fe", X"1128", X"f339", X"f8ee", X"deef", X"d0bd", X"fc04", X"e34a", X"e930", X"0e04", X"f0c4", X"ebf0", X"161e", X"ed42",
                                                        X"ef98", X"0668", X"f073", X"00cc", X"f496", X"f5c4", X"d9fc", X"f19f", X"0218", X"f06e", X"e7b5", X"f405", X"0b71", X"fc87",
                                                        X"1451", X"07a2", X"00ab", X"f524", X"1568", X"fc56", X"f194", X"f4cc", X"fec6", X"1bbc", X"f421", X"de67", X"1285", X"e5b9",
                                                        X"f646", X"0b5c", X"f64b", X"1b1f", X"0d64", X"0a3b", X"11e2", X"0060", X"fe0e", X"0a6a", X"eeaf", X"25d1", X"f643", X"0829",
                                                        X"0913", X"fb7f", X"e783", X"07e9", X"f9ac", X"f264", X"ff70", X"083d", X"105e", X"0a82", X"ef51", X"1114", X"d00c", X"0b18",
                                                        X"1e5f", X"f064", X"034c", X"ffc8", X"e379", X"edbf", X"da99", X"1675", X"fb33", X"faba", X"fa86", X"e7d8", X"f6c1", X"1fa6",
                                                        X"f8d3", X"222b", X"052e", X"f07d", X"0388", X"2203", X"15b7", X"fc05", X"e739", X"f448", X"00c1", X"0c6d", X"0647", X"fc01",
                                                        X"1775", X"1219", X"d5a2", X"0275", X"ff98", X"fe00", X"042e", X"0077", X"e7f1", X"055f", X"051b", X"0195", X"efae", X"0440",
                                                        X"039c", X"0537", X"fef5", X"2cb0", X"ec56", X"1d64", X"ed66", X"f671", X"087f", X"0d98", X"f129", X"0f63", X"f799", X"fc09",
                                                        X"01ad", X"0b40", X"01b7", X"00ec", X"0d82", X"06c4", X"d1ca", X"f681", X"0784", X"23d5", X"ff58", X"e915", X"10ed", X"0927",
                                                        X"ef5e", X"0fd7", X"eef5", X"f83a", X"076f", X"0d93", X"0a65", X"1f34", X"16ce", X"1803", X"1062", X"09cf", X"08fe", X"f0b4",
                                                        X"df2f", X"fd3c", X"ed96", X"f129", X"f7a8", X"072d", X"facb", X"fb44", X"070b", X"2352", X"f6b9", X"fb70", X"ea19", X"0151",
                                                        X"0cf9", X"0554", X"10c4", X"0e2b", X"f9dc", X"f11e", X"035a", X"f0ae", X"fb82", X"0117", X"faa8", X"0301", X"f18b", X"f8b0",
                                                        X"de16", X"fdfd", X"091a", X"fb53", X"1aaf", X"0b0b", X"02f0", X"e8e2", X"0369", X"0612", X"fcb1", X"1224", X"0848", X"1f9e",
                                                        X"f7a0", X"f135", X"1082", X"0d5f", X"11be", X"fd00", X"16a6", X"f47e", X"efe1", X"09e4", X"044f", X"11b1", X"f9a3", X"1256",
                                                        X"f0e1", X"e40b", X"d804", X"e762", X"f9c7", X"eb0e", X"0a06", X"0621", X"e855", X"08e9", X"fbf4", X"1cd1", X"1757", X"ebda",
                                                        X"e3e3", X"01d2", X"014a", X"fbef", X"0ddb", X"f4f5", X"fc1d", X"0052", X"f6ec", X"0846", X"df0f", X"0ca1", X"19d6", X"1984",
                                                        X"0c5e", X"f1fa", X"fffd", X"03da", X"eb74", X"fe71", X"282a", X"fcc0", X"f040", X"e65a", X"f203", X"000c", X"dfee", X"0775",
                                                        X"193c", X"0d01", X"1024", X"0c41", X"fdef", X"1634", X"f03e", X"075f", X"dcc3", X"de7b", X"0903", X"e6a0", X"01c5", X"f500",
                                                        X"ec89", X"09b7", X"f43d", X"1472", X"0c0d", X"f865", X"ff18", X"0da5", X"03d4", X"09b4", X"1870", X"f226", X"0bc7", X"dcdf",
                                                        X"f628", X"05a5", X"e553", X"f263", X"0467", X"edd1", X"1a34", X"ec4b", X"021b", X"ef64", X"fdf3", X"061c", X"fd63", X"0022",
                                                        X"f66c", X"eef1", X"f2b9", X"1182", X"facd", X"db08", X"f6e3", X"0e50", X"ff4a", X"050a", X"f285", X"f36c", X"eaa2", X"1a3b",
                                                        X"18e4", X"06d2", X"fadf", X"f976", X"f4aa", X"0eb6", X"1089", X"0368", X"0b9e", X"0965", X"f90a", X"01b2", X"07cb", X"04cd",
                                                        X"1040", X"0051", X"dea8", X"0b84", X"04df", X"008c", X"12dd", X"f994", X"e78a", X"f0b0", X"f953", X"0a47", X"0e47", X"f8e8",
                                                        X"e6bd", X"0126", X"f56c", X"14d9", X"eecc", X"0174", X"094e", X"f619", X"1479", X"038c", X"169f", X"fd0f", X"f6d7", X"eb6c",
                                                        X"02ea", X"fbd5", X"f8c8", X"00c4", X"0dd9", X"1e2e", X"f28c", X"0c56", X"0323", X"fe46", X"ff45", X"0145", X"fcb0", X"f1ae",
                                                        X"f4c4", X"0f51", X"ea8c", X"f85d", X"0c83", X"f1d4", X"08a8", X"0072", X"e08c", X"20ca", X"eb00", X"0671", X"1219", X"fc11",
                                                        X"f8f0", X"fd10", X"0372", X"f9dc", X"0f23", X"02ac", X"fc9b", X"f83e", X"09d4", X"13ae", X"eb1a", X"3636", X"0150", X"2b9c",
                                                        X"070b", X"034e", X"f67f", X"f028", X"f0a5", X"ffcd", X"ff5e", X"f797", X"fcda", X"0670", X"f675", X"fa8d", X"05c2", X"0125",
                                                        X"f358", X"149f", X"0775", X"fd56", X"0f20", X"01e3", X"e129", X"f788", X"ff90", X"064a", X"1031", X"0d98", X"fcb2", X"1582",
                                                        X"061a", X"13a7", X"ee88", X"ff91", X"1465", X"f56d", X"0943", X"09ea", X"019e", X"088b", X"f950", X"121c", X"10aa", X"091d",
                                                        X"068a", X"ec41", X"d7a2", X"10bd", X"edc4", X"0d43", X"17ba", X"03b6", X"2e4b", X"f5a1", X"f5b0", X"fbd8", X"015e", X"0b6e",
                                                        X"123b", X"0b2e", X"025e", X"1451", X"18e8", X"e59f", X"f878", X"fb3a", X"fe79", X"0aa8", X"3005", X"faff", X"032f", X"007c",
                                                        X"1945", X"fb78", X"f296", X"00e4", X"070d", X"0155", X"00a1", X"017e", X"0e71", X"0367", X"f418", X"1221", X"014f", X"ed74",
                                                        X"0e54", X"1e2c", X"127d", X"fdc2", X"f489", X"1103", X"0221", X"129c", X"f6b0", X"d069", X"0044", X"ddc3", X"fae7", X"f634",
                                                        X"f822", X"f5cd", X"1429", X"20fb", X"120d", X"f7ef", X"fdcf", X"fb05", X"0aa7", X"f067", X"013f", X"0332", X"f83e", X"f527",
                                                        X"0317", X"f6f8", X"04a1", X"0b2b", X"f9da", X"0b08", X"07bd", X"fa41", X"0d77", X"0461", X"e991", X"f961", X"fea2", X"ec4e",
                                                        X"f37a", X"e6de", X"e960", X"0eca", X"2e46", X"021a", X"128b", X"2b76", X"168c", X"0285", X"e531", X"04ac", X"e5c7", X"f199",
                                                        X"ff03", X"fd1c", X"fcde", X"ec8e", X"d870", X"ff4c", X"0617", X"131c", X"f55c", X"1351", X"114f", X"fc6a", X"f906", X"1ade",
                                                        X"0146", X"11cc", X"da19", X"e81d", X"0b0c", X"f148", X"fa02", X"ddae", X"f77a", X"0959", X"00b2", X"f930", X"02a3", X"f1bd",
                                                        X"fb0c", X"008f", X"fe84", X"f6f9", X"d1c0", X"02af", X"f0de", X"e3a1", X"1a7d", X"f7e2", X"0ed1", X"15fb", X"2a0a", X"15ec",
                                                        X"0bc6", X"ef12", X"0af6", X"0c01", X"fa72", X"1193", X"0fec", X"fa4f", X"f10a", X"e3e6", X"1ec2", X"0b8d", X"dec3", X"101b",
                                                        X"01e8", X"fdf4", X"0c58", X"dfa3", X"1ec4", X"04f8", X"f086", X"02bb", X"e788", X"20cb", X"02a7", X"fd04", X"edc9", X"26ea",
                                                        X"dc82", X"168c", X"f714", X"0a79", X"f310", X"f65d", X"0d7c", X"ff14", X"f48c", X"165c", X"e0df", X"1e92", X"e57a", X"e27a",
                                                        X"13da", X"fa1d", X"0646", X"0a7f", X"0ab4", X"efd0", X"de54", X"f84f", X"fa45", X"0526", X"faba", X"0a99", X"f51e", X"2870",
                                                        X"16bd", X"0d12", X"1239", X"0002", X"f65d", X"04c7", X"fae6", X"f87f", X"06ed", X"071e", X"066e", X"f682", X"fb5e", X"161c",
                                                        X"ec44", X"2687", X"ed33", X"0434", X"10a9", X"f453", X"e5b2", X"015d", X"0ae2", X"f445", X"ff79", X"024c", X"0903", X"105e",
                                                        X"007b", X"072b", X"0980", X"1466", X"f60a", X"fac5", X"fe3a", X"14fb", X"f037", X"0b51", X"0409", X"0e38", X"01ca", X"0f6c",
                                                        X"0c78", X"f5ee", X"07cc", X"1506", X"cd9a", X"0a71", X"f68d", X"025b", X"f22d", X"005b", X"0945", X"0026", X"ffc1", X"f6ed",
                                                        X"00d2", X"0c1d", X"10db", X"feec", X"11bb", X"1486", X"e184", X"ec89", X"f708", X"1740", X"0249", X"0280", X"0d06", X"157a",
                                                        X"0f44", X"ec24", X"ea6c", X"1698", X"fe7e", X"0cc0", X"f326", X"1176", X"e7ff", X"0908", X"fd2f", X"0ee4", X"02cb", X"f77b",
                                                        X"181e", X"f797", X"1459", X"ec2b", X"01d7", X"faab", X"1034", X"08c9", X"16ea", X"f82d", X"086e", X"e11c", X"00b5", X"f63a",
                                                        X"0736", X"0780", X"1f80", X"0265", X"feac", X"ff30", X"fd1e", X"0e8f", X"0279", X"121b", X"f41f", X"167a", X"ff8c", X"daf4",
                                                        X"fe37", X"00a5", X"f80a", X"f1fb", X"1a70", X"0a49", X"13fd", X"091c", X"1676", X"08fe", X"f04c", X"0736", X"ef6b", X"f573",
                                                        X"1116", X"d80f", X"0cf8", X"f42e", X"f157", X"0dc3", X"1ef6", X"fba2", X"0da0", X"ffb6", X"0353", X"04da", X"f248", X"0b4a",
                                                        X"01b4", X"f6cb", X"f043", X"c4fb", X"0094", X"e487", X"feb7", X"0230", X"da4a", X"fada", X"0203", X"1c06", X"1256", X"07f5",
                                                        X"164d", X"03f8", X"eb14", X"f304", X"e1cd", X"bb23", X"fa0a", X"ce6a", X"f325", X"e4b0", X"1088", X"fd0e", X"233e", X"03bd",
                                                        X"1935", X"0b4e", X"fb0b", X"f851");
  SIGNAL data_int                         : std_logic_vector(DataWidth - 1 DOWNTO 0) := X"f851";
  SIGNAL addr_unsigned                    : unsigned(AddrWidth - 1 DOWNTO 0);  -- generic width

BEGIN
  addr_unsigned <= unsigned(addr);

  SinglePortRAM_generic_process: PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF enb = '1' THEN
        IF we = '1' THEN
          ram(to_integer(addr_unsigned)) <= din;
          data_int <= din;
        ELSE
          data_int <= ram(to_integer(addr_unsigned));
        END IF;
      END IF;
    END IF;
  END PROCESS SinglePortRAM_generic_process;

  dout <= data_int;

END rtl;

