-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/amc_model_w16a16/amc_cnn_16w16a_src_SinglePortRAM_generic_block336.vhd
-- Created: 2023-08-04 11:27:13
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: amc_cnn_16w16a_src_SinglePortRAM_generic_block336
-- Source Path: amc_model_w16a16/DUT HDL/Dense Layer 1/Dense Layer 1/Weight Storage104/SinglePortRAM_generic
-- Hierarchy Level: 4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY amc_cnn_16w16a_src_SinglePortRAM_generic_block336 IS
  GENERIC( AddrWidth                      : integer := 1;
           DataWidth                      : integer := 1
           );
  PORT( clk                               :   IN    std_logic;
        enb                               :   IN    std_logic;
        din                               :   IN    std_logic_vector(DataWidth - 1 DOWNTO 0);  -- generic width
        addr                              :   IN    std_logic_vector(AddrWidth - 1 DOWNTO 0);  -- generic width
        we                                :   IN    std_logic;  -- ufix1
        dout                              :   OUT   std_logic_vector(DataWidth - 1 DOWNTO 0)  -- generic width
        );
END amc_cnn_16w16a_src_SinglePortRAM_generic_block336;


ARCHITECTURE rtl OF amc_cnn_16w16a_src_SinglePortRAM_generic_block336 IS

  -- Local Type Definitions
  TYPE ram_type IS ARRAY (2**AddrWidth - 1 DOWNTO 0) of std_logic_vector(DataWidth - 1 DOWNTO 0);

  -- Signals
  SIGNAL ram                              : ram_type := (X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"188d", X"06ad", X"f394", X"f045", X"1129", X"f88a",
                                                        X"e0d1", X"fdc3", X"0683", X"1d37", X"f59e", X"06de", X"1a86", X"fc75", X"0961", X"1708", X"f302", X"f0a1", X"e1aa", X"f833",
                                                        X"038c", X"00f5", X"fbac", X"0029", X"0cb2", X"f198", X"08cf", X"0aa8", X"ee0a", X"f85f", X"0db8", X"0785", X"f2db", X"01e4",
                                                        X"165a", X"02b3", X"074e", X"ef25", X"fcd8", X"f753", X"0c6e", X"03bd", X"f1f5", X"fbfd", X"098a", X"fc07", X"facf", X"063d",
                                                        X"f7f3", X"f9de", X"e568", X"0014", X"0389", X"ff74", X"e8a8", X"1627", X"0e3f", X"fac3", X"ef83", X"f586", X"0246", X"f657",
                                                        X"eff3", X"04a8", X"023e", X"ff58", X"fb55", X"ee35", X"fda0", X"fd6b", X"edc9", X"ec84", X"0fa3", X"1524", X"e88f", X"05a1",
                                                        X"f3be", X"0b31", X"ff4c", X"067b", X"fa15", X"eb29", X"ff70", X"ff01", X"fa36", X"f1a5", X"f3ef", X"106b", X"dc89", X"336b",
                                                        X"e8ce", X"f6c9", X"ee71", X"0c2e", X"eff1", X"03c5", X"f3ae", X"f63c", X"15d8", X"09b1", X"07cd", X"0c5c", X"1c2d", X"1b6a",
                                                        X"f76e", X"ff90", X"e35d", X"eb82", X"fa89", X"064d", X"06da", X"1afb", X"155d", X"0c3f", X"0dd0", X"090f", X"efda", X"0025",
                                                        X"0b6f", X"258e", X"db80", X"fc6c", X"156d", X"f895", X"f636", X"e7e2", X"044b", X"f26c", X"0574", X"e7b0", X"0742", X"0f88",
                                                        X"02a7", X"e8cc", X"f6aa", X"e304", X"0fea", X"13ba", X"e97c", X"f7cf", X"f7e0", X"ebf9", X"f5cb", X"f3a8", X"0baa", X"0982",
                                                        X"e14e", X"0149", X"f750", X"fc45", X"28dc", X"f376", X"0964", X"f8e8", X"18a2", X"facc", X"04ef", X"eb0a", X"fba7", X"f26a",
                                                        X"06dd", X"06d4", X"e55d", X"086f", X"f930", X"148d", X"1af6", X"0820", X"f7fa", X"0c02", X"1dba", X"f401", X"f30c", X"f53f",
                                                        X"05e5", X"ee21", X"0be8", X"f56a", X"123a", X"02c5", X"f3ef", X"f83d", X"1273", X"094a", X"dc07", X"fb17", X"01db", X"0cb2",
                                                        X"f474", X"f176", X"0739", X"f16f", X"fcd6", X"dc04", X"059f", X"02a3", X"f0bd", X"0194", X"0cac", X"f90f", X"0502", X"fd15",
                                                        X"2739", X"0c08", X"09da", X"0438", X"0a29", X"08eb", X"f4b6", X"ec12", X"ee0b", X"f601", X"efe9", X"f6ea", X"10b7", X"09e7",
                                                        X"1e37", X"e370", X"15c7", X"09e3", X"f496", X"f6d5", X"f618", X"f000", X"0d59", X"e937", X"1819", X"055c", X"0632", X"091c",
                                                        X"1888", X"1b53", X"2acb", X"fa7b", X"0d68", X"0c35", X"080d", X"fbef", X"142c", X"0e78", X"075f", X"e33b", X"eb51", X"06f3",
                                                        X"edbb", X"ebc7", X"0222", X"e48b", X"e612", X"e7bd", X"2335", X"e613", X"1290", X"0583", X"1150", X"107d", X"fecf", X"c9a5",
                                                        X"1f48", X"06b0", X"f822", X"02aa", X"26cb", X"ff5f", X"0313", X"12cb", X"e59d", X"08f3", X"fdf5", X"fe9e", X"f8b9", X"fbe7",
                                                        X"0baa", X"e957", X"f72a", X"0a56", X"072f", X"11e2", X"fcd6", X"1828", X"06f9", X"fc83", X"19aa", X"ffd5", X"0ebd", X"f66e",
                                                        X"03ae", X"f401", X"1060", X"0ee0", X"0c47", X"f999", X"ed7d", X"f5a0", X"0d98", X"fb8d", X"13a3", X"1c1e", X"ed76", X"fdbb",
                                                        X"f446", X"0129", X"f7a4", X"f5be", X"fe94", X"fbc0", X"f047", X"fd73", X"04f3", X"0663", X"f1e4", X"fcfe", X"edd5", X"f205",
                                                        X"1fc6", X"f6e6", X"04eb", X"0a3c", X"ff36", X"08e8", X"f9a2", X"0f75", X"f7a8", X"06c8", X"e7e5", X"f251", X"0059", X"f264",
                                                        X"f9c3", X"df85", X"0bbc", X"f9aa", X"fc13", X"0106", X"fec9", X"1214", X"ff97", X"e4aa", X"d4e7", X"facc", X"1bce", X"e648",
                                                        X"0aac", X"f214", X"1314", X"ed6c", X"eeca", X"00d0", X"fac2", X"f7d0", X"fe98", X"ec55", X"018c", X"12b1", X"1b21", X"158a",
                                                        X"f59a", X"e8fe", X"fbfc", X"04c5", X"dcf1", X"0359", X"09f5", X"0059", X"0af8", X"f261", X"fced", X"fb11", X"08ca", X"f6a6",
                                                        X"1712", X"0bb4", X"113d", X"01b3", X"f87a", X"ef1b", X"1e3e", X"f45f", X"f915", X"135e", X"0ad9", X"f52d", X"ece1", X"0c44",
                                                        X"09c6", X"0514", X"fa15", X"f7e3", X"0bf8", X"0f39", X"070c", X"1ece", X"e341", X"fc51", X"f77a", X"ef24", X"f7fd", X"ffc6",
                                                        X"07c3", X"0fb4", X"0ef3", X"f925", X"ef55", X"ed7e", X"061f", X"0a79", X"0849", X"f807", X"e87b", X"19e9", X"f9f1", X"097a",
                                                        X"08d7", X"11ac", X"0338", X"06a4", X"08c2", X"fbf8", X"f2a0", X"0aea", X"f7ae", X"f610", X"f27a", X"097b", X"ef47", X"e131",
                                                        X"0bc8", X"f1a5", X"f6a3", X"f1ce", X"f309", X"14cf", X"0631", X"f0bc", X"1dc5", X"fdac", X"ec45", X"06d4", X"e6ce", X"31af",
                                                        X"245d", X"e14d", X"29f5", X"04e7", X"05cb", X"051f", X"fb4e", X"f5d9", X"0ce4", X"fcff", X"f31a", X"fcb3", X"ff3e", X"03f3",
                                                        X"19fe", X"1acb", X"e364", X"f067", X"f8d1", X"0196", X"11a6", X"f767", X"f749", X"043c", X"0c02", X"1471", X"0340", X"edb1",
                                                        X"0876", X"e82b", X"1645", X"e26b", X"0e46", X"f4ed", X"fa1f", X"ed39", X"07b4", X"ecef", X"0ea8", X"0486", X"0348", X"103b",
                                                        X"d955", X"e323", X"1a7a", X"f8ca", X"06df", X"1cf5", X"e62f", X"fa32", X"3371", X"fa2a", X"f9db", X"1218", X"0efc", X"f0b4",
                                                        X"187c", X"0c6a", X"f526", X"f1a7", X"f516", X"eeee", X"fae1", X"1a54", X"1276", X"1168", X"0158", X"f13f", X"e174", X"11bf",
                                                        X"12b6", X"0bb7", X"0f85", X"fb3d", X"e341", X"0bea", X"0481", X"fcea", X"098a", X"0fda", X"e623", X"e545", X"1b1e", X"08de",
                                                        X"f2e7", X"ef90", X"024a", X"dddf", X"0426", X"ecab", X"1533", X"0069", X"fdb4", X"f027", X"2d21", X"f0b4", X"0623", X"feb8",
                                                        X"ff8a", X"fd4c", X"ff69", X"f8ea", X"03a4", X"f5cd", X"00e1", X"0d89", X"d62b", X"169c", X"fe03", X"0654", X"f0c8", X"f2d0",
                                                        X"0275", X"dd39", X"1ce8", X"f5d2", X"05ea", X"fda2", X"f17d", X"dd82", X"0c11", X"dc94", X"f697", X"f5cf", X"fee5", X"0f08",
                                                        X"1c7d", X"2241", X"20d8", X"139e", X"f761", X"f462", X"eb14", X"fd90", X"fba1", X"ee92", X"1502", X"ea61", X"11ca", X"01d0",
                                                        X"ffa7", X"fe19", X"0a46", X"1139", X"f5d9", X"fe42", X"fd3f", X"149c", X"110f", X"fb2c", X"f566", X"086b", X"0cad", X"fea0",
                                                        X"0799", X"f8c3", X"0015", X"0ab2", X"005a", X"ffae", X"1170", X"eb6c", X"2161", X"0cf5", X"fc4d", X"0c17", X"fec6", X"f986",
                                                        X"0371", X"e39b", X"eebf", X"0506", X"fa3d", X"f8f0", X"07b5", X"fa0a", X"28cc", X"19a9", X"133e", X"f21a", X"079f", X"0bc7",
                                                        X"0729", X"0af3", X"099b", X"05cc", X"fc5c", X"ef46", X"0ded", X"0ed4", X"168a", X"1287", X"f83d", X"fc6a", X"eae8", X"fa8c",
                                                        X"fe44", X"fcb5", X"02cb", X"05d9", X"11d1", X"0569", X"1f84", X"fa3d", X"fc43", X"f0a0", X"ec9d", X"fd18", X"e81a", X"2503",
                                                        X"f08a", X"1e4a", X"f70a", X"fb62", X"efe5", X"f869", X"f9f3", X"e496", X"e129", X"fe16", X"f57e", X"fac2", X"0ee4", X"0906",
                                                        X"174d", X"00ad", X"0be8", X"f379", X"f3ee", X"fdb9", X"eba4", X"10cc", X"f95d", X"0542", X"0d88", X"0607", X"0ac9", X"0ea3",
                                                        X"dc52", X"fde8", X"0e17", X"f865", X"e1b6", X"09ec", X"fcc6", X"0615", X"029b", X"0ec5", X"ff30", X"0a57", X"f847", X"0c6d",
                                                        X"ff60", X"030a", X"f5a6", X"1882", X"2038", X"f2c7", X"0f4a", X"fa62", X"fa08", X"0887", X"f576", X"13cc", X"044d", X"0d44",
                                                        X"0aa4", X"f9ab", X"f4a7", X"099c", X"d659", X"0dad", X"1fad", X"0bf4", X"faf8", X"03db", X"fcb0", X"f9c2", X"f226", X"1284",
                                                        X"ef13", X"fb6e", X"0f3f", X"f8f5", X"fcd4", X"f48e", X"fe69", X"e8c8", X"058f", X"1361", X"e4d6", X"0d39", X"01f4", X"133c",
                                                        X"fe3a", X"2fa5", X"fdbe", X"14ca", X"f81f", X"eef4", X"109f", X"0f9e", X"0a4c", X"fd29", X"ec16", X"0c1e", X"0cdf", X"06e1",
                                                        X"ebf8", X"0d16", X"ffe4", X"13b3", X"0f1b", X"de1b", X"fa6a", X"0947", X"ef64", X"fc69", X"ece0", X"1787", X"125d", X"f10f",
                                                        X"f321", X"fd52", X"e2ef", X"0958", X"fae7", X"ee3b", X"f249", X"0e7f", X"0138", X"118b", X"0287", X"0994", X"f5ff", X"0d0a",
                                                        X"f66a", X"f131", X"f354", X"ff29", X"f646", X"fb70", X"f87b", X"f74d", X"fd4f", X"00f2", X"e318", X"e47c", X"f5e8", X"0916",
                                                        X"08ac", X"ec5a", X"db3b", X"0bed", X"0e8a", X"064a", X"f618", X"1fef", X"fee1", X"07da", X"0516", X"f990", X"f4a3", X"de63",
                                                        X"01a7", X"213f", X"f972", X"f200", X"1dcb", X"f645", X"0365", X"f0ae", X"144e", X"003b", X"1c87", X"0d67", X"ee43", X"fbe3",
                                                        X"dbee", X"fe1c", X"0e1c", X"f0ed", X"0563", X"2607", X"0241", X"0c98", X"fcc3", X"0c54", X"eb11", X"01b3", X"0160", X"e9cb",
                                                        X"f5e9", X"eff4", X"04a1", X"0078", X"0d94", X"12dd", X"2394", X"01a0", X"ffab", X"0c2e", X"1933", X"fce4", X"1408", X"f9c4",
                                                        X"1b57", X"0af9", X"f8d1", X"ed93", X"f950", X"0d46", X"00d1", X"ffd1", X"fb06", X"0fa2", X"12c5", X"1361", X"00f9", X"035d",
                                                        X"f01d", X"fdcd", X"ff03", X"0bce", X"155c", X"fef7", X"f89a", X"127b", X"0bed", X"f9e0", X"1c6f", X"1bbe", X"1301", X"dabb",
                                                        X"2d63", X"e663", X"f7cb", X"0ce7", X"fab7", X"0863", X"1445", X"ffe9", X"1746", X"0835", X"f7c2", X"11f5", X"e586", X"f331",
                                                        X"05f7", X"e3d5", X"1643", X"f8f6", X"e099", X"0996", X"1c5c", X"0ba9", X"0f1c", X"e3d4", X"0dfb", X"f8e2", X"fb94", X"f498",
                                                        X"e6c4", X"16d0", X"1187", X"dc4a", X"1223", X"1492", X"0143", X"f81c", X"16ba", X"ff88", X"ffd6", X"f2be", X"f6e0", X"f6f9",
                                                        X"fc5a", X"0f12", X"f87b", X"0d08", X"f928", X"e206", X"1a43", X"f852", X"03c1", X"fa07", X"0424", X"f3c0", X"06e8", X"f4bc",
                                                        X"d93d", X"ede4", X"00a2", X"fe73", X"fe28", X"25cf", X"02d1", X"0f0e", X"2897", X"ffdf", X"f6f8", X"0323", X"f6c2", X"195d",
                                                        X"fbf7", X"11ce", X"ec67", X"ffad", X"04cc", X"e9da", X"fc70", X"0922", X"f1c2", X"e4e6", X"ee80", X"f609", X"08a8", X"fb90",
                                                        X"03c4", X"0924", X"0247", X"e817", X"d399", X"0d74", X"089d", X"f259", X"ed10", X"fb84", X"e8aa", X"2329", X"fd22", X"0031",
                                                        X"ee99", X"0438", X"fb1c", X"114a", X"04f1", X"ed08", X"dd0c", X"12a3", X"0e4b", X"09af", X"00ae", X"188e", X"ff37", X"0128",
                                                        X"07e4", X"01e6", X"043d", X"0508", X"0800", X"fa98", X"0152", X"f567", X"0a1a", X"0a44", X"1192", X"f026", X"e6c6", X"1558",
                                                        X"fe82", X"2039", X"08c3", X"f95d", X"fd7b", X"eeef", X"0a63", X"025d", X"fa2a", X"f3b6", X"26ee", X"088c", X"ef01", X"e222",
                                                        X"f4d3", X"0456", X"1b83", X"07e8", X"ff04", X"fe61", X"0f51", X"03e4", X"fffe", X"0adf", X"fdfb", X"feb4", X"01bd", X"06f1",
                                                        X"02a9", X"1940", X"ebc7", X"0e17", X"1737", X"1ce3", X"0fc5", X"f980", X"fcd1", X"03ec", X"ea98", X"fefa", X"1220", X"11d6",
                                                        X"d3d5", X"fca4", X"f34e", X"1412", X"e93a", X"12f4", X"da5d", X"e1e9", X"dfea", X"fcdf", X"ee93", X"f324", X"efad", X"003a",
                                                        X"ee2a", X"1bbc", X"2511", X"e57e", X"0393", X"1d3a", X"e2a3", X"0296", X"fd50", X"1eb0", X"dbc5", X"f2bc", X"fbb1", X"fd5d",
                                                        X"f677", X"07c6", X"1c11", X"f934", X"104a", X"f652", X"0c66", X"fc0e", X"f607", X"0ac0", X"08e0", X"ff4e", X"05a1", X"f1f0",
                                                        X"fa96", X"102c", X"f039", X"dd97", X"00f4", X"fc58", X"0803", X"0375", X"fd4b", X"fadd", X"fa15", X"0e7f", X"0383", X"1cb6",
                                                        X"f19d", X"05f2", X"0c9f", X"f984", X"e3c6", X"0d1d", X"f48c", X"0c62", X"064f", X"00ea", X"16ea", X"10e2", X"e9f6", X"00f3",
                                                        X"e6c9", X"038f", X"0ddb", X"082f", X"f50c", X"ee96", X"13ec", X"ef14", X"f118", X"1878", X"25ee", X"0a2f", X"06fa", X"0282",
                                                        X"f4f8", X"1dd6", X"1516", X"0a0c", X"dc22", X"ff09", X"ee55", X"fe19", X"0537", X"e18f", X"f687", X"19fb", X"09ca", X"f6f8",
                                                        X"e698", X"e856", X"fef7", X"0742", X"e91a", X"f6fc", X"d7e0", X"002e", X"1c04", X"ef5b", X"0e56", X"0122", X"0d8b", X"157f",
                                                        X"d2c5", X"076c", X"078c", X"008f", X"05d1", X"1e48", X"f3a4", X"051a", X"edee", X"ed41", X"094f", X"fb38", X"1290", X"f054",
                                                        X"edc5", X"08d1", X"14b8", X"ff8f", X"00ad", X"e214", X"da70", X"0c00", X"ebee", X"f5a2", X"1282", X"0171", X"0fc9", X"fb0c",
                                                        X"f988", X"0d9f", X"f6c3", X"e991", X"ed17", X"ed3e", X"f7d4", X"0efc", X"fc00", X"e1c7", X"f77b", X"08ec", X"e379", X"0c02",
                                                        X"01e4", X"f75f", X"dd3e", X"f693", X"f9f0", X"16b9", X"fb26", X"eab6", X"0635", X"ffd1", X"f8d9", X"ff9b", X"0e43", X"323d",
                                                        X"e3a2", X"f249", X"0685", X"04c2", X"e9a6", X"feb7", X"f318", X"f6fc", X"0023", X"073a", X"0bfa", X"0a58", X"c8f0", X"1c62",
                                                        X"ee09", X"0f88", X"c4fb", X"fdc1", X"f64a", X"17d1", X"e14d", X"2303", X"fb85", X"0955", X"0813", X"fc79", X"0d32", X"08d1",
                                                        X"ec73", X"15ea", X"01ff", X"1157", X"e3c0", X"08b2", X"029f", X"fdf2", X"ef4a", X"08c1", X"01aa", X"fbae", X"0a6d", X"0997",
                                                        X"f49e", X"0068", X"d12d", X"0818", X"1c07", X"fd11", X"c51f", X"f6dc", X"0e96", X"fcd9", X"ee14", X"0e01", X"02bc", X"ebb7",
                                                        X"08c9", X"fde6", X"e6bb", X"03c2", X"ba6b", X"0da5", X"e74c", X"270b", X"e391", X"f35e", X"fc0c", X"02e7", X"f3d3", X"05b5",
                                                        X"fa1f", X"01c3", X"1d69", X"ff32", X"10fa", X"e73d", X"c0f2", X"2333", X"f102", X"fe42", X"ceed", X"0848", X"0e8a", X"0d93",
                                                        X"f78d", X"176d", X"f4a8", X"f40a", X"15ff", X"1faa", X"0867", X"ee9d", X"db5d", X"10fd", X"18a1", X"0493", X"f28a", X"fd87",
                                                        X"056a", X"f133", X"e9ff", X"1ab4", X"f9be", X"124d", X"fa9c", X"ff6e", X"0e05", X"0641", X"cbb4", X"03be", X"0d8e", X"0226",
                                                        X"ebc5", X"f8fa", X"e895", X"f771", X"027f", X"0e28", X"0da2", X"dcc2", X"25a5", X"f111", X"0b5a", X"f844", X"d287", X"2f65",
                                                        X"25be", X"2099", X"ed4d", X"ecd6", X"f78a", X"f3fd", X"f372", X"fd36", X"0643", X"fe6c", X"138a", X"f1af", X"0c78", X"148c",
                                                        X"d7d2", X"0079", X"132e", X"27da", X"e896", X"de21", X"ff14", X"f265", X"02cb", X"1597", X"07cb", X"093f", X"2036", X"e83c",
                                                        X"1b74", X"fa19", X"e3fd", X"24c2", X"fdbd", X"fed5", X"170d", X"04d4", X"ef99", X"0765", X"07fc", X"ea54", X"107b", X"1e0a",
                                                        X"d597", X"f146", X"fef8", X"f5f5", X"e4c5", X"0add", X"1959", X"2925", X"f49b", X"fb90", X"08b3", X"070d", X"15b7", X"f005",
                                                        X"09cd", X"125d", X"0937", X"f871", X"113e", X"0aed", X"fc77", X"0393", X"f326", X"f923", X"1c76", X"f852", X"ef63", X"08ed",
                                                        X"fead", X"0f4f", X"f3dd", X"de56", X"0076", X"f987", X"00dd", X"f66f", X"f860", X"24c0", X"0608", X"30c3", X"13e7", X"07f7",
                                                        X"018c", X"114d", X"0aba", X"f1a0", X"ed5f", X"ef38", X"0859", X"0513", X"fe26", X"ea23", X"eefa", X"ee2a", X"fce6", X"14f3",
                                                        X"0737", X"fa0d", X"055e", X"0203", X"fcb0", X"14e6", X"0116", X"ebb4", X"d5f5", X"09e1", X"0545", X"f534", X"f6fd", X"0070",
                                                        X"1651", X"f610", X"f562", X"f7e1", X"f069", X"193b", X"0ba2", X"0421", X"108a", X"fd3f", X"f9b4", X"f167", X"ef58", X"0768",
                                                        X"062c", X"0a93", X"fb42", X"1cef", X"07f1", X"0088", X"f9d7", X"06b8", X"0566", X"0ca0", X"07f4", X"0ebf", X"e627", X"fe1b",
                                                        X"0747", X"f32c", X"e1dc", X"2cac", X"f0a5", X"16d6", X"f121", X"1029", X"1085", X"046f", X"14e5", X"fc32", X"fde9", X"0b58",
                                                        X"1199", X"ea9c", X"ef2a", X"f907", X"1196", X"ec4b", X"074e", X"ea16", X"011e", X"08fc", X"042a", X"fcd8", X"fb17", X"fabe",
                                                        X"f664", X"088e", X"f4e1", X"06bf", X"f22d", X"f9f7", X"ebc2", X"0c07", X"e5d3", X"f92e", X"0b21", X"eacf", X"fd6d", X"07ce",
                                                        X"f794", X"eb96", X"f85c", X"f2f9", X"fc09", X"f1ab", X"00fe", X"0608", X"12bf", X"07bb", X"fdad", X"0366", X"f45c", X"00c9",
                                                        X"ea2b", X"fdc9", X"ffc1", X"e94d", X"056e", X"1598", X"ca55", X"001b", X"092c", X"fdf1", X"157d", X"0f47", X"fe64", X"fffc",
                                                        X"1520", X"094a", X"fd92", X"11d4", X"0a5b", X"e7c3", X"0703", X"0acd", X"d02b", X"0a87", X"087f", X"f6b2", X"fe98", X"f57d",
                                                        X"1518", X"fb95", X"1d3a", X"0654", X"0e04", X"1633", X"0ec5", X"dd07", X"1a2a", X"cea9", X"e7ab", X"06b9", X"f20c", X"f573",
                                                        X"12e7", X"167f", X"fdce", X"eebe", X"20f2", X"0539", X"011d", X"0457", X"1389", X"f2e8", X"0fe4", X"faa5", X"e171", X"08dd",
                                                        X"eed9", X"f2c9", X"3c2c", X"27e7", X"0815", X"e312", X"2b9b", X"020e", X"fd31", X"f1f8", X"07ed", X"f9a9", X"060e", X"e85b",
                                                        X"eb73", X"fb27", X"fb46", X"004e", X"0ccc", X"2027", X"f2f2", X"dd8b", X"2f99", X"f3a6", X"fdb7", X"1609", X"0ded", X"ff92",
                                                        X"04bf", X"c7a8", X"ee3e", X"0561", X"ec31", X"fb7d", X"1190", X"1393", X"14d9", X"efe5", X"26b2", X"07ac", X"0c44", X"031d",
                                                        X"0599", X"de95", X"fdb5", X"f39f", X"d50d", X"0419", X"fd58", X"e965", X"1380", X"efdb", X"16fc", X"ed40", X"1b57", X"fc3f",
                                                        X"0470", X"0a8f", X"16f8", X"d893", X"022f", X"d0f5", X"f304", X"f6a3", X"fe3c", X"f0a0", X"27c3", X"e3f7", X"0f91", X"1393",
                                                        X"2ad1", X"0edf", X"fd43", X"0363", X"225a", X"e68b", X"1121", X"105f", X"dde7", X"056b", X"eacf", X"f04a", X"206d", X"120c",
                                                        X"1cc6", X"df7b", X"2624", X"0af5", X"0577", X"e79c", X"092c", X"0427", X"0dd1", X"0655", X"d172", X"f689", X"ee54", X"1235",
                                                        X"0749", X"ebe6", X"0ada", X"0fe2", X"3338", X"0882", X"01a2", X"062c", X"0d40", X"ea5b", X"fbf5", X"cbd2", X"f41d", X"0b7d",
                                                        X"fbf8", X"05eb", X"16b8", X"03fc", X"1a76", X"006c", X"01e0", X"0268", X"065c", X"016c", X"0271", X"00d3", X"ffe9", X"f96b",
                                                        X"e43b", X"0720", X"02a7", X"f360", X"f32e", X"15b6", X"3028", X"1581", X"1409", X"0591", X"f127", X"009a", X"13bf", X"f843",
                                                        X"f86d", X"0691", X"0727", X"1e04", X"0911", X"0774", X"00d7", X"2060", X"057f", X"e1ab", X"133a", X"f98d", X"fa35", X"00a0",
                                                        X"f13b", X"fa86", X"08c6", X"1976", X"01a5", X"f667", X"fa37", X"f775", X"ebc0", X"fee6", X"ed15", X"fd8e", X"00bd", X"f901",
                                                        X"e207", X"03d1", X"01a7", X"0694", X"fa6a", X"e4f6", X"f17d", X"f6e7", X"fd1f", X"0f4c", X"ded9", X"0ab7", X"0c5e", X"2a6f",
                                                        X"13ba", X"ff6d", X"03ba", X"f4cd", X"fc2c", X"f5af", X"0160", X"f590", X"f767", X"ed07", X"0f1a", X"fd1e", X"efcd", X"1f3c",
                                                        X"ed40", X"0629", X"ded7", X"04d3", X"08b4", X"054c", X"fc7c", X"ee1e", X"f925", X"140e", X"fa1e", X"092e", X"0e14", X"fa96",
                                                        X"eebc", X"fdce", X"f0d9", X"0da0", X"0681", X"07ee", X"fa97", X"1780", X"e843", X"0eb3", X"10cf", X"fad6", X"fc30", X"183b",
                                                        X"f83f", X"f4e6", X"d2da", X"158b", X"227b", X"2806", X"e63f", X"f328", X"06e8", X"0c94", X"fa46", X"18ee", X"0760", X"0d8c",
                                                        X"f9a2", X"0684", X"fa48", X"1946", X"dfdb", X"0ff8", X"21f8", X"0be2", X"f21c", X"f69b", X"03f0", X"f721", X"eeca", X"24e3",
                                                        X"0554", X"168a", X"ec2c", X"fab6", X"0f7b", X"f002", X"eb1c", X"fc6c", X"f2c0", X"f6b2", X"f93e", X"111e", X"0bbd", X"ffe3",
                                                        X"13f3", X"fc46", X"e665", X"e239", X"0621", X"02df", X"f246", X"eb3d", X"f338", X"1ad9", X"f80c", X"1ec8", X"e8b2", X"f3d8",
                                                        X"fc19", X"02d6", X"fc0e", X"fd97", X"01a6", X"1384", X"dbaf", X"f2ad", X"099b", X"f4a0", X"dd3d", X"16fe", X"1457", X"1abf",
                                                        X"04d7", X"05f8", X"f708", X"0d28", X"f6c2", X"12ee", X"1040", X"da71", X"df5e", X"0955", X"fe52", X"eb19", X"fcbd", X"0204",
                                                        X"12b9", X"2078", X"0650", X"048f", X"05df", X"ef09", X"0723", X"013e", X"0ec9", X"ee80", X"e7a3", X"e6a6", X"fa4d", X"eccf",
                                                        X"e2d1", X"072b", X"1b56", X"13f9", X"0a41", X"0959", X"f09b", X"fc9d", X"0412", X"158e", X"f487", X"fdcd", X"e3b6", X"faca",
                                                        X"0900", X"03d1", X"f3c1", X"1495", X"0b66", X"0b03", X"1b98", X"ff27", X"fd39", X"0d5c", X"05dc", X"e984", X"138b", X"e4d3",
                                                        X"dd7f", X"0abf", X"01f0", X"f7f3", X"0a84", X"1097", X"fba2", X"1613", X"0b0f", X"fc63", X"05ea", X"fe68", X"0cf4", X"0e54",
                                                        X"faa9", X"eecc", X"fb4a", X"0f67", X"ed66", X"ff42", X"f7de", X"0cc9", X"fc36", X"eb78", X"1b29", X"0fa1", X"0874", X"0c4c",
                                                        X"0817", X"0e17", X"f598", X"0184", X"e3cc", X"efcd", X"fedb", X"fa62", X"fb40", X"065f", X"1622", X"e620", X"07de", X"0791",
                                                        X"13fb", X"f5a3", X"0979", X"f9d2");
  SIGNAL data_int                         : std_logic_vector(DataWidth - 1 DOWNTO 0) := X"f9d2";
  SIGNAL addr_unsigned                    : unsigned(AddrWidth - 1 DOWNTO 0);  -- generic width

BEGIN
  addr_unsigned <= unsigned(addr);

  SinglePortRAM_generic_process: PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF enb = '1' THEN
        IF we = '1' THEN
          ram(to_integer(addr_unsigned)) <= din;
          data_int <= din;
        ELSE
          data_int <= ram(to_integer(addr_unsigned));
        END IF;
      END IF;
    END IF;
  END PROCESS SinglePortRAM_generic_process;

  dout <= data_int;

END rtl;

