-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/amc_model_w16a16/amc_cnn_16w16a_src_SinglePortRAM_generic_block2.vhd
-- Created: 2023-08-04 11:27:07
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: amc_cnn_16w16a_src_SinglePortRAM_generic_block2
-- Source Path: amc_model_w16a16/DUT HDL/Dense Layer 2/Dense Layer 2/Weight Storage 1/SinglePortRAM_generic
-- Hierarchy Level: 4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY amc_cnn_16w16a_src_SinglePortRAM_generic_block2 IS
  GENERIC( AddrWidth                      : integer := 1;
           DataWidth                      : integer := 1
           );
  PORT( clk                               :   IN    std_logic;
        enb                               :   IN    std_logic;
        din                               :   IN    std_logic_vector(DataWidth - 1 DOWNTO 0);  -- generic width
        addr                              :   IN    std_logic_vector(AddrWidth - 1 DOWNTO 0);  -- generic width
        we                                :   IN    std_logic;  -- ufix1
        dout                              :   OUT   std_logic_vector(DataWidth - 1 DOWNTO 0)  -- generic width
        );
END amc_cnn_16w16a_src_SinglePortRAM_generic_block2;


ARCHITECTURE rtl OF amc_cnn_16w16a_src_SinglePortRAM_generic_block2 IS

  -- Local Type Definitions
  TYPE ram_type IS ARRAY (2**AddrWidth - 1 DOWNTO 0) of std_logic_vector(DataWidth - 1 DOWNTO 0);

  -- Signals
  SIGNAL ram                              : ram_type := (X"fbfe", X"2e1c", X"c17a", X"d690", X"0074", X"3470", X"4b9b", X"c7b3", X"25f1", X"126f", X"c83f", X"c996", X"f142", X"f984",
                                                        X"741f", X"cbd7", X"ec19", X"0337", X"1f95", X"6a6a", X"c567", X"ffdb", X"e225", X"e726", X"bf72", X"190a", X"9c54", X"65be",
                                                        X"e29d", X"123b", X"27ca", X"74ec", X"45ba", X"1d70", X"d7a7", X"d314", X"cdd5", X"dd19", X"11a9", X"a650", X"ca89", X"7f8a",
                                                        X"bb31", X"036f", X"ae2e", X"5b7f", X"c07c", X"ac9b", X"ce7c", X"d89d", X"53ae", X"974b", X"676a", X"bea9", X"c547", X"c9bc",
                                                        X"ea77", X"54b2", X"f474", X"e7a3", X"e67f", X"fd1d", X"cd72", X"d452", X"ae84", X"45fd", X"c883", X"4e53", X"e7e7", X"ad06",
                                                        X"0ba8", X"bd3c", X"46fc", X"a8f1", X"ba35", X"11bb", X"a995", X"dad4", X"c169", X"2a55", X"af0a", X"4c83", X"b83a", X"bd0c",
                                                        X"bf20", X"faf3", X"00d9", X"da97", X"cf04", X"e358", X"a474", X"bcf5", X"e34e", X"023b", X"ed12", X"fab1", X"f7a5", X"0000",
                                                        X"b551", X"ffb0", X"a2bb", X"d664", X"f158", X"0a05", X"efcf", X"3495", X"d8dc", X"fe5d", X"129c", X"22f5", X"e992", X"9dcc",
                                                        X"dd01", X"4328", X"a7ba", X"7d1c", X"d3ed", X"3faf", X"d6e8", X"8966", X"de0c", X"fce8", X"dce3", X"b047", X"e5e2", X"c484",
                                                        X"c01a", X"bbb8");
  SIGNAL data_int                         : std_logic_vector(DataWidth - 1 DOWNTO 0) := X"bbb8";
  SIGNAL addr_unsigned                    : unsigned(AddrWidth - 1 DOWNTO 0);  -- generic width

BEGIN
  addr_unsigned <= unsigned(addr);

  SinglePortRAM_generic_process: PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF enb = '1' THEN
        IF we = '1' THEN
          ram(to_integer(addr_unsigned)) <= din;
          data_int <= din;
        ELSE
          data_int <= ram(to_integer(addr_unsigned));
        END IF;
      END IF;
    END IF;
  END PROCESS SinglePortRAM_generic_process;

  dout <= data_int;

END rtl;

