-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj_dma/hdlsrc/ltehdlCNN_AMC/amc_cnn_dma_src_Dense_Layer_2_block.vhd
-- Created: 2023-02-01 23:11:33
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: amc_cnn_dma_src_Dense_Layer_2_block
-- Source Path: ltehdlCNN_AMC/DUT HDL/Dense Layer 2
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.amc_cnn_dma_src_DUT_HDL_pkg.ALL;

ENTITY amc_cnn_dma_src_Dense_Layer_2_block IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        dataIn                            :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En10
        validIn                           :   IN    std_logic;
        dataOut                           :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En11
        validOut                          :   OUT   std_logic
        );
END amc_cnn_dma_src_Dense_Layer_2_block;


ARCHITECTURE rtl OF amc_cnn_dma_src_Dense_Layer_2_block IS

  -- Component Declarations
  COMPONENT amc_cnn_dma_src_Dense_Layer_2
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          dataIn                          :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En10
          validIn                         :   IN    std_logic;
          dataOut                         :   OUT   vector_of_std_logic_vector18(0 TO 7);  -- sfix18_En11 [8]
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT amc_cnn_dma_src_Output_Buffer3
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          vectorIn                        :   IN    vector_of_std_logic_vector18(0 TO 7);  -- sfix18_En11 [8]
          validIn                         :   IN    std_logic;
          samplesOut                      :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En11
          validOut                        :   OUT   std_logic;
          done                            :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT amc_cnn_dma_src_bias4_add
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          sampleIn                        :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En11
          validIn                         :   IN    std_logic;
          out_nT                          :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En11
          samplesOut                      :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En11
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : amc_cnn_dma_src_Dense_Layer_2
    USE ENTITY work.amc_cnn_dma_src_Dense_Layer_2(rtl);

  FOR ALL : amc_cnn_dma_src_Output_Buffer3
    USE ENTITY work.amc_cnn_dma_src_Output_Buffer3(rtl);

  FOR ALL : amc_cnn_dma_src_bias4_add
    USE ENTITY work.amc_cnn_dma_src_bias4_add(rtl);

  -- Signals
  SIGNAL samplesOut                       : vector_of_std_logic_vector18(0 TO 7);  -- ufix18 [8]
  SIGNAL validOut_l4                      : std_logic;
  SIGNAL samplesOut_1                     : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL validOut_1                       : std_logic;
  SIGNAL done                             : std_logic;
  SIGNAL samplesOut_signed                : signed(17 DOWNTO 0);  -- sfix18_En11
  SIGNAL Pipeline_Delay7_out1             : signed(17 DOWNTO 0);  -- sfix18_En11
  SIGNAL Pipeline_Delay8_out1             : std_logic;
  SIGNAL Constant_out1                    : signed(17 DOWNTO 0);  -- sfix18_En11
  SIGNAL samplesOut_2                     : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL validOut_2                       : std_logic;
  SIGNAL samplesOut_signed_1              : signed(17 DOWNTO 0);  -- sfix18_En11
  SIGNAL Pipeline_Delay13_out1            : signed(17 DOWNTO 0);  -- sfix18_En11
  SIGNAL Pipeline_Delay14_out1            : std_logic;

BEGIN
  u_Dense_Layer_2 : amc_cnn_dma_src_Dense_Layer_2
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dataIn => dataIn,  -- sfix18_En10
              validIn => validIn,
              dataOut => samplesOut,  -- sfix18_En11 [8]
              validOut => validOut_l4
              );

  u_Output_Buffer3 : amc_cnn_dma_src_Output_Buffer3
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              vectorIn => samplesOut,  -- sfix18_En11 [8]
              validIn => validOut_l4,
              samplesOut => samplesOut_1,  -- sfix18_En11
              validOut => validOut_1,
              done => done
              );

  u_bias4_add : amc_cnn_dma_src_bias4_add
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              sampleIn => std_logic_vector(Pipeline_Delay7_out1),  -- sfix18_En11
              validIn => Pipeline_Delay8_out1,
              out_nT => std_logic_vector(Constant_out1),  -- sfix18_En11
              samplesOut => samplesOut_2,  -- sfix18_En11
              validOut => validOut_2
              );

  samplesOut_signed <= signed(samplesOut_1);

  Pipeline_Delay7_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Pipeline_Delay7_out1 <= to_signed(16#00000#, 18);
      ELSIF enb = '1' THEN
        Pipeline_Delay7_out1 <= samplesOut_signed;
      END IF;
    END IF;
  END PROCESS Pipeline_Delay7_process;


  Pipeline_Delay8_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Pipeline_Delay8_out1 <= '0';
      ELSIF enb = '1' THEN
        Pipeline_Delay8_out1 <= validOut_1;
      END IF;
    END IF;
  END PROCESS Pipeline_Delay8_process;


  Constant_out1 <= to_signed(-16#0CC40#, 18);

  samplesOut_signed_1 <= signed(samplesOut_2);

  Pipeline_Delay13_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Pipeline_Delay13_out1 <= to_signed(16#00000#, 18);
      ELSIF enb = '1' THEN
        Pipeline_Delay13_out1 <= samplesOut_signed_1;
      END IF;
    END IF;
  END PROCESS Pipeline_Delay13_process;


  dataOut <= std_logic_vector(Pipeline_Delay13_out1);

  Pipeline_Delay14_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Pipeline_Delay14_out1 <= '0';
      ELSIF enb = '1' THEN
        Pipeline_Delay14_out1 <= validOut_2;
      END IF;
    END IF;
  END PROCESS Pipeline_Delay14_process;


  validOut <= Pipeline_Delay14_out1;

END rtl;

