-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/amc_model_w16a16/amc_cnn_16w16a_src_SinglePortRAM_generic_block410.vhd
-- Created: 2023-07-03 13:16:57
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: amc_cnn_16w16a_src_SinglePortRAM_generic_block410
-- Source Path: amc_model_w16a16/DUT HDL/Dense Layer 1/Dense Layer 1/Weight Storage57/SinglePortRAM_generic
-- Hierarchy Level: 4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY amc_cnn_16w16a_src_SinglePortRAM_generic_block410 IS
  GENERIC( AddrWidth                      : integer := 1;
           DataWidth                      : integer := 1
           );
  PORT( clk                               :   IN    std_logic;
        enb                               :   IN    std_logic;
        din                               :   IN    std_logic_vector(DataWidth - 1 DOWNTO 0);  -- generic width
        addr                              :   IN    std_logic_vector(AddrWidth - 1 DOWNTO 0);  -- generic width
        we                                :   IN    std_logic;  -- ufix1
        dout                              :   OUT   std_logic_vector(DataWidth - 1 DOWNTO 0)  -- generic width
        );
END amc_cnn_16w16a_src_SinglePortRAM_generic_block410;


ARCHITECTURE rtl OF amc_cnn_16w16a_src_SinglePortRAM_generic_block410 IS

  -- Local Type Definitions
  TYPE ram_type IS ARRAY (2**AddrWidth - 1 DOWNTO 0) of std_logic_vector(DataWidth - 1 DOWNTO 0);

  -- Signals
  SIGNAL ram                              : ram_type := (X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"19e3", X"07cb", X"05e8", X"2e7a", X"1357", X"1c8e",
                                                        X"1686", X"fb76", X"f447", X"1899", X"fc65", X"b5df", X"2a4f", X"ce96", X"ed0d", X"d8af", X"0337", X"ef28", X"f9c0", X"ffdd",
                                                        X"f00d", X"0966", X"0146", X"13ee", X"1541", X"03fa", X"0796", X"15d6", X"d843", X"ff35", X"fed0", X"f833", X"ff72", X"095c",
                                                        X"f4f8", X"ef18", X"f6fd", X"0f29", X"ed4f", X"f8a4", X"edb3", X"d5e4", X"ee52", X"38e7", X"09c8", X"1c01", X"f787", X"e976",
                                                        X"15d7", X"0720", X"f1db", X"094a", X"0d65", X"eb19", X"f016", X"00d5", X"0527", X"edc5", X"fa6d", X"31bb", X"1747", X"2d89",
                                                        X"0135", X"f18a", X"e6ea", X"f936", X"ef64", X"196e", X"1a12", X"ef87", X"efc3", X"e330", X"fc50", X"eec7", X"1557", X"2dab",
                                                        X"eea3", X"faca", X"0146", X"e8e9", X"e759", X"14ed", X"f456", X"db23", X"1ecb", X"11cd", X"0b30", X"107d", X"e6e0", X"f437",
                                                        X"f1da", X"0aa3", X"de10", X"10ce", X"ec69", X"02f2", X"1a7f", X"0557", X"f4e9", X"229b", X"0e0e", X"ff08", X"f8d5", X"033e",
                                                        X"f243", X"f345", X"ed52", X"201a", X"1189", X"03cc", X"f227", X"e8ef", X"ebf2", X"0cfd", X"f7f1", X"281c", X"ffa7", X"1930",
                                                        X"0ad4", X"f288", X"10d5", X"059c", X"00dc", X"f10e", X"f98e", X"deb9", X"fde3", X"de4a", X"12d9", X"fe0c", X"fa2b", X"299e",
                                                        X"f96a", X"2ac3", X"1c0f", X"083c", X"ea62", X"e5ae", X"0bb4", X"d5c7", X"0fe1", X"01d3", X"ec49", X"f1f9", X"20f8", X"f018",
                                                        X"f44b", X"1995", X"0c85", X"0306", X"efd3", X"faad", X"e055", X"f56d", X"0914", X"0515", X"07f1", X"ef99", X"f311", X"fd34",
                                                        X"e8df", X"04bb", X"f7e5", X"04b1", X"1d46", X"ec0a", X"0146", X"f298", X"203e", X"0537", X"f055", X"edf4", X"093c", X"1aa1",
                                                        X"04f0", X"02d7", X"1921", X"0a4d", X"ef81", X"0724", X"e755", X"f040", X"f7d2", X"f9ab", X"feb8", X"f562", X"09e9", X"3751",
                                                        X"0046", X"1213", X"f7cf", X"178a", X"d592", X"fb0f", X"f85b", X"1db4", X"f6da", X"0125", X"f1e7", X"f7c2", X"04bd", X"f79b",
                                                        X"f5db", X"0c60", X"e28d", X"204c", X"f252", X"f5d7", X"1d7d", X"1432", X"f462", X"014c", X"0224", X"0d48", X"04be", X"efff",
                                                        X"1704", X"ec96", X"f1fa", X"362b", X"d4b7", X"1fd7", X"fefd", X"03a4", X"1080", X"fdbf", X"075a", X"d7aa", X"0eb8", X"1676",
                                                        X"077b", X"e931", X"1e89", X"e5b5", X"07f3", X"0043", X"22f3", X"0862", X"f8ef", X"0b80", X"1f2e", X"01db", X"f7e6", X"f08b",
                                                        X"0ef2", X"fa0c", X"1484", X"ebda", X"f9b1", X"f414", X"f50c", X"ee70", X"f00d", X"d636", X"f473", X"f2d2", X"1d78", X"1bb9",
                                                        X"f1a9", X"32c9", X"18c2", X"1dab", X"1264", X"fd02", X"24ea", X"fe56", X"f4dc", X"d705", X"f833", X"e8fa", X"f2c2", X"eab8",
                                                        X"355c", X"0fbf", X"eef1", X"e6df", X"063e", X"f88c", X"1086", X"1afb", X"d7d2", X"10ab", X"f4c6", X"eca8", X"f941", X"e442",
                                                        X"fd95", X"f5f1", X"f0d9", X"e856", X"f213", X"0cff", X"0591", X"23c7", X"014d", X"05d9", X"052f", X"e6c3", X"053a", X"179c",
                                                        X"06a1", X"02a6", X"f34c", X"e34d", X"f8eb", X"fc8a", X"e9e5", X"fe09", X"f69d", X"f1d5", X"f0fb", X"deb7", X"1150", X"e403",
                                                        X"fcb7", X"2f08", X"f105", X"0c54", X"f8ab", X"df05", X"0ea1", X"0ba3", X"fe47", X"f055", X"f517", X"1850", X"ff32", X"e008",
                                                        X"1db6", X"f1b5", X"f1dc", X"2fb8", X"e109", X"221f", X"028d", X"0aa9", X"f176", X"0be4", X"ff4f", X"1ac8", X"1489", X"ec70",
                                                        X"152c", X"10a6", X"da8f", X"ff8c", X"05cf", X"202d", X"1e3f", X"1e80", X"f83b", X"ee99", X"0b35", X"fc22", X"fb0b", X"1880",
                                                        X"f46a", X"0305", X"ff29", X"eb23", X"f8b4", X"f0d2", X"e340", X"ee07", X"ec2b", X"f52f", X"f0e9", X"036f", X"e66c", X"f9d0",
                                                        X"f938", X"f4c1", X"27e1", X"2359", X"f68a", X"044e", X"e84a", X"06c1", X"f897", X"e993", X"de4e", X"fc4d", X"f149", X"ef74",
                                                        X"fc8f", X"0f82", X"eed4", X"288b", X"f8bd", X"1d52", X"126b", X"10c7", X"1489", X"01fc", X"f337", X"e246", X"1000", X"de0a",
                                                        X"ef71", X"e71c", X"f527", X"fb74", X"f277", X"dd57", X"fc10", X"06e7", X"050c", X"e5ff", X"0dd6", X"f805", X"f1eb", X"deb7",
                                                        X"04e6", X"dacf", X"f67e", X"04f8", X"20f2", X"feb1", X"fc71", X"2949", X"f4d9", X"ef95", X"051c", X"f23e", X"d9bf", X"0fc6",
                                                        X"01d0", X"0348", X"18c6", X"f63c", X"fa71", X"0ea3", X"1e3d", X"eb20", X"13db", X"d0de", X"14fd", X"07af", X"f37e", X"0a04",
                                                        X"e35f", X"172d", X"09f9", X"1dd9", X"1845", X"38f6", X"0782", X"dfe6", X"e8ed", X"fbf8", X"00f3", X"d4ff", X"fa0b", X"fa07",
                                                        X"f2c9", X"11b0", X"17c4", X"e4c4", X"ff33", X"2db8", X"f34f", X"1b93", X"f908", X"00be", X"f69b", X"f3a7", X"fd1d", X"07e4",
                                                        X"f016", X"0164", X"0330", X"14eb", X"0e18", X"f763", X"fe03", X"10ee", X"1014", X"3516", X"0325", X"dc9c", X"1c3e", X"0b87",
                                                        X"e8f3", X"f752", X"08ab", X"0ac2", X"f185", X"e736", X"d2e3", X"12d4", X"ee50", X"fc0a", X"0f8a", X"fda7", X"ebcc", X"0444",
                                                        X"100d", X"0cc4", X"02ae", X"0e5f", X"291f", X"ee81", X"1baf", X"e948", X"e7cd", X"f6e8", X"f6b3", X"fc1a", X"ffaa", X"dd3c",
                                                        X"02ca", X"04f8", X"10ce", X"06de", X"022f", X"1075", X"13c4", X"2ad3", X"01d1", X"e960", X"fc85", X"eed9", X"e25e", X"e533",
                                                        X"f0d2", X"c005", X"f387", X"ef9d", X"10c9", X"1b51", X"e79b", X"f9d9", X"0b2e", X"0ec3", X"0a8a", X"e9ba", X"2663", X"faec",
                                                        X"ef8e", X"dd05", X"ed8b", X"f86c", X"0aa0", X"08e6", X"118e", X"0ae1", X"f548", X"ddf9", X"1f26", X"17c5", X"0156", X"f65d",
                                                        X"1b46", X"fb8f", X"0787", X"f875", X"0417", X"13b5", X"117f", X"fd94", X"1574", X"00fb", X"fe6c", X"d768", X"fb27", X"14a4",
                                                        X"fa75", X"f6d7", X"289b", X"0ffb", X"043c", X"2287", X"e56b", X"1cc9", X"fb5f", X"f62b", X"0d3a", X"0288", X"f5cd", X"0491",
                                                        X"ebd6", X"e6b5", X"0315", X"ee8d", X"2798", X"0846", X"fbbe", X"2e62", X"ee7e", X"1669", X"fbf8", X"f13a", X"022b", X"f56c",
                                                        X"13e5", X"0c05", X"0f55", X"0f12", X"fe9e", X"0370", X"d69e", X"ec71", X"fe1f", X"3686", X"ec31", X"143e", X"01e7", X"f8f7",
                                                        X"f294", X"f7a4", X"0a19", X"2161", X"0225", X"02f1", X"e495", X"f877", X"e28e", X"f8ed", X"f02f", X"1736", X"02c5", X"171a",
                                                        X"fc06", X"e420", X"f546", X"f808", X"e039", X"df9a", X"ff38", X"20f6", X"0b4d", X"06ba", X"21b5", X"ec2e", X"03ef", X"dbf0",
                                                        X"1859", X"e57f", X"02cf", X"07de", X"0234", X"fc35", X"ef6a", X"1aed", X"273d", X"1603", X"0675", X"f644", X"21c7", X"f23b",
                                                        X"0391", X"e776", X"0f93", X"eac2", X"ef20", X"e367", X"fbc1", X"1f4e", X"f78f", X"fca6", X"1f26", X"1c64", X"ec67", X"04b0",
                                                        X"1257", X"139d", X"04be", X"e6a4", X"0d7d", X"dfbd", X"f90b", X"0950", X"0068", X"1fd9", X"ea71", X"df2d", X"fb34", X"1172",
                                                        X"027c", X"f92a", X"f337", X"14c9", X"f2e5", X"f4c4", X"0c66", X"1929", X"00b0", X"ff09", X"0757", X"f78b", X"fe29", X"eba8",
                                                        X"e63e", X"fe30", X"003d", X"ea7e", X"f4a7", X"022b", X"f60e", X"3482", X"ffe7", X"1452", X"fc02", X"e4c1", X"f36f", X"dfda",
                                                        X"f104", X"2567", X"ed18", X"fe66", X"f958", X"f7c4", X"e6c8", X"fcc8", X"f1fe", X"22ca", X"02d5", X"3406", X"f806", X"e9db",
                                                        X"fbd1", X"f64d", X"0038", X"090b", X"0a82", X"03fd", X"fe24", X"0f00", X"0efc", X"eb55", X"0643", X"15ad", X"0c55", X"1485",
                                                        X"f10f", X"f457", X"f92f", X"f212", X"f290", X"f571", X"0585", X"ecde", X"0da7", X"010b", X"edd2", X"fc61", X"05bc", X"049b",
                                                        X"0fae", X"232f", X"0281", X"e954", X"fa6b", X"f030", X"0438", X"f083", X"0997", X"1c34", X"ff43", X"e64c", X"23e0", X"1ebf",
                                                        X"f67c", X"0437", X"f398", X"f4d7", X"febf", X"052a", X"011b", X"f820", X"f8b3", X"f6ff", X"1265", X"0635", X"f6f9", X"14a3",
                                                        X"f145", X"ed0f", X"0422", X"e474", X"2333", X"e681", X"e890", X"fbd2", X"0aba", X"188c", X"f15a", X"225f", X"0840", X"1cd0",
                                                        X"10a7", X"fdc2", X"eb87", X"ebf7", X"ff26", X"df54", X"0154", X"dc6e", X"e6fa", X"ef3c", X"2030", X"1d11", X"eca7", X"26db",
                                                        X"f7bc", X"15d9", X"07d6", X"ea76", X"e23c", X"008a", X"0047", X"0761", X"0233", X"ed93", X"fc08", X"0275", X"ff6b", X"fe8c",
                                                        X"0e01", X"2381", X"0fce", X"ff17", X"fc26", X"fb5b", X"11b3", X"10a9", X"f0d3", X"f6c0", X"032a", X"02e8", X"f8cd", X"0154",
                                                        X"df5f", X"087a", X"0c3a", X"dad7", X"01ee", X"f7ec", X"0bca", X"f00b", X"0448", X"ec38", X"eec0", X"2dd3", X"1f5e", X"173b",
                                                        X"f567", X"dd7b", X"de58", X"fccd", X"1177", X"ff61", X"ec28", X"ef2e", X"f2c8", X"e550", X"0d6d", X"d43c", X"f7e9", X"4315",
                                                        X"ea36", X"1011", X"09d3", X"077a", X"e418", X"f7d8", X"f7a1", X"1052", X"079e", X"145a", X"1236", X"ec30", X"166f", X"fe23",
                                                        X"0629", X"33f7", X"1db8", X"1944", X"fe35", X"f54c", X"f7f1", X"0b4a", X"e296", X"1ff8", X"ec91", X"01a8", X"1724", X"0067",
                                                        X"05ce", X"feff", X"03c0", X"df8a", X"fb7f", X"084f", X"ebe1", X"003e", X"0d11", X"ecc5", X"eddb", X"2035", X"16fa", X"08eb",
                                                        X"0f06", X"0f0f", X"fd03", X"f78f", X"04b7", X"f7f6", X"f94c", X"da38", X"e62b", X"ff70", X"f316", X"fd7f", X"eb8e", X"0917",
                                                        X"1dca", X"f84c", X"f5da", X"e648", X"1724", X"0521", X"f412", X"ea40", X"0215", X"de26", X"f719", X"e80d", X"16a7", X"043f",
                                                        X"ed08", X"131e", X"065d", X"2973", X"ff76", X"091a", X"158d", X"eb34", X"fc6b", X"de6e", X"0781", X"ef17", X"fcf0", X"f0b5",
                                                        X"ec60", X"fa76", X"fcbd", X"fdc7", X"0c84", X"0e98", X"f5af", X"fcf7", X"1570", X"1244", X"e756", X"fc20", X"0a53", X"0841",
                                                        X"e968", X"df28", X"f94f", X"fc05", X"f2e5", X"ee00", X"0191", X"fa14", X"fda9", X"f5c2", X"eab0", X"1bb1", X"f73e", X"165d",
                                                        X"eb14", X"2bec", X"f6b9", X"f4bd", X"efd3", X"f8e5", X"0156", X"ec59", X"e3dc", X"0ea8", X"f460", X"04d5", X"1439", X"fcdd",
                                                        X"fb0b", X"316d", X"e475", X"12c6", X"f442", X"0478", X"f8bd", X"f8c6", X"128b", X"f04d", X"e56e", X"126d", X"0510", X"00f4",
                                                        X"06c7", X"f5d3", X"ff1f", X"054b", X"19f8", X"17b8", X"05f3", X"f1db", X"ecbf", X"049c", X"faf3", X"dc60", X"f47c", X"0f59",
                                                        X"06d6", X"00f6", X"e9fa", X"182a", X"0d87", X"fab9", X"0175", X"fe3a", X"edb7", X"ea60", X"f85f", X"0760", X"e616", X"dd2f",
                                                        X"07ba", X"144d", X"0576", X"fed6", X"e5a1", X"e5c4", X"f63c", X"0775", X"0151", X"fd23", X"f461", X"0fa1", X"208a", X"f4d1",
                                                        X"f3bb", X"2ac7", X"02b4", X"0fb0", X"03af", X"0a9c", X"0af6", X"f77a", X"e0e0", X"d342", X"1009", X"ce04", X"eff3", X"ea41",
                                                        X"feed", X"07fd", X"e075", X"dd7e", X"1a7b", X"2d29", X"10b3", X"00f7", X"f08a", X"02cd", X"f1ba", X"f62e", X"fb76", X"f24d",
                                                        X"fa64", X"eb6e", X"f795", X"015b", X"f569", X"e58e", X"f658", X"f7f7", X"ed52", X"ed51", X"fba6", X"1617", X"f644", X"107e",
                                                        X"1663", X"045c", X"079a", X"fdff", X"16d9", X"fa83", X"f76e", X"292b", X"1952", X"ef2d", X"ff2b", X"05ae", X"e689", X"e19c",
                                                        X"ff3c", X"2828", X"0e95", X"1b2e", X"fde6", X"fc03", X"0a78", X"0930", X"f3f5", X"f541", X"035d", X"f8ed", X"f6af", X"f1f8",
                                                        X"ee27", X"ef45", X"0645", X"2395", X"fb64", X"2463", X"fb13", X"ca9a", X"f8a5", X"e9d4", X"f1d1", X"fe6c", X"08fa", X"e629",
                                                        X"eea3", X"f58e", X"125e", X"08d3", X"fbb9", X"11cb", X"1308", X"165f", X"0338", X"f22d", X"0dd6", X"f816", X"0187", X"e76c",
                                                        X"e26a", X"f728", X"0594", X"f536", X"1e63", X"f58d", X"f796", X"f707", X"fcd0", X"03c8", X"f319", X"fcce", X"01a7", X"f4ca",
                                                        X"fa81", X"e09b", X"02c3", X"0d49", X"10ea", X"f14f", X"f304", X"033a", X"fe2e", X"153e", X"0d06", X"0caa", X"e956", X"f7dd",
                                                        X"128f", X"ed1f", X"e86a", X"16fb", X"188c", X"2637", X"14cd", X"0b52", X"0709", X"f435", X"ee6a", X"f108", X"114b", X"cf3b",
                                                        X"e620", X"f427", X"07c2", X"f343", X"f06c", X"fffb", X"0251", X"ff6b", X"112c", X"0346", X"dd3c", X"f8a8", X"ebd3", X"cf2e",
                                                        X"e906", X"f2b6", X"f1f7", X"db85", X"f298", X"0b2d", X"ec49", X"1e8b", X"1b9b", X"2315", X"015e", X"f088", X"0f95", X"efc7",
                                                        X"f19d", X"106b", X"04c9", X"0b17", X"f9a9", X"de2b", X"1c9e", X"eec6", X"fea9", X"f848", X"0982", X"19d1", X"f921", X"fd51",
                                                        X"ec17", X"061f", X"ee9c", X"1c7e", X"f788", X"08c3", X"02ec", X"0087", X"eb94", X"0cc1", X"f523", X"0142", X"eb2b", X"11c5",
                                                        X"f36d", X"ec26", X"023b", X"05fd", X"f4be", X"086c", X"e5b4", X"1fa8", X"fa06", X"038d", X"e9ec", X"0022", X"fc3a", X"0970",
                                                        X"e8f0", X"ead1", X"f822", X"e2bd", X"037f", X"0cf8", X"faa7", X"1883", X"2174", X"365f", X"0d73", X"0a67", X"0410", X"edce",
                                                        X"044e", X"eac5", X"ef21", X"fba0", X"f3aa", X"f72a", X"1a7a", X"ef75", X"f822", X"20e2", X"0b7a", X"2f8e", X"0ff0", X"efd6",
                                                        X"f202", X"102a", X"e4a3", X"ea56", X"00c0", X"1694", X"02bf", X"1180", X"0054", X"f46e", X"e6de", X"0e3e", X"0c86", X"f503",
                                                        X"fd73", X"f4b9", X"132e", X"f228", X"e894", X"1ac0", X"1c36", X"21f5", X"0182", X"f803", X"db45", X"f662", X"f0f8", X"e308",
                                                        X"eef4", X"e165", X"fb57", X"f812", X"e9dd", X"e84b", X"f9e4", X"e525", X"06cb", X"27b7", X"10ec", X"f488", X"0c92", X"07bc",
                                                        X"ffdf", X"c68a", X"fcc8", X"d904", X"0396", X"ef21", X"17b0", X"0878", X"ea0e", X"14ff", X"1358", X"2951", X"026a", X"0b33",
                                                        X"f74f", X"0d2c", X"f4b5", X"ec12", X"f752", X"ee8f", X"0164", X"dd5b", X"0dc1", X"fecc", X"e467", X"ddcb", X"101d", X"fac2",
                                                        X"1024", X"ede7", X"fa52", X"fc4c", X"f525", X"fa83", X"e853", X"013a", X"041a", X"06ef", X"f5bb", X"f768", X"f375", X"2402",
                                                        X"da9c", X"16df", X"004a", X"0802", X"1a1c", X"027c", X"0346", X"1adc", X"d7ab", X"1dda", X"00aa", X"0f43", X"ee22", X"fcd9",
                                                        X"19d6", X"1039", X"fefc", X"07bc", X"0833", X"e7c5", X"03f1", X"ec0c", X"f744", X"3583", X"1585", X"3c39", X"0aa7", X"ea59",
                                                        X"d32d", X"e692", X"efe5", X"f1ee", X"04ea", X"f572", X"f516", X"141d", X"0c65", X"0c40", X"fa01", X"29b1", X"fb8d", X"05e5",
                                                        X"09d1", X"064a", X"172d", X"07d7", X"fdaa", X"15bb", X"0c44", X"1aa7", X"02e9", X"0623", X"fa02", X"f9d1", X"f441", X"fbc7",
                                                        X"09e8", X"01ab", X"f21c", X"ebea", X"fd0f", X"0330", X"f94e", X"1ea2", X"0580", X"1cd6", X"153e", X"0264", X"e176", X"f209",
                                                        X"0212", X"0755", X"1589", X"ec55", X"ede1", X"d335", X"23fe", X"0a24", X"e067", X"fff8", X"1564", X"2fa1", X"f252", X"e5dc",
                                                        X"03ce", X"f776", X"f52b", X"f030", X"134f", X"dcbe", X"f373", X"e809", X"3260", X"0528", X"fe4b", X"2aad", X"07fd", X"373d",
                                                        X"0219", X"f10e", X"ea3f", X"154b", X"008f", X"ef04", X"14aa", X"ec11", X"f78d", X"eae7", X"e757", X"f2d2", X"0999", X"271a",
                                                        X"26a7", X"f519", X"0252", X"f891", X"188a", X"e9ba", X"06ca", X"0b9c", X"15b1", X"0a50", X"facd", X"eaf5", X"f950", X"02b0",
                                                        X"f533", X"0fa0", X"1038", X"fd57", X"f544", X"f1d0", X"2785", X"e198", X"0394", X"1db3", X"dbe8", X"0e72", X"0d44", X"0457",
                                                        X"e380", X"fd3c", X"ffa5", X"326c", X"11fc", X"dffc", X"f917", X"0455", X"162a", X"f6ed", X"0ae7", X"1cae", X"1ad2", X"434e",
                                                        X"0c26", X"0444", X"fe33", X"f700", X"f217", X"1a48", X"ff62", X"ffb2", X"0101", X"095b", X"d9a9", X"1871", X"edd2", X"1385",
                                                        X"e8bf", X"22ed", X"f58c", X"f359", X"eb72", X"f8c8", X"ec43", X"fba5", X"206b", X"e8d0", X"03a4", X"fc7d", X"0214", X"f003",
                                                        X"e371", X"0c3a", X"1f80", X"0783", X"0ce2", X"1078", X"08cd", X"0197", X"fbf7", X"242f", X"2a05", X"2c19", X"1cd8", X"e77d",
                                                        X"0d8f", X"087e", X"f0cb", X"036f", X"f622", X"f15e", X"fc6a", X"f766", X"29cb", X"00b2", X"f10a", X"f1aa", X"fe2f", X"287a",
                                                        X"0084", X"0473", X"fe64", X"0c63", X"0f61", X"e208", X"25c9", X"d24e", X"0b54", X"d3e0", X"eca8", X"f3d6", X"ff91", X"ec80",
                                                        X"f473", X"2dd8", X"1ce3", X"0842", X"f8ad", X"ff4d", X"015f", X"eb5b", X"e94f", X"e78d", X"041a", X"fad5", X"17f8", X"0f91",
                                                        X"ffde", X"32a8", X"1dc9", X"07be", X"fff1", X"04a9", X"0cb9", X"ee96", X"ea6c", X"0977", X"02af", X"0f1b", X"0579", X"d568",
                                                        X"16e8", X"f40e", X"fb02", X"f357", X"f325", X"0ab4", X"e7fe", X"dc5e", X"1bec", X"0235", X"f87e", X"0d1b", X"164f", X"1797",
                                                        X"f8c6", X"ed1b", X"fffa", X"faf3", X"f39c", X"1245", X"01ab", X"e533", X"dea4", X"054a", X"df5b", X"fb9b", X"fe53", X"1a2d",
                                                        X"f673", X"0afd", X"0889", X"12a0", X"fa44", X"08dd", X"fd0d", X"0c45", X"0444", X"e366", X"ffe2", X"1731", X"e21f", X"1005",
                                                        X"f6ce", X"24db", X"17f5", X"1b8e", X"ffb7", X"0cee", X"0ae4", X"fcf0", X"0de8", X"1119", X"2043", X"04f3", X"00ae", X"eb72",
                                                        X"f12a", X"e536", X"f7a8", X"14a5", X"0388", X"0be5", X"f01c", X"e4d7", X"02cc", X"0d86", X"03d1", X"1acd", X"fdab", X"0950",
                                                        X"fed4", X"fe98", X"eb50", X"f2a3", X"f38d", X"de41", X"f0ab", X"eb07", X"0585", X"091a", X"06f5", X"1186", X"e57f", X"2638",
                                                        X"0605", X"06d8", X"0171", X"e2e5", X"ee69", X"faa2", X"09e7", X"fdea", X"23e3", X"d3ac", X"f637", X"e67a", X"fefc", X"14ee",
                                                        X"02aa", X"eb40", X"2b17", X"2401", X"1856", X"077a", X"1cfd", X"eb4f", X"ff83", X"ef4b", X"2473", X"dae4", X"f31d", X"dfec",
                                                        X"1700", X"e334", X"ed79", X"13fa", X"1d62", X"1e77", X"f453", X"f817", X"03f6", X"f52a", X"fa76", X"fe73", X"e6af", X"00be",
                                                        X"fc60", X"075b", X"f1c4", X"fb2f", X"09fc", X"17fe", X"01c9", X"f4b6", X"12a3", X"df89", X"f8dd", X"fcab", X"0c45", X"20eb",
                                                        X"e66a", X"0712", X"eeca", X"f4c3", X"ef2b", X"eb01", X"e855", X"d81e", X"ee67", X"fb0d", X"00ef", X"1223", X"126d", X"0c1c",
                                                        X"ff1e", X"14ec", X"14a7", X"121f", X"037f", X"e68b", X"0340", X"08ea", X"ff23", X"1d9a", X"f923", X"0329", X"fa7f", X"0ae1",
                                                        X"1586", X"fea9", X"075f", X"3742", X"0eb1", X"1de2", X"f16b", X"fb94", X"f8ae", X"fa78", X"0141", X"0231", X"f122", X"fd3f",
                                                        X"05cb", X"03eb", X"e7dd", X"0486", X"0750", X"1403", X"e641", X"1c2c", X"f377", X"dd10", X"1b21", X"04a2", X"04fd", X"11e9",
                                                        X"0c4d", X"00e4", X"ffd4", X"f77b", X"e726", X"12a1", X"007b", X"dfb3", X"dc16", X"f443", X"f57a", X"dd23", X"2151", X"13be",
                                                        X"00b2", X"1f57", X"20e1", X"1fb1", X"f5c4", X"00bc", X"0a1f", X"f02b", X"0ce6", X"0882", X"0e2a", X"ee9c", X"fb7c", X"ea47",
                                                        X"1213", X"f3c2", X"e0e7", X"f2d5", X"1aea", X"28c2", X"0e45", X"f222", X"f212", X"0a6d", X"f7d3", X"f780", X"fa0a", X"d5e6",
                                                        X"f101", X"ee07", X"f965", X"077b", X"f242", X"e874", X"fefd", X"0abe", X"fda1", X"1466", X"f465", X"ec1c", X"f64b", X"fc8f",
                                                        X"14ec", X"f492", X"f8ef", X"e42b", X"f63a", X"f3e4", X"fcb5", X"136f", X"f51e", X"0b73", X"f9e2", X"f1c5", X"1f75", X"0c75",
                                                        X"fcc6", X"f29e", X"0d73", X"faaa", X"e9ac", X"fb6f", X"fa52", X"f6c8", X"e360", X"01a6", X"fc4f", X"0553", X"0887", X"039e",
                                                        X"d4d6", X"e22e", X"fb13", X"2ec4", X"1ba6", X"230f", X"01d1", X"f904", X"0a55", X"fd89", X"eae8", X"1521", X"eed2", X"f7f1",
                                                        X"06db", X"fae4", X"1452", X"00f5", X"0937", X"2982", X"100e", X"2857", X"0303", X"def3", X"0dcb", X"f3eb", X"09eb", X"f7af",
                                                        X"ef46", X"eb53", X"1258", X"f295", X"2361", X"0352", X"010e", X"105d", X"ebfe", X"1533", X"fde9", X"fc51", X"0a3a", X"1682",
                                                        X"02fd", X"dac2", X"1834", X"1f42", X"f99c", X"ed10", X"f6de", X"0728", X"efdb", X"1ca1", X"fd4c", X"0f96", X"f8f1", X"f9ae",
                                                        X"0866", X"031c", X"ef34", X"e2f9", X"2c2f", X"1e6a", X"ffb0", X"074a", X"0860", X"f74c", X"0f5f", X"f7da", X"fcaf", X"e31b",
                                                        X"f5e1", X"f895", X"20b5", X"1461", X"e9b9", X"1bac", X"0a64", X"0bb9", X"171c", X"0e1e", X"ea7f", X"01d6", X"0cef", X"ca3e",
                                                        X"0530", X"cccd", X"f80b", X"f11b");
  SIGNAL data_int                         : std_logic_vector(DataWidth - 1 DOWNTO 0) := X"f11b";
  SIGNAL addr_unsigned                    : unsigned(AddrWidth - 1 DOWNTO 0);  -- generic width

BEGIN
  addr_unsigned <= unsigned(addr);

  SinglePortRAM_generic_process: PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF enb = '1' THEN
        IF we = '1' THEN
          ram(to_integer(addr_unsigned)) <= din;
          data_int <= din;
        ELSE
          data_int <= ram(to_integer(addr_unsigned));
        END IF;
      END IF;
    END IF;
  END PROCESS SinglePortRAM_generic_process;

  dout <= data_int;

END rtl;

