-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/amc_model_w16a16/amc_cnn_16w16a_src_SinglePortRAM_generic_block383.vhd
-- Created: 2023-07-03 13:16:53
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: amc_cnn_16w16a_src_SinglePortRAM_generic_block383
-- Source Path: amc_model_w16a16/DUT HDL/Dense Layer 1/Dense Layer 1/Weight Storage32/SinglePortRAM_generic
-- Hierarchy Level: 4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY amc_cnn_16w16a_src_SinglePortRAM_generic_block383 IS
  GENERIC( AddrWidth                      : integer := 1;
           DataWidth                      : integer := 1
           );
  PORT( clk                               :   IN    std_logic;
        enb                               :   IN    std_logic;
        din                               :   IN    std_logic_vector(DataWidth - 1 DOWNTO 0);  -- generic width
        addr                              :   IN    std_logic_vector(AddrWidth - 1 DOWNTO 0);  -- generic width
        we                                :   IN    std_logic;  -- ufix1
        dout                              :   OUT   std_logic_vector(DataWidth - 1 DOWNTO 0)  -- generic width
        );
END amc_cnn_16w16a_src_SinglePortRAM_generic_block383;


ARCHITECTURE rtl OF amc_cnn_16w16a_src_SinglePortRAM_generic_block383 IS

  -- Local Type Definitions
  TYPE ram_type IS ARRAY (2**AddrWidth - 1 DOWNTO 0) of std_logic_vector(DataWidth - 1 DOWNTO 0);

  -- Signals
  SIGNAL ram                              : ram_type := (X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"ea17", X"e1d8", X"0676", X"0ebb", X"10d5", X"2357",
                                                        X"e6d5", X"1689", X"e87e", X"db79", X"ff55", X"f283", X"e0e0", X"12bd", X"ecd0", X"06a2", X"e576", X"0959", X"ed13", X"be0a",
                                                        X"137c", X"e43a", X"f25b", X"eb9a", X"e663", X"1107", X"f1db", X"fb3d", X"d116", X"e2be", X"e90c", X"1078", X"06ba", X"0e5c",
                                                        X"14cf", X"e141", X"00b8", X"0c7e", X"13cf", X"08b3", X"14f9", X"0282", X"072e", X"f27e", X"19b3", X"fd4d", X"efa0", X"0046",
                                                        X"f2f2", X"f578", X"e2d1", X"051d", X"f911", X"07c4", X"d438", X"f6ef", X"fc77", X"eff0", X"0482", X"1b69", X"c83a", X"2248",
                                                        X"f4fe", X"e8ba", X"eec5", X"e983", X"0e6b", X"eaec", X"035c", X"e5de", X"0bc7", X"12d9", X"0fef", X"e5e9", X"f196", X"089e",
                                                        X"cd2e", X"ec5c", X"f301", X"13b5", X"e87a", X"0876", X"fee2", X"d0fd", X"0ebd", X"de5c", X"f7dc", X"ed8c", X"dcae", X"e619",
                                                        X"068c", X"e125", X"0895", X"dad6", X"f852", X"eb57", X"fa27", X"1708", X"fe2a", X"d06b", X"f4e9", X"1e1e", X"d763", X"e5b0",
                                                        X"e77d", X"e4dc", X"f688", X"1070", X"dc4a", X"e24f", X"fe63", X"f8ae", X"0013", X"e83b", X"e551", X"1ff7", X"1b6a", X"f23d",
                                                        X"0da2", X"df85", X"e1dc", X"1b2d", X"cf06", X"0522", X"e731", X"f63a", X"11c9", X"140e", X"e57c", X"16c9", X"0189", X"ef5e",
                                                        X"f832", X"e6b2", X"e588", X"0799", X"f30d", X"e970", X"eb9c", X"d8d7", X"dd9e", X"0c76", X"ec22", X"e2df", X"20a8", X"f8c7",
                                                        X"e609", X"d96c", X"ff74", X"041f", X"0323", X"0ece", X"eb45", X"ed4d", X"f564", X"0295", X"1877", X"0a03", X"fbff", X"0f0a",
                                                        X"f447", X"fdde", X"0ce9", X"0eb7", X"2d82", X"f13e", X"1653", X"e6b8", X"14b8", X"f076", X"f1d8", X"1502", X"efdd", X"f4b6",
                                                        X"eead", X"ff09", X"f686", X"10ab", X"ebf6", X"f47e", X"eee9", X"006d", X"0f53", X"f54e", X"f5a2", X"1f02", X"f2be", X"06e5",
                                                        X"fdcc", X"ff4c", X"f0ab", X"0956", X"edad", X"146f", X"fc59", X"fa46", X"1e36", X"ee1c", X"048f", X"0726", X"eadf", X"edbc",
                                                        X"fe77", X"175a", X"f395", X"fbd3", X"fdf0", X"e982", X"1cb9", X"072f", X"01d8", X"0da1", X"0b3c", X"1409", X"191a", X"0b2e",
                                                        X"e751", X"0297", X"04be", X"f211", X"1f38", X"e74f", X"0093", X"e7f7", X"202c", X"02b5", X"efed", X"1f72", X"fd51", X"e253",
                                                        X"dcb3", X"0d97", X"ea7d", X"f5d9", X"d8cf", X"0ad5", X"0c79", X"ff24", X"0a08", X"f1b4", X"014f", X"0f9e", X"05b6", X"eaa9",
                                                        X"10f2", X"0a5b", X"010a", X"088b", X"f563", X"0847", X"0ac5", X"d949", X"0a93", X"147e", X"f42b", X"0d4c", X"f0f4", X"ff3b",
                                                        X"0a50", X"e0ee", X"e083", X"f26f", X"24fa", X"fc83", X"002e", X"0f3b", X"e036", X"017f", X"0085", X"f15a", X"f32b", X"e82c",
                                                        X"e04c", X"dff7", X"0ff6", X"15b2", X"e031", X"1377", X"f209", X"1d52", X"f2e0", X"ffba", X"074b", X"1bc5", X"0cc5", X"01d8",
                                                        X"edde", X"0a46", X"0fc3", X"0ea3", X"119c", X"0cfd", X"237a", X"0184", X"ff5d", X"043c", X"f594", X"e69c", X"0ac3", X"dd80",
                                                        X"d843", X"f963", X"e762", X"e53b", X"1041", X"0050", X"1904", X"017d", X"fd15", X"ddb8", X"f68b", X"07a2", X"0288", X"fe28",
                                                        X"fcd6", X"0004", X"e413", X"ff54", X"f799", X"0328", X"f568", X"ebf8", X"0fb0", X"1bd9", X"0cb5", X"0fe7", X"ec0d", X"ed4a",
                                                        X"0436", X"0f08", X"07fa", X"fed6", X"fb9f", X"0510", X"0caf", X"1015", X"2a18", X"0584", X"2484", X"f370", X"1490", X"1056",
                                                        X"1c97", X"0a59", X"0279", X"fa02", X"1f10", X"142e", X"22ba", X"0bc7", X"f943", X"33bc", X"0f44", X"26cc", X"1870", X"0c4d",
                                                        X"190a", X"1ec1", X"1a4a", X"17da", X"0bd6", X"35a7", X"e6b0", X"0592", X"2e43", X"09cd", X"0310", X"062c", X"397c", X"1e4a",
                                                        X"00e6", X"fecc", X"f817", X"f167", X"f518", X"0554", X"2c98", X"e468", X"0258", X"0a96", X"36e4", X"2db8", X"0404", X"31ab",
                                                        X"fad3", X"3134", X"1f19", X"eb26", X"0f57", X"05a4", X"22ce", X"2e1c", X"f115", X"1814", X"192e", X"00ea", X"3082", X"e381",
                                                        X"0981", X"2616", X"df4b", X"16a9", X"ede9", X"0443", X"fe0c", X"e4a5", X"1cec", X"e277", X"3479", X"f336", X"e6ae", X"1f6c",
                                                        X"02c4", X"0d40", X"122c", X"0e0b", X"fc10", X"062c", X"188f", X"3024", X"0ddf", X"0928", X"021c", X"e880", X"0392", X"1d42",
                                                        X"1692", X"f956", X"f533", X"d8f1", X"1895", X"f3e1", X"eeda", X"ed63", X"ffb8", X"d6c0", X"e97c", X"00ba", X"0f97", X"14f0",
                                                        X"3442", X"1aeb", X"f66f", X"0d37", X"0783", X"1104", X"05fb", X"2492", X"05c0", X"1b3f", X"f207", X"1e10", X"1bb6", X"16fe",
                                                        X"19dd", X"0a8c", X"37d5", X"0677", X"1557", X"fbd6", X"fcc6", X"e725", X"fdb4", X"06f8", X"03c8", X"1530", X"f273", X"2936",
                                                        X"f017", X"1ff7", X"1304", X"0ac6", X"2ef7", X"220e", X"1214", X"ec09", X"19ee", X"0590", X"0a06", X"04fe", X"1db8", X"1e58",
                                                        X"fefd", X"fcb7", X"fa21", X"0657", X"0913", X"fd33", X"02aa", X"0383", X"f928", X"fa32", X"f377", X"263a", X"0369", X"09e1",
                                                        X"2cb3", X"305b", X"0497", X"eac0", X"3e9b", X"354e", X"12d7", X"01a9", X"2549", X"053e", X"252d", X"22d4", X"14f1", X"f25a",
                                                        X"f8fa", X"32b3", X"f2a4", X"05a2", X"15fe", X"e5dd", X"f23e", X"2d7e", X"fc6d", X"e151", X"0af6", X"0aad", X"1cf2", X"11b8",
                                                        X"292a", X"fe25", X"0091", X"109a", X"2c27", X"132f", X"0417", X"2859", X"0261", X"1e77", X"3452", X"183c", X"09ae", X"22bc",
                                                        X"fd74", X"03bd", X"f510", X"01b0", X"09e2", X"0577", X"e1bd", X"09a9", X"ead8", X"ddad", X"206b", X"2708", X"2264", X"2409",
                                                        X"1af1", X"f418", X"0bc7", X"1120", X"d587", X"f78c", X"ffdc", X"0dbc", X"0ad1", X"f239", X"f7d6", X"f212", X"f974", X"0623",
                                                        X"213e", X"f03c", X"eb97", X"f05f", X"eb25", X"f72e", X"0896", X"fc06", X"e102", X"0daf", X"df97", X"ee33", X"eee5", X"f3d3",
                                                        X"e23f", X"e631", X"fea5", X"0e29", X"d2d1", X"09e2", X"0d15", X"e262", X"1802", X"1af2", X"ef11", X"02d1", X"e467", X"02d3",
                                                        X"10d1", X"0dc0", X"f5b6", X"147a", X"01ca", X"d62c", X"ce72", X"e605", X"e9df", X"1a80", X"0881", X"e276", X"e66b", X"fe5c",
                                                        X"1730", X"ecf7", X"23fd", X"f6ed", X"f095", X"0c43", X"f9e2", X"f9e0", X"e5ca", X"ef25", X"fa75", X"dc13", X"096e", X"0c31",
                                                        X"ef80", X"1473", X"d3c9", X"fc05", X"eb21", X"1374", X"f130", X"e7f4", X"e9e4", X"f076", X"fd18", X"f715", X"eb54", X"1834",
                                                        X"d72a", X"06a0", X"fdff", X"e287", X"fae6", X"f2cf", X"febf", X"fd07", X"096b", X"d078", X"d8b6", X"02ea", X"063d", X"df9d",
                                                        X"f0d0", X"04b4", X"d465", X"f17b", X"fae3", X"dbf7", X"efe7", X"f24f", X"f569", X"0ca1", X"002c", X"f5f5", X"fa71", X"132a",
                                                        X"1608", X"093a", X"fb77", X"f55e", X"deeb", X"db45", X"ebac", X"0486", X"c5e1", X"1fd2", X"d96e", X"e2f6", X"ff88", X"0a7e",
                                                        X"144f", X"f6ad", X"d8b6", X"1134", X"1aa7", X"165d", X"1df8", X"1197", X"0b6d", X"e331", X"dabe", X"0f5f", X"fcbe", X"06cb",
                                                        X"d8e1", X"ecc2", X"f69f", X"01ee", X"fc8d", X"fd16", X"eab3", X"ea44", X"1636", X"115b", X"f394", X"09dd", X"f33c", X"0c7d",
                                                        X"1293", X"c80d", X"fe35", X"1314", X"fbd6", X"f9b8", X"d058", X"22bd", X"2951", X"059d", X"d4c3", X"03e5", X"dead", X"0db9",
                                                        X"04bd", X"ff96", X"06da", X"1e41", X"e56d", X"09e3", X"0e90", X"e88a", X"254d", X"e241", X"e5ad", X"dcae", X"129b", X"d224",
                                                        X"e5fd", X"1644", X"d7d5", X"e94d", X"df75", X"ce5d", X"f699", X"01a3", X"1184", X"07a8", X"cc0c", X"f949", X"2718", X"1553",
                                                        X"128e", X"fc36", X"e9fd", X"0d27", X"100e", X"017c", X"f35c", X"f7bb", X"feda", X"0de9", X"183a", X"0062", X"1d3c", X"e92c",
                                                        X"ee56", X"f34b", X"27f0", X"f7ca", X"ffd4", X"f2b9", X"1775", X"0e0d", X"04dd", X"edeb", X"25fc", X"29fd", X"1a24", X"08b3",
                                                        X"f3c4", X"109c", X"0288", X"f93a", X"e9cd", X"292b", X"fd8a", X"0422", X"2375", X"0c3e", X"f8da", X"fb9a", X"1754", X"e96f",
                                                        X"fada", X"e7a3", X"f8c0", X"098a", X"ec9b", X"fba1", X"0e99", X"ff1c", X"0539", X"fbf5", X"deb3", X"203e", X"04cc", X"154b",
                                                        X"eaf2", X"f2ca", X"1e6b", X"0918", X"02c0", X"0ee3", X"ee14", X"278b", X"e05c", X"ea17", X"108d", X"e33f", X"e563", X"fda0",
                                                        X"ebc6", X"2dc9", X"1216", X"0b0f", X"040c", X"0af5", X"11aa", X"ea07", X"0784", X"f719", X"1f74", X"f5e3", X"0b62", X"f1dc",
                                                        X"1591", X"fe6f", X"efb6", X"d707", X"f206", X"f932", X"1530", X"f06b", X"eeb5", X"ff4c", X"22ba", X"1937", X"233b", X"f26a",
                                                        X"da59", X"f512", X"1f4b", X"e6a7", X"1155", X"d382", X"fc1c", X"0596", X"16b4", X"02c1", X"02ed", X"dd94", X"1092", X"10f5",
                                                        X"136e", X"1b98", X"f26c", X"10de", X"15d2", X"1ff6", X"0002", X"01fc", X"e7ac", X"f43b", X"0373", X"dde9", X"0b2e", X"1014",
                                                        X"2471", X"1c36", X"d30b", X"f3b3", X"007a", X"0134", X"0acd", X"e53c", X"f20f", X"138d", X"e137", X"2699", X"e9e7", X"00f1",
                                                        X"11ff", X"0eb6", X"facf", X"d81d", X"0987", X"edb5", X"178b", X"0bf5", X"f037", X"f509", X"175a", X"096b", X"0e28", X"2620",
                                                        X"0492", X"fbbb", X"d5d6", X"f301", X"f645", X"2a8d", X"ccb9", X"0752", X"fb98", X"fe8e", X"e81a", X"1061", X"0907", X"170e",
                                                        X"0a1d", X"1067", X"e21a", X"0095", X"20cb", X"f494", X"ebb8", X"f62d", X"fa12", X"1a21", X"ff24", X"0830", X"db8d", X"f809",
                                                        X"0786", X"232e", X"0e0d", X"264e", X"1aa1", X"064a", X"2256", X"0a2e", X"fbbe", X"fbef", X"ee3a", X"fed2", X"eb2f", X"115a",
                                                        X"1e3e", X"ffb1", X"0f71", X"23be", X"d875", X"fbbe", X"0470", X"eda6", X"d721", X"f042", X"0e07", X"1a06", X"1570", X"fd8b",
                                                        X"fe12", X"edeb", X"0d56", X"e59d", X"dc58", X"12ec", X"dcae", X"e1eb", X"ea85", X"010b", X"18df", X"dfdc", X"1c18", X"fbb1",
                                                        X"e46c", X"0d6d", X"1c90", X"fecc", X"fa2e", X"0123", X"00e2", X"db09", X"e04f", X"155d", X"fbe2", X"e3d3", X"db0c", X"0ed6",
                                                        X"ff54", X"04bb", X"0e89", X"0c46", X"f6bd", X"26d1", X"f235", X"0d75", X"10f9", X"17ff", X"04c4", X"e723", X"1438", X"0467",
                                                        X"0eba", X"ea5f", X"11fe", X"022c", X"0c68", X"1154", X"1237", X"036f", X"e8f2", X"ff52", X"fb8a", X"d9da", X"fd37", X"256c",
                                                        X"fc48", X"f572", X"dbf6", X"f17c", X"1200", X"1d94", X"e0e8", X"07c2", X"eb85", X"10bb", X"1910", X"0acb", X"2535", X"f2bb",
                                                        X"e548", X"ffb2", X"06b7", X"11d2", X"f004", X"143d", X"fc55", X"182e", X"022c", X"077c", X"0595", X"1b63", X"f4c8", X"098c",
                                                        X"0f1d", X"1cce", X"ed6a", X"f53e", X"1544", X"e16a", X"20a3", X"1101", X"f5a5", X"01aa", X"0b66", X"eeb8", X"fcb5", X"ec29",
                                                        X"111c", X"f995", X"1479", X"e650", X"ded3", X"ce0c", X"fb99", X"fbae", X"f05a", X"ff58", X"11a0", X"0861", X"e9b4", X"e880",
                                                        X"09b6", X"f880", X"fda4", X"fee1", X"1271", X"d6ef", X"e8d7", X"f68a", X"0e73", X"0920", X"040d", X"e95e", X"189b", X"fe9c",
                                                        X"1c1e", X"fed2", X"0aea", X"edf8", X"e27f", X"e550", X"031f", X"e66b", X"e703", X"158f", X"ffdc", X"e89d", X"fad9", X"15f6",
                                                        X"fca8", X"1c00", X"2515", X"00c7", X"057e", X"1826", X"f453", X"0672", X"2400", X"118b", X"114f", X"0cc2", X"fa69", X"0512",
                                                        X"2782", X"0a30", X"f485", X"e8b6", X"e2a6", X"07c0", X"f89e", X"20f7", X"f567", X"307c", X"03de", X"0593", X"3406", X"1281",
                                                        X"15d5", X"f7a7", X"e47b", X"f670", X"f0c4", X"e5ab", X"3305", X"fb1d", X"f065", X"211b", X"f27a", X"f9e9", X"2205", X"34ee",
                                                        X"f82b", X"335b", X"0dfb", X"15db", X"f423", X"f2e5", X"01da", X"1de8", X"20ba", X"2d85", X"0bbd", X"1638", X"0e32", X"1193",
                                                        X"050c", X"f404", X"0dc1", X"214a", X"2954", X"feaf", X"17b5", X"07ce", X"e2b7", X"2c4e", X"1836", X"e9f2", X"0f61", X"f935",
                                                        X"f300", X"2954", X"ed85", X"15c7", X"4677", X"f740", X"0cad", X"0037", X"3b0f", X"05d6", X"191b", X"eb95", X"1d95", X"129c",
                                                        X"faa4", X"1870", X"1fc1", X"f6d6", X"24c8", X"ebd4", X"ec35", X"2b9f", X"0e42", X"1399", X"1db4", X"179f", X"24d6", X"174a",
                                                        X"2ac3", X"1fb5", X"ee82", X"2353", X"07c0", X"0e7a", X"f840", X"2392", X"e6bc", X"1f37", X"f7a7", X"1bb8", X"f0c0", X"1550",
                                                        X"05b5", X"0299", X"dc60", X"fa0a", X"00e0", X"ecbe", X"da9d", X"fb36", X"1f91", X"e678", X"fd7c", X"eb21", X"01cf", X"f811",
                                                        X"163d", X"eb25", X"1bce", X"e49c", X"08ef", X"25b7", X"f378", X"1704", X"06fe", X"e81d", X"f021", X"fd75", X"0a09", X"f5d6",
                                                        X"0c98", X"f5fe", X"13b2", X"fbcc", X"0734", X"0b0a", X"e731", X"f4fe", X"f460", X"1cb5", X"08ba", X"ebb4", X"f05f", X"f7b8",
                                                        X"d0c0", X"f68d", X"1a2a", X"fe0e", X"d587", X"f90c", X"fc41", X"0c80", X"dab9", X"eba9", X"f2db", X"de53", X"ee32", X"f844",
                                                        X"0582", X"ef52", X"d32f", X"f30a", X"ed34", X"035d", X"ffc9", X"fd36", X"eede", X"de9a", X"fdaa", X"13bd", X"f533", X"e15a",
                                                        X"091c", X"0295", X"debe", X"dc3c", X"d1e0", X"c609", X"eebc", X"e82e", X"df5e", X"eea8", X"d165", X"e6db", X"d2f7", X"0086",
                                                        X"0713", X"fdf4", X"f98c", X"0280", X"ff49", X"117f", X"dc79", X"cd64", X"fcdb", X"ebf2", X"0d7d", X"dd10", X"fa11", X"d4df",
                                                        X"dac8", X"09a7", X"ef68", X"0727", X"c8ce", X"0238", X"e092", X"12e6", X"ef88", X"db9a", X"f43d", X"044c", X"d075", X"0b63",
                                                        X"eb6d", X"06ec", X"e5fe", X"f9c5", X"0baf", X"d9df", X"fc73", X"fced", X"d76e", X"f671", X"17fa", X"14c4", X"0ccf", X"fd62",
                                                        X"01a9", X"0dc6", X"e435", X"0ad7", X"e861", X"0263", X"14f7", X"052a", X"ece4", X"f426", X"14df", X"e1c1", X"fadd", X"f42a",
                                                        X"1151", X"ed26", X"0942", X"fb80", X"dfdd", X"03c9", X"ffc7", X"0b3e", X"10fd", X"115f", X"e0f1", X"0792", X"eb5c", X"f460",
                                                        X"2c30", X"f2c7", X"e395", X"0c97", X"f0da", X"f579", X"1796", X"1a05", X"f4bf", X"e913", X"fbac", X"f973", X"ffb9", X"2fde",
                                                        X"eaaf", X"16be", X"eb02", X"27fe", X"1abd", X"f964", X"2d29", X"13f5", X"f3f2", X"f06d", X"0ff3", X"1cee", X"0627", X"fb93",
                                                        X"3b99", X"0921", X"f555", X"e552", X"0700", X"3645", X"0976", X"14f6", X"e740", X"13b6", X"2a49", X"1f09", X"1724", X"0ba1",
                                                        X"0d7f", X"0238", X"1a19", X"0b1b", X"fb40", X"e4ba", X"f074", X"008a", X"141e", X"17ee", X"fec0", X"092a", X"1b5e", X"e03a",
                                                        X"393f", X"18eb", X"f596", X"04c7", X"06a0", X"2764", X"fc74", X"ed52", X"f65d", X"30bd", X"f905", X"1ee2", X"eeea", X"10e9",
                                                        X"0a65", X"1871", X"1316", X"d591", X"0647", X"e2f6", X"f1f7", X"e04d", X"0fb7", X"06a2", X"076b", X"2a00", X"ebce", X"17cf",
                                                        X"0e68", X"12db", X"1609", X"2037", X"028f", X"f297", X"fcff", X"f8ac", X"f21b", X"ebe0", X"1694", X"193f", X"097f", X"f8f9",
                                                        X"fc56", X"1272", X"12a5", X"0757", X"2058", X"f518", X"269e", X"e5a7", X"f5bf", X"04b8", X"14bc", X"f80c", X"0dae", X"d890",
                                                        X"00f2", X"f725", X"fc83", X"f0bd", X"ec3a", X"16e3", X"0917", X"f873", X"07b9", X"0b7a", X"f3ce", X"0700", X"f6e8", X"e08e",
                                                        X"fb0b", X"dc37", X"f66f", X"236a", X"1e45", X"143d", X"194c", X"1876", X"e9f8", X"d8e3", X"00b3", X"e6de", X"012d", X"01ab",
                                                        X"e408", X"242c", X"fa00", X"09e1", X"efba", X"18b2", X"309b", X"1b9f", X"07d0", X"ef3a", X"2723", X"07c6", X"180a", X"17a9",
                                                        X"fedc", X"0727", X"0fcc", X"e93a", X"ec14", X"fe3a", X"0c8c", X"fdf4", X"f7b4", X"f7f9", X"df43", X"fa3a", X"e182", X"f946",
                                                        X"0ed7", X"060b", X"fdf6", X"f9df", X"ff3d", X"dd9e", X"17d8", X"06a6", X"fca4", X"1fd5", X"0dae", X"f361", X"272d", X"f1b5",
                                                        X"f46f", X"0834", X"e837", X"fc95", X"f7b4", X"f3a7", X"2bfb", X"31be", X"2256", X"1361", X"05c6", X"2667", X"fc24", X"fc8a",
                                                        X"02c0", X"24ee", X"1927", X"0f8f", X"1122", X"efbc", X"0cea", X"f2a4", X"1fa4", X"fafc", X"f658", X"1f3a", X"1278", X"0dfd",
                                                        X"0a3d", X"f827", X"21a7", X"f12f", X"2ed7", X"1328", X"0b55", X"1b55", X"e7ff", X"efa9", X"fdab", X"0cad", X"f819", X"09d2",
                                                        X"ef80", X"ef3a", X"e9c7", X"0a2d", X"e97d", X"1f5c", X"06b6", X"0a5f", X"d098", X"e607", X"ebce", X"1ce1", X"d772", X"1818",
                                                        X"042c", X"0736", X"1cd3", X"0375", X"e6e8", X"efc9", X"e448", X"ea9d", X"03c8", X"f2cc", X"01ae", X"1dfa", X"f24a", X"f181",
                                                        X"05c3", X"efd3", X"1b76", X"fe68", X"f801", X"0ea7", X"22fb", X"e7c7", X"e023", X"03b8", X"eb67", X"f5ba", X"ca29", X"0741",
                                                        X"1702", X"ff57", X"da19", X"f82a", X"17d6", X"0bab", X"d978", X"e658", X"0d8e", X"fed9", X"e783", X"fe8c", X"f52c", X"1106",
                                                        X"f26a", X"e117", X"0312", X"083c", X"f946", X"082b", X"f4ad", X"d3f0", X"0d59", X"eb8e", X"025e", X"00a5", X"1a13", X"f33f",
                                                        X"f52a", X"e101", X"ea27", X"e9ab", X"fb12", X"f38b", X"f4d4", X"fff8", X"e2b0", X"f921", X"e130", X"f5bb", X"d4d2", X"0437",
                                                        X"d4e9", X"f906", X"13e3", X"0633", X"fd01", X"f993", X"f2e8", X"0af8", X"fdb6", X"faf2", X"fecd", X"ecad", X"ec39", X"d300",
                                                        X"e968", X"11d4", X"db7b", X"00f6", X"ea20", X"e8b9", X"cedf", X"fb47", X"dd5a", X"e63c", X"eb6a", X"dfd0", X"0111", X"d5e5",
                                                        X"f9c1", X"fbdb", X"f063", X"f437", X"e263", X"e95f", X"f1bf", X"ec0b", X"f764", X"f489", X"dfa7", X"ce5d", X"ebf6", X"0d4f",
                                                        X"efa0", X"16bd", X"d349", X"0755", X"e546", X"e804", X"dcf3", X"dec4", X"e63d", X"f13b", X"cd14", X"ecec", X"0256", X"0652",
                                                        X"ea80", X"fdad", X"0a86", X"bce7", X"f719", X"0cac", X"1047", X"043a", X"e02d", X"0f07", X"1013", X"1c35", X"f500", X"f940",
                                                        X"e907", X"06cc", X"f0ed", X"02e0", X"f32a", X"bfce", X"1877", X"0766", X"ef7f", X"1296", X"e094", X"0779", X"e81f", X"f98d",
                                                        X"d23f", X"f606", X"dd9e", X"ea60", X"f452", X"e6b5", X"1044", X"c93c", X"efdd", X"f177", X"f512", X"0f25", X"ea42", X"01ea",
                                                        X"f22a", X"f06a", X"d843", X"1349", X"fddf", X"fccc", X"f153", X"ceae", X"0301", X"ec5f", X"0271", X"018b", X"1989", X"fa48",
                                                        X"0342", X"03ed", X"0f3c", X"1dc2", X"df6a", X"e511", X"edd2", X"fe47", X"0947", X"100f", X"e648", X"c7c1", X"f228", X"e5b8",
                                                        X"0082", X"de49", X"f855", X"dd82", X"e085", X"f43b", X"da61", X"f634", X"04f7", X"e2fc", X"ce5b", X"eba8", X"ebbf", X"0459",
                                                        X"e3ec", X"f947", X"eed8", X"f073", X"ff4d", X"e1bc", X"e4fe", X"0101", X"f5c5", X"060d", X"f94f", X"d581", X"eb0a", X"12d3",
                                                        X"f87e", X"d015", X"0903", X"fcf1", X"f797", X"ff7d", X"1a04", X"13d8", X"0c9c", X"e26e", X"ddb2", X"f618", X"ee12", X"e6f3",
                                                        X"f407", X"f0c8", X"1825", X"e13e", X"0f4a", X"1129", X"f6a6", X"0a44", X"eb14", X"f6da", X"e38f", X"10ec", X"e4ba", X"ea17",
                                                        X"e72a", X"1202", X"0fee", X"1b0b", X"dd00", X"da6e", X"dd37", X"ea4c", X"15c1", X"016c", X"0c44", X"0450", X"f4c2", X"e16f",
                                                        X"0c93", X"f832", X"fc55", X"060b", X"f043", X"fffd", X"e893", X"e3a2", X"f593", X"1046", X"1bf5", X"0729", X"e20f", X"fc4c",
                                                        X"111b", X"fed6", X"e9e7", X"1398", X"0c11", X"f5a0", X"0f45", X"fc13", X"f7ac", X"0fe3", X"2562", X"18d3", X"1405", X"e9d8",
                                                        X"e58a", X"2357", X"ec84", X"e78b", X"f056", X"ffe3", X"f143", X"e5e9", X"1468", X"1813", X"0ab8", X"0389", X"dc2a", X"fc66",
                                                        X"17e4", X"fae3", X"130f", X"0f9c", X"fb38", X"0653", X"2a84", X"0a59", X"f5c9", X"1fcf", X"e765", X"0af3", X"f8f0", X"f1e8",
                                                        X"1f7e", X"2ea8", X"0e53", X"fbcc", X"2dc6", X"fa36", X"333d", X"fe7d", X"ebd2", X"caff", X"fa57", X"04b0", X"1644", X"2595",
                                                        X"f9fb", X"082e", X"22e3", X"ed8a", X"df89", X"2673", X"1265", X"1c32", X"23e7", X"e95a", X"1904", X"d7a4", X"14d1", X"02d9",
                                                        X"3a19", X"fa75", X"1fcf", X"f977", X"2e14", X"28a9", X"2ff1", X"fc98", X"1b44", X"232f", X"ee16", X"1157", X"2857", X"1c5a",
                                                        X"1771", X"2e81", X"33f0", X"3edd", X"fcab", X"2014", X"2c6c", X"1466", X"0bc3", X"1db3", X"1205", X"0163", X"487c", X"17e0",
                                                        X"fc1d", X"1263", X"0cf4", X"2a54");
  SIGNAL data_int                         : std_logic_vector(DataWidth - 1 DOWNTO 0) := X"2a54";
  SIGNAL addr_unsigned                    : unsigned(AddrWidth - 1 DOWNTO 0);  -- generic width

BEGIN
  addr_unsigned <= unsigned(addr);

  SinglePortRAM_generic_process: PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF enb = '1' THEN
        IF we = '1' THEN
          ram(to_integer(addr_unsigned)) <= din;
          data_int <= din;
        ELSE
          data_int <= ram(to_integer(addr_unsigned));
        END IF;
      END IF;
    END IF;
  END PROCESS SinglePortRAM_generic_process;

  dout <= data_int;

END rtl;

