-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/amc_model_w16a16/amc_cnn_16w16a_src_SinglePortRAM_generic_block439.vhd
-- Created: 2023-07-03 13:17:00
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: amc_cnn_16w16a_src_SinglePortRAM_generic_block439
-- Source Path: amc_model_w16a16/DUT HDL/Dense Layer 1/Dense Layer 1/Weight Storage83/SinglePortRAM_generic
-- Hierarchy Level: 4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY amc_cnn_16w16a_src_SinglePortRAM_generic_block439 IS
  GENERIC( AddrWidth                      : integer := 1;
           DataWidth                      : integer := 1
           );
  PORT( clk                               :   IN    std_logic;
        enb                               :   IN    std_logic;
        din                               :   IN    std_logic_vector(DataWidth - 1 DOWNTO 0);  -- generic width
        addr                              :   IN    std_logic_vector(AddrWidth - 1 DOWNTO 0);  -- generic width
        we                                :   IN    std_logic;  -- ufix1
        dout                              :   OUT   std_logic_vector(DataWidth - 1 DOWNTO 0)  -- generic width
        );
END amc_cnn_16w16a_src_SinglePortRAM_generic_block439;


ARCHITECTURE rtl OF amc_cnn_16w16a_src_SinglePortRAM_generic_block439 IS

  -- Local Type Definitions
  TYPE ram_type IS ARRAY (2**AddrWidth - 1 DOWNTO 0) of std_logic_vector(DataWidth - 1 DOWNTO 0);

  -- Signals
  SIGNAL ram                              : ram_type := (X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"f6c3", X"29e2", X"131d", X"f84b", X"f539", X"2344",
                                                        X"0edc", X"06ab", X"f4ed", X"22b8", X"2092", X"098a", X"fc3a", X"ef30", X"ff4d", X"0d4d", X"0b4b", X"1037", X"02cb", X"1b57",
                                                        X"f36a", X"fe89", X"ee9b", X"fb7c", X"ee04", X"1730", X"ff5a", X"21e7", X"f421", X"f8a6", X"0860", X"f325", X"24df", X"f3ec",
                                                        X"0d63", X"14dd", X"ed22", X"053a", X"ef63", X"015e", X"e51a", X"16b0", X"1356", X"2ee9", X"01ab", X"09e9", X"0880", X"03e9",
                                                        X"1ff1", X"f99f", X"1c6c", X"0f02", X"0195", X"1833", X"f150", X"1546", X"1007", X"e05d", X"0fe0", X"10d9", X"1887", X"027f",
                                                        X"ff52", X"fd90", X"f70e", X"ed66", X"f136", X"e5ff", X"fe6c", X"fac3", X"0764", X"fb1c", X"00c4", X"fbed", X"03c7", X"ed02",
                                                        X"01e1", X"eecf", X"0c1c", X"210e", X"f88b", X"087f", X"052e", X"f609", X"0386", X"edfa", X"f70a", X"0d4a", X"dcae", X"02fe",
                                                        X"fd94", X"15cc", X"eb7d", X"f46d", X"f3b5", X"1538", X"113b", X"f079", X"ebb3", X"10f5", X"db14", X"01f1", X"f426", X"0b9b",
                                                        X"f70d", X"1eaf", X"fdd5", X"36c7", X"0bd6", X"e6b2", X"04bc", X"0631", X"ef3f", X"f86d", X"ef2a", X"08eb", X"defc", X"05fc",
                                                        X"f24c", X"fe0e", X"00aa", X"fb50", X"08b6", X"0198", X"1700", X"e0f8", X"0fe3", X"ed74", X"00f5", X"f797", X"f76e", X"09d1",
                                                        X"eb4a", X"e8a4", X"f1d7", X"f826", X"154a", X"1c54", X"f9ff", X"2da4", X"eb37", X"ded6", X"fa76", X"f1e2", X"11e4", X"ea18",
                                                        X"fb9e", X"2439", X"0944", X"0551", X"02e7", X"128d", X"f6ca", X"ff53", X"01d1", X"e46b", X"0b39", X"ded0", X"069e", X"f56e",
                                                        X"01f7", X"0d1a", X"0a6f", X"2511", X"0e65", X"085f", X"f60c", X"15bc", X"f441", X"0d42", X"fa67", X"1cb0", X"05ca", X"dcef",
                                                        X"f6af", X"fe7b", X"f8de", X"0282", X"fdf8", X"e926", X"f857", X"087c", X"fe99", X"e360", X"f48c", X"17ec", X"fa08", X"0e91",
                                                        X"dc2d", X"e8c2", X"fa2f", X"0b7b", X"f966", X"de81", X"f978", X"05aa", X"ef7a", X"eb47", X"f00f", X"0911", X"df97", X"fd53",
                                                        X"fa4d", X"ebf7", X"f6dc", X"da1c", X"0344", X"06b1", X"f059", X"fabd", X"0444", X"2028", X"f507", X"f307", X"0078", X"0a97",
                                                        X"e0f2", X"fc36", X"0682", X"21d9", X"f5c6", X"e26f", X"09bd", X"07ed", X"0c60", X"0c51", X"ff0c", X"e1d6", X"0bc2", X"0ef6",
                                                        X"f6b7", X"104a", X"023a", X"0103", X"f43b", X"04f0", X"14b2", X"dd7c", X"fbe4", X"fe82", X"00c3", X"f080", X"f32b", X"e3a9",
                                                        X"f378", X"f549", X"e60a", X"07d7", X"fff6", X"18e5", X"05e5", X"fb54", X"11cf", X"f095", X"06de", X"fe66", X"e170", X"083c",
                                                        X"fd55", X"0ee5", X"e7ae", X"f5ab", X"e9f0", X"ef4f", X"e32e", X"f19d", X"01fb", X"14d1", X"04b7", X"0858", X"0ab1", X"18c0",
                                                        X"f5c3", X"eb61", X"094a", X"0633", X"e7dc", X"fc43", X"f3a0", X"120a", X"e7f2", X"fff6", X"f029", X"0eda", X"fa49", X"01ce",
                                                        X"07d2", X"1397", X"0aea", X"0ca4", X"140e", X"e6b6", X"fc68", X"1261", X"01e7", X"0181", X"1576", X"0252", X"f684", X"10e5",
                                                        X"0bd7", X"0aa8", X"0eba", X"fe33", X"eedf", X"fb15", X"0195", X"ea5e", X"f5a3", X"fedc", X"eb65", X"ee27", X"ee47", X"f44d",
                                                        X"fbe2", X"fa9d", X"ea3b", X"fd6c", X"0b1f", X"fb2c", X"f3dc", X"ed5e", X"0693", X"e887", X"fc24", X"f6a2", X"1c51", X"0f61",
                                                        X"ea7f", X"f733", X"0414", X"0bc4", X"f224", X"ec4a", X"f57b", X"0e48", X"1a31", X"0200", X"febc", X"fe5d", X"f90f", X"fb6e",
                                                        X"03fd", X"05b2", X"fb06", X"fe06", X"126a", X"16ee", X"09c9", X"0478", X"f718", X"f91c", X"1241", X"f0b9", X"0f5e", X"e7cb",
                                                        X"f499", X"1794", X"03c0", X"ecec", X"0ed0", X"fbfb", X"137e", X"ed8c", X"fad6", X"eccf", X"027f", X"ecd2", X"145a", X"0368",
                                                        X"1403", X"0c57", X"0739", X"0a84", X"de50", X"fa5a", X"e0fe", X"08da", X"0b2f", X"15c3", X"d70e", X"f522", X"f357", X"fcbd",
                                                        X"f573", X"0661", X"182e", X"0a7e", X"147d", X"141b", X"f04f", X"ea70", X"f869", X"f043", X"03e3", X"e82f", X"fcbb", X"e336",
                                                        X"fc70", X"0c99", X"0a3a", X"e8ce", X"fe6c", X"ec52", X"ec95", X"efd7", X"f314", X"fde2", X"f8fc", X"017d", X"0f1d", X"e9fc",
                                                        X"e7c1", X"005f", X"f4f2", X"f285", X"f784", X"136a", X"0075", X"f889", X"0b71", X"f522", X"0c9b", X"ffea", X"fe83", X"ff03",
                                                        X"0d72", X"ee72", X"f3ab", X"e47c", X"062d", X"04a5", X"09af", X"02b7", X"1c69", X"00de", X"1697", X"ef9f", X"106f", X"129c",
                                                        X"028a", X"0169", X"04f8", X"df2e", X"0405", X"f5f8", X"0815", X"fc40", X"f641", X"182e", X"fe69", X"ea8c", X"10b0", X"164e",
                                                        X"1903", X"1d39", X"1199", X"fe48", X"11a8", X"014a", X"1196", X"10ff", X"f685", X"048c", X"ffe7", X"04fc", X"f8bd", X"eab7",
                                                        X"f221", X"f3f6", X"f8ce", X"0963", X"188d", X"fbef", X"f934", X"d951", X"e39a", X"0c9e", X"f3ae", X"0d8f", X"1207", X"116c",
                                                        X"0630", X"1281", X"01e3", X"18ca", X"f1fd", X"f932", X"f8dc", X"f7fd", X"1370", X"e9ed", X"dbab", X"1a72", X"f1a4", X"0c66",
                                                        X"05a6", X"ece6", X"1458", X"03f8", X"010d", X"fbce", X"ef0d", X"0d3f", X"f151", X"12a3", X"0986", X"f400", X"f0e7", X"1047",
                                                        X"1072", X"f922", X"00bc", X"fade", X"1437", X"d4c0", X"13f8", X"e4be", X"f977", X"14c7", X"1989", X"f6f2", X"eafc", X"f13e",
                                                        X"da4b", X"114b", X"f39d", X"0df7", X"d962", X"0e46", X"018d", X"0c9c", X"0b72", X"ff5e", X"0a56", X"0689", X"de09", X"fe1c",
                                                        X"15bd", X"181a", X"ea9b", X"0ace", X"01c7", X"fa3a", X"0e48", X"f91d", X"e90a", X"dbb0", X"f2b5", X"01d5", X"fae9", X"0bbc",
                                                        X"fc8e", X"f9a1", X"1955", X"0c1c", X"08d2", X"12cc", X"00f3", X"1440", X"e97d", X"0b31", X"16b3", X"07a4", X"e903", X"fb8f",
                                                        X"1585", X"1317", X"118d", X"eb7b", X"f217", X"f9b3", X"e411", X"f978", X"fa53", X"f510", X"f248", X"ec8b", X"1440", X"10b6",
                                                        X"1f44", X"f265", X"0b5a", X"ecab", X"f46d", X"13b2", X"0079", X"ebe8", X"03bb", X"2f00", X"f0db", X"f5d2", X"f8bf", X"ee77",
                                                        X"149e", X"dc99", X"f61b", X"0e32", X"de68", X"f2a2", X"fa9a", X"f1bf", X"0632", X"eab8", X"f98f", X"fa6d", X"fffe", X"15aa",
                                                        X"ecd1", X"164e", X"178b", X"df6d", X"1f6b", X"1037", X"05db", X"ef7b", X"0f98", X"0c94", X"ecac", X"dd60", X"0803", X"124d",
                                                        X"0388", X"09c9", X"1889", X"10e8", X"0cc7", X"1017", X"fb2c", X"fb97", X"e844", X"fd20", X"0429", X"0691", X"e890", X"dc4e",
                                                        X"0055", X"088d", X"029e", X"13eb", X"e459", X"faad", X"03a5", X"1980", X"1bd7", X"fb63", X"e984", X"f831", X"1343", X"193e",
                                                        X"0a77", X"eee8", X"f071", X"04b4", X"fafb", X"0564", X"13c6", X"f876", X"fde6", X"f9e3", X"0fd0", X"e7b6", X"ede9", X"08ba",
                                                        X"0234", X"08c8", X"037b", X"fbaa", X"017c", X"e972", X"0965", X"0f96", X"f5cb", X"0e41", X"04a0", X"de70", X"0d5d", X"f81b",
                                                        X"1823", X"fd54", X"e64d", X"f5f6", X"070a", X"f60b", X"09c0", X"0c65", X"0321", X"f910", X"e310", X"04da", X"0894", X"d72f",
                                                        X"0339", X"0a04", X"0796", X"ec18", X"fc0d", X"e6db", X"0854", X"e54b", X"ef6b", X"f6e8", X"f6c4", X"044f", X"e573", X"0d8b",
                                                        X"fa01", X"ff34", X"fc4d", X"f911", X"0537", X"0551", X"fecc", X"e742", X"f47a", X"ec18", X"e6b9", X"09ba", X"f83f", X"ebc2",
                                                        X"0f5f", X"fe90", X"04b4", X"fb74", X"2007", X"1a91", X"f298", X"1652", X"ec2d", X"0515", X"fc05", X"e9bd", X"048e", X"0ed2",
                                                        X"040a", X"05a7", X"f28d", X"f2b3", X"108e", X"01d0", X"0ea2", X"f9c0", X"0e33", X"018e", X"0042", X"ffa2", X"1911", X"0944",
                                                        X"de64", X"0240", X"f1bd", X"0af9", X"e17f", X"0647", X"207f", X"e7df", X"e5a8", X"f4f5", X"0954", X"02b1", X"184d", X"0f90",
                                                        X"07ca", X"e70b", X"0911", X"07e1", X"fe61", X"029d", X"e3a1", X"fd18", X"f21d", X"d918", X"0d86", X"0133", X"0801", X"f9c9",
                                                        X"0a21", X"089b", X"13b6", X"1431", X"13af", X"15fb", X"e8bd", X"1824", X"e588", X"eaec", X"f768", X"00b3", X"0fa6", X"00e3",
                                                        X"f31d", X"160f", X"dfd6", X"0e7b", X"ee3b", X"fb2e", X"012a", X"f114", X"f3d3", X"1172", X"eb43", X"1a5c", X"06b7", X"083a",
                                                        X"f117", X"17fa", X"f398", X"01e8", X"dae6", X"df58", X"0e61", X"0f0f", X"f5d4", X"0023", X"f260", X"04ee", X"01dc", X"0509",
                                                        X"fa2c", X"db18", X"f90a", X"102d", X"0402", X"ea05", X"dcb3", X"feb3", X"fcfb", X"ee65", X"0160", X"06d1", X"0274", X"0a76",
                                                        X"e9f9", X"0717", X"03fa", X"055c", X"20bc", X"0348", X"0a0a", X"0a94", X"e52f", X"f3eb", X"1ce9", X"08b7", X"ef7e", X"fb6c",
                                                        X"f733", X"f6fa", X"f24a", X"fb78", X"eac3", X"043a", X"ff41", X"f705", X"feae", X"fafa", X"e5df", X"01c2", X"109e", X"ed67",
                                                        X"e0e3", X"df40", X"02fa", X"f757", X"eb9a", X"0aa5", X"07e7", X"ff2e", X"f01d", X"1273", X"122b", X"12ce", X"1c02", X"faf8",
                                                        X"02ec", X"0b35", X"fcb6", X"061d", X"032d", X"f7bc", X"f1f0", X"e60c", X"ff0b", X"0b1b", X"0ddd", X"0c45", X"ed8c", X"f29e",
                                                        X"fa95", X"1e8c", X"10fe", X"ee82", X"1052", X"e8ca", X"fc63", X"fcb1", X"f092", X"f852", X"fb62", X"1170", X"19d2", X"f665",
                                                        X"0909", X"11f8", X"103b", X"0c83", X"146c", X"f9d9", X"e72c", X"ec8e", X"077c", X"078c", X"11d7", X"1170", X"fc4a", X"e333",
                                                        X"fecd", X"ff0b", X"0454", X"0b27", X"fdba", X"0e28", X"0340", X"10f9", X"e614", X"ed0f", X"0a27", X"f5d7", X"16f8", X"fbb6",
                                                        X"08dd", X"0969", X"15bc", X"061d", X"e925", X"e8e2", X"e334", X"f269", X"fc34", X"fc43", X"0458", X"ec60", X"07ba", X"fed4",
                                                        X"e730", X"0f27", X"08c1", X"1341", X"e230", X"0ade", X"eb9c", X"fdbb", X"ff13", X"0fdd", X"1595", X"da8b", X"103c", X"e62b",
                                                        X"09c2", X"1e7a", X"05ce", X"ff0e", X"f899", X"15fb", X"05e4", X"0695", X"f360", X"e93b", X"fd99", X"1922", X"135f", X"fcb9",
                                                        X"e46c", X"0e47", X"f4d2", X"fad7", X"e0c1", X"f994", X"0e36", X"1114", X"11c3", X"f6bd", X"1216", X"064a", X"0a1b", X"0068",
                                                        X"0a53", X"0363", X"e17f", X"0724", X"ff78", X"fde2", X"1572", X"0ae7", X"02ce", X"0665", X"1573", X"ef00", X"efdb", X"099c",
                                                        X"fdc0", X"f878", X"1a9c", X"2729", X"f53d", X"03da", X"1315", X"110c", X"f51e", X"096a", X"fc80", X"e695", X"1a07", X"fee3",
                                                        X"127c", X"0f39", X"f606", X"18a4", X"1b0e", X"17f2", X"1895", X"ec76", X"1819", X"1d20", X"ea2d", X"1113", X"0993", X"d2b7",
                                                        X"0924", X"f076", X"ef09", X"13bb", X"1395", X"1050", X"0052", X"0110", X"ffdc", X"f818", X"0bb1", X"0704", X"e65b", X"fef3",
                                                        X"03e0", X"fb28", X"e563", X"1577", X"11af", X"0bc5", X"f04f", X"233a", X"2279", X"0999", X"1434", X"08ad", X"fcae", X"21ae",
                                                        X"fdca", X"0e17", X"08f5", X"e6d1", X"096d", X"05e6", X"f3e8", X"fff5", X"e97d", X"0d6c", X"22b3", X"119d", X"d98d", X"0a84",
                                                        X"f519", X"092a", X"143c", X"e148", X"02cb", X"1c4d", X"0f18", X"1524", X"0a97", X"e6cf", X"13c7", X"e82a", X"f576", X"1a94",
                                                        X"e41a", X"f069", X"0465", X"fea7", X"e9c8", X"0264", X"f3f1", X"116d", X"f3f5", X"f786", X"0b53", X"120a", X"f752", X"0c94",
                                                        X"0fed", X"05bb", X"0a64", X"f254", X"fa53", X"fa01", X"1941", X"1ba2", X"117b", X"e5ab", X"edc0", X"1c83", X"f23c", X"e0e5",
                                                        X"0587", X"1053", X"f9f6", X"fcf3", X"f266", X"d89b", X"f576", X"f3d1", X"fe5e", X"0b18", X"0962", X"f757", X"06e8", X"f296",
                                                        X"0cea", X"f904", X"e719", X"eaac", X"fb86", X"246e", X"fd7e", X"eaf1", X"fbab", X"f7ef", X"f521", X"002a", X"061a", X"dc18",
                                                        X"0377", X"f667", X"004e", X"f0d4", X"e6df", X"fe3c", X"1996", X"fca0", X"fe42", X"e68c", X"f960", X"fba5", X"e7b9", X"eddb",
                                                        X"ec99", X"1d73", X"1834", X"fd4d", X"01bb", X"0301", X"15ab", X"01cf", X"f9ae", X"131f", X"05e3", X"e506", X"0640", X"0e42",
                                                        X"fb5f", X"f16c", X"f97b", X"e9b2", X"edef", X"1a09", X"020f", X"13f1", X"01f5", X"093d", X"ea46", X"de72", X"eac0", X"d1d1",
                                                        X"01c3", X"f0dc", X"1662", X"fb90", X"f4b0", X"16fc", X"ecf9", X"0857", X"f96b", X"ea9a", X"008e", X"ff3a", X"f50a", X"0efb",
                                                        X"f17f", X"ffe1", X"05fe", X"ed14", X"ebd4", X"fcae", X"0de0", X"1631", X"f446", X"fb10", X"fed9", X"ecf2", X"e1f6", X"fc1b",
                                                        X"f203", X"f41b", X"0469", X"000d", X"112a", X"0e29", X"0360", X"0e10", X"0347", X"e8c4", X"f805", X"f362", X"f5c9", X"e5c7",
                                                        X"0847", X"f9d4", X"0965", X"d928", X"f5a3", X"f51d", X"0440", X"0375", X"0913", X"f130", X"0cc3", X"f804", X"fe64", X"fc43",
                                                        X"0bed", X"04f3", X"e3f7", X"f74a", X"f7d2", X"0d7a", X"f6af", X"fd5a", X"ff36", X"0685", X"fccf", X"0e3e", X"030c", X"f38f",
                                                        X"fd67", X"f84e", X"15ca", X"ef8d", X"efc8", X"0096", X"fa0c", X"fbbc", X"f46c", X"0152", X"05ae", X"0c6d", X"f4c2", X"01fa",
                                                        X"06df", X"ff6a", X"feac", X"fd06", X"e90a", X"0c9b", X"0995", X"f58e", X"02da", X"183d", X"08d4", X"f9d8", X"0bec", X"fee0",
                                                        X"0e2b", X"0095", X"23c4", X"21cf", X"0491", X"fa6e", X"1e36", X"f49b", X"09fb", X"fd98", X"fbd3", X"0b63", X"f244", X"ff2d",
                                                        X"13d9", X"1906", X"f3ce", X"065f", X"f5dc", X"f07d", X"234a", X"04c5", X"0a09", X"f176", X"03cd", X"0026", X"01b6", X"f748",
                                                        X"0e04", X"08d8", X"f9b4", X"1937", X"eeb8", X"0447", X"fade", X"1baf", X"e9be", X"f48e", X"f9cf", X"ec7c", X"04fa", X"030e",
                                                        X"078d", X"effa", X"0c4a", X"0026", X"0554", X"f819", X"074c", X"f5d3", X"085d", X"1e3c", X"e8e3", X"1650", X"0f9d", X"03be",
                                                        X"1733", X"ffb0", X"f92a", X"f59d", X"f6eb", X"ff57", X"1390", X"0cfb", X"f16e", X"e97f", X"1237", X"e86f", X"e736", X"ec37",
                                                        X"06fd", X"05b9", X"1fbb", X"020d", X"f62a", X"ed90", X"ec54", X"ff4c", X"0454", X"ffe2", X"06af", X"08ea", X"f680", X"f232",
                                                        X"f783", X"15bf", X"fdf7", X"0dd3", X"1d63", X"052d", X"fccd", X"fd8e", X"2371", X"1207", X"06fc", X"fedb", X"1169", X"124c",
                                                        X"00ef", X"1def", X"0e0d", X"f938", X"f528", X"1023", X"207f", X"02e2", X"1fbf", X"f3a2", X"f16d", X"e986", X"00ac", X"e72f",
                                                        X"e90c", X"efa7", X"03ae", X"04e8", X"d5da", X"fc23", X"1748", X"113b", X"109b", X"ff29", X"0f5f", X"ec42", X"ecfc", X"fdb1",
                                                        X"1529", X"fd94", X"fe8c", X"ffce", X"009d", X"1c5c", X"f57c", X"0ad7", X"ddd0", X"0769", X"fe37", X"052d", X"fa16", X"f7a2",
                                                        X"05df", X"ec05", X"108e", X"0f0d", X"ef37", X"fd04", X"16ad", X"d5f7", X"0c2c", X"ea71", X"f9e4", X"2bd2", X"0879", X"1835",
                                                        X"045d", X"254b", X"fc47", X"fef0", X"e974", X"06bd", X"027d", X"ffe9", X"1202", X"f64a", X"088c", X"2838", X"fb32", X"fa17",
                                                        X"fe4c", X"f9a7", X"1ac8", X"145d", X"e9e4", X"087c", X"f289", X"ff6c", X"0bf6", X"fac0", X"079b", X"ea6e", X"174f", X"0488",
                                                        X"042b", X"fb0b", X"d75e", X"0dae", X"1231", X"2881", X"f65a", X"f2c8", X"011c", X"1761", X"0ef6", X"0d0b", X"00d7", X"0085",
                                                        X"0e1e", X"1cb4", X"f71e", X"f40b", X"0732", X"ec7c", X"e623", X"0195", X"e5f8", X"04eb", X"ffde", X"1960", X"150e", X"04ae",
                                                        X"0c83", X"d9fa", X"0ac1", X"f17f", X"01b3", X"19b4", X"fcd7", X"09c8", X"0f4a", X"0c62", X"fc3a", X"05a9", X"10c9", X"0854",
                                                        X"e292", X"e7ec", X"ef76", X"f720", X"12e3", X"e39d", X"fc26", X"2ef3", X"ff88", X"0859", X"0edd", X"12e7", X"17d4", X"fae6",
                                                        X"11c5", X"ef81", X"0844", X"ecce", X"ed49", X"e763", X"d7a0", X"0ab7", X"feba", X"0316", X"f9e4", X"1461", X"e7f6", X"eba2",
                                                        X"e1b6", X"f28a", X"0e6d", X"f25a", X"fce9", X"1afd", X"069b", X"1089", X"de16", X"1a9d", X"189b", X"011a", X"f19f", X"00ef",
                                                        X"22c1", X"ee62", X"1545", X"1c7a", X"0be6", X"17a9", X"123b", X"06b9", X"f671", X"d829", X"1a0a", X"f866", X"00f7", X"04ba",
                                                        X"f8d3", X"06e2", X"ed70", X"fee5", X"13a9", X"fc09", X"0100", X"17f6", X"12d2", X"dd25", X"0c7a", X"00cf", X"0e9d", X"f531",
                                                        X"ff72", X"0215", X"e5b6", X"fc10", X"1d3d", X"f38a", X"dbdc", X"1387", X"f1b1", X"1763", X"09f1", X"050a", X"0d2b", X"fba4",
                                                        X"f3d5", X"f1e7", X"f2b3", X"f9ce", X"f3df", X"f3ca", X"1c44", X"fbd9", X"f6d5", X"fea6", X"f20a", X"1384", X"eccf", X"f25c",
                                                        X"147e", X"d8a5", X"03ce", X"0c97", X"0e39", X"0d48", X"dece", X"ed5d", X"f073", X"08bb", X"004e", X"ea38", X"f298", X"0146",
                                                        X"e438", X"f39f", X"f918", X"ef01", X"fc41", X"f834", X"ef5e", X"16ee", X"0ca5", X"115d", X"2842", X"e7b1", X"fd9f", X"f82c",
                                                        X"f04a", X"155e", X"f196", X"1032", X"ff30", X"14b9", X"e8ac", X"f42f", X"f5dc", X"139f", X"f5f2", X"0bf0", X"02d8", X"0f9d",
                                                        X"16b4", X"1ac7", X"0edc", X"0788", X"f933", X"0add", X"0324", X"efa5", X"1925", X"22c2", X"04a5", X"f4d3", X"1bbb", X"f9b3",
                                                        X"02b5", X"f14d", X"f8f5", X"f5a4", X"fd90", X"0ea9", X"e5fc", X"f6af", X"10b1", X"f749", X"ea9b", X"182e", X"0d14", X"16aa",
                                                        X"ed77", X"fb91", X"0087", X"012d", X"df43", X"f040", X"f242", X"faa2", X"1579", X"17de", X"edf0", X"15a2", X"0a30", X"012b",
                                                        X"ee88", X"0d01", X"e248", X"fbf1", X"13a1", X"f79d", X"fa98", X"06ec", X"01ae", X"0e53", X"e45d", X"fe1a", X"0f6e", X"0357",
                                                        X"106e", X"07d8", X"ff0e", X"0744", X"0c34", X"f0b3", X"f1c6", X"eb49", X"d4e6", X"12c3", X"08a2", X"0d13", X"e2fd", X"1d84",
                                                        X"f65b", X"f710", X"f734", X"144e", X"20e7", X"01e7", X"1ac8", X"03fc", X"0819", X"dfd0", X"dff8", X"ee3e", X"044a", X"13c7",
                                                        X"f181", X"0679", X"06dd", X"1049", X"1317", X"eb21", X"ff9b", X"13bc", X"e602", X"efef", X"1198", X"f268", X"1a71", X"13db",
                                                        X"096a", X"0dbd", X"0767", X"1173", X"e107", X"d5d3", X"ee0f", X"edc7", X"094a", X"f180", X"0553", X"1374", X"f0a6", X"fb6b",
                                                        X"f127", X"ec1a", X"f332", X"02b8", X"ea5d", X"11b5", X"0de6", X"f6c8", X"f723", X"e4e0", X"08fb", X"1697", X"f130", X"0843",
                                                        X"15e9", X"fde6", X"efe3", X"166d", X"01e5", X"05a7", X"0deb", X"142b", X"ff42", X"0e4e", X"e974", X"fbd7", X"008a", X"07bf",
                                                        X"df42", X"f3bc", X"0504", X"ed4f", X"11d7", X"16e2", X"0b9f", X"1cc3", X"f742", X"ea7c", X"15ed", X"d278", X"13e6", X"f221",
                                                        X"ede3", X"02d3", X"1980", X"e405", X"f24c", X"eb4a", X"f0d5", X"12a7", X"ff2c", X"1188", X"fd74", X"f31b", X"0253", X"d6a3",
                                                        X"0f43", X"e870", X"f533", X"f4a7", X"155e", X"0227", X"f5ce", X"f04b", X"e5cc", X"0a71", X"09ef", X"0b10", X"fbe3", X"fe9b",
                                                        X"1746", X"0492", X"1b62", X"f764", X"f031", X"e2c1", X"fbfc", X"fa88", X"17ef", X"fc7f", X"f6f2", X"fd37", X"f952", X"fae5",
                                                        X"de77", X"26b8", X"fca2", X"e8de", X"18ca", X"198b", X"1735", X"e919", X"2352", X"0684", X"fba8", X"ffeb", X"ecba", X"fa73",
                                                        X"1106", X"fa16", X"ed3f", X"07f6", X"0ae8", X"0ceb", X"015e", X"0c96", X"1ae4", X"1bf2", X"1931", X"1132", X"0783", X"eca2",
                                                        X"f897", X"f265", X"0df7", X"2733", X"ea7f", X"1b17", X"18af", X"f0f1", X"0a4a", X"f40c", X"0572", X"00a1", X"1165", X"fb15",
                                                        X"0615", X"f493", X"02c0", X"1f56", X"fa77", X"1e71", X"0a71", X"e6ea", X"fcf1", X"036d", X"f1ca", X"13b2", X"f10a", X"193d",
                                                        X"09bb", X"ebbd", X"1c78", X"1ce3", X"005a", X"e5ba", X"073b", X"fa40", X"14b5", X"0b30", X"e904", X"1e62", X"13e3", X"03f7",
                                                        X"0ce4", X"fc45", X"e514", X"fe85", X"0568", X"efd6", X"dba0", X"0eea", X"f4ce", X"036c", X"017b", X"0d83", X"1220", X"ff3c",
                                                        X"fc7e", X"0814", X"03c0", X"2275", X"e901", X"11b2", X"1dde", X"f9ae", X"11d1", X"07a8", X"e6df", X"1262", X"ea71", X"07f6",
                                                        X"fb81", X"0719", X"ee7f", X"0c1f", X"0b67", X"ff8c", X"18f8", X"0741", X"0fc1", X"fc63", X"dda5", X"0d51", X"e6cb", X"facb",
                                                        X"f271", X"054c", X"006a", X"f931", X"2232", X"09bb", X"0c82", X"f39a", X"0365", X"f7df", X"131a", X"e921", X"e686", X"f3fc",
                                                        X"f436", X"02d7", X"1daa", X"1929", X"f7c7", X"df2b", X"2bc7", X"0e6c", X"e512", X"27ab", X"1e97", X"18ff", X"1feb", X"20ae",
                                                        X"f266", X"1251", X"f34d", X"252c");
  SIGNAL data_int                         : std_logic_vector(DataWidth - 1 DOWNTO 0) := X"252c";
  SIGNAL addr_unsigned                    : unsigned(AddrWidth - 1 DOWNTO 0);  -- generic width

BEGIN
  addr_unsigned <= unsigned(addr);

  SinglePortRAM_generic_process: PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF enb = '1' THEN
        IF we = '1' THEN
          ram(to_integer(addr_unsigned)) <= din;
          data_int <= din;
        ELSE
          data_int <= ram(to_integer(addr_unsigned));
        END IF;
      END IF;
    END IF;
  END PROCESS SinglePortRAM_generic_process;

  dout <= data_int;

END rtl;

