-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/amc_model_w16a16/amc_cnn_16w16a_src_SinglePortRAM_generic_block389.vhd
-- Created: 2023-07-03 13:16:54
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: amc_cnn_16w16a_src_SinglePortRAM_generic_block389
-- Source Path: amc_model_w16a16/DUT HDL/Dense Layer 1/Dense Layer 1/Weight Storage38/SinglePortRAM_generic
-- Hierarchy Level: 4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY amc_cnn_16w16a_src_SinglePortRAM_generic_block389 IS
  GENERIC( AddrWidth                      : integer := 1;
           DataWidth                      : integer := 1
           );
  PORT( clk                               :   IN    std_logic;
        enb                               :   IN    std_logic;
        din                               :   IN    std_logic_vector(DataWidth - 1 DOWNTO 0);  -- generic width
        addr                              :   IN    std_logic_vector(AddrWidth - 1 DOWNTO 0);  -- generic width
        we                                :   IN    std_logic;  -- ufix1
        dout                              :   OUT   std_logic_vector(DataWidth - 1 DOWNTO 0)  -- generic width
        );
END amc_cnn_16w16a_src_SinglePortRAM_generic_block389;


ARCHITECTURE rtl OF amc_cnn_16w16a_src_SinglePortRAM_generic_block389 IS

  -- Local Type Definitions
  TYPE ram_type IS ARRAY (2**AddrWidth - 1 DOWNTO 0) of std_logic_vector(DataWidth - 1 DOWNTO 0);

  -- Signals
  SIGNAL ram                              : ram_type := (X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"fa16", X"fc67", X"f7a8", X"fe5f", X"0c27", X"0841",
                                                        X"fe61", X"1478", X"f220", X"ebd7", X"ea77", X"ee08", X"0270", X"fdd4", X"0f5a", X"fcdd", X"fdba", X"f216", X"0c26", X"0679",
                                                        X"f62d", X"f686", X"f4e3", X"0855", X"13b5", X"fdbf", X"f1f0", X"fe75", X"ed57", X"0716", X"1081", X"fd41", X"fea8", X"fbcf",
                                                        X"f11b", X"f992", X"fbbd", X"0bb0", X"e2dd", X"ee06", X"ff30", X"ff1f", X"fa31", X"fc4c", X"ffae", X"fb5e", X"0d67", X"0164",
                                                        X"0387", X"0604", X"0969", X"fada", X"1964", X"1077", X"0492", X"f2e8", X"fb2d", X"fd7b", X"1343", X"0568", X"16c2", X"eb28",
                                                        X"1098", X"059e", X"03e9", X"0b41", X"f8ea", X"fe3d", X"0092", X"0e53", X"07e1", X"081e", X"0daf", X"0ca5", X"0487", X"0270",
                                                        X"fe25", X"056a", X"09ba", X"0d05", X"fe97", X"1650", X"0595", X"05b5", X"028c", X"0ef8", X"083b", X"0c53", X"0327", X"05f0",
                                                        X"fdc1", X"032f", X"fa40", X"0bae", X"1169", X"fe88", X"01e5", X"0f01", X"ffce", X"fd4a", X"ebef", X"f796", X"0b6d", X"fcba",
                                                        X"fe47", X"043a", X"f53f", X"f68d", X"0b04", X"e519", X"13af", X"f962", X"f614", X"0d60", X"181f", X"004f", X"1286", X"f27f",
                                                        X"0c66", X"f8c7", X"1507", X"0400", X"f805", X"0cfb", X"017f", X"159b", X"01f8", X"fe7f", X"0611", X"f332", X"01fd", X"f817",
                                                        X"f616", X"049a", X"0946", X"fda9", X"04e8", X"fd35", X"f2d2", X"f54b", X"0502", X"07c7", X"f4c7", X"fd1f", X"f80e", X"faf1",
                                                        X"0b8c", X"fd88", X"02f5", X"02bd", X"070c", X"087c", X"0621", X"04a5", X"f59f", X"048f", X"fd7b", X"eb45", X"f372", X"06dd",
                                                        X"f76f", X"fb8e", X"0410", X"fcdb", X"02e2", X"ffc9", X"02f1", X"ffed", X"fca8", X"f248", X"f4e5", X"fb8c", X"057f", X"0760",
                                                        X"f9b3", X"0206", X"df83", X"f69b", X"08c3", X"e926", X"ee9d", X"03db", X"f87f", X"ecac", X"fe56", X"f4cb", X"f1e4", X"f9ed",
                                                        X"06c5", X"0c8d", X"08f8", X"f828", X"ef14", X"0590", X"e6f5", X"028b", X"efeb", X"0e99", X"ee7a", X"fcec", X"0dac", X"f81d",
                                                        X"0a63", X"0bf3", X"0882", X"ffd9", X"f045", X"11b6", X"00e8", X"eed3", X"fe1e", X"f302", X"082a", X"049e", X"ecc1", X"fa10",
                                                        X"f7ff", X"04e1", X"1403", X"f9e9", X"f3b4", X"edc8", X"016d", X"0bdb", X"0685", X"0dc5", X"f3f4", X"ff39", X"ff25", X"081c",
                                                        X"fc15", X"ff13", X"0b9a", X"ffb8", X"fb92", X"f7fb", X"fe0e", X"f3a1", X"0873", X"045b", X"fa66", X"069c", X"0133", X"fb16",
                                                        X"0a9d", X"008e", X"093d", X"0097", X"eeb5", X"061b", X"0de9", X"eacb", X"e9b6", X"fa86", X"09dc", X"f1c9", X"efd8", X"1567",
                                                        X"f440", X"0833", X"eb32", X"f1be", X"ee6b", X"06e4", X"0d72", X"02d6", X"ed56", X"f8e2", X"0568", X"dcb8", X"048d", X"f47e",
                                                        X"ed9c", X"f0ed", X"f739", X"e5e2", X"e892", X"ef16", X"fa37", X"0df3", X"0939", X"0135", X"ebc3", X"f753", X"ff19", X"fa2f",
                                                        X"ff5e", X"0177", X"f6a1", X"02de", X"fd16", X"f71f", X"0e51", X"f40c", X"f71f", X"f846", X"0ece", X"ebe6", X"0069", X"fb7c",
                                                        X"f0b1", X"0291", X"1232", X"fc28", X"0013", X"f2a1", X"0587", X"15c4", X"1764", X"fce4", X"1934", X"0333", X"f6f9", X"fd0d",
                                                        X"221d", X"03b1", X"0284", X"04c8", X"f8c8", X"0863", X"efbd", X"1b51", X"f7d7", X"f05e", X"01b1", X"0e73", X"1055", X"05a0",
                                                        X"00ad", X"0966", X"1001", X"05d4", X"06f3", X"1e9f", X"0930", X"0865", X"0cdc", X"00ac", X"13ad", X"05ad", X"24c1", X"170a",
                                                        X"003a", X"0302", X"0122", X"0b68", X"06d8", X"1109", X"2028", X"e862", X"f76b", X"1a2c", X"0c5a", X"07cd", X"150a", X"134e",
                                                        X"1d8d", X"23f4", X"02d8", X"0ee9", X"22d0", X"10c1", X"174a", X"064f", X"2165", X"0ddd", X"0bad", X"10b5", X"0896", X"11de",
                                                        X"1573", X"11c3", X"1255", X"213f", X"0ce3", X"06c6", X"1b6f", X"0c7e", X"0303", X"fbbb", X"fe82", X"08dd", X"fee1", X"03c7",
                                                        X"0879", X"0e2b", X"08d0", X"e639", X"1978", X"f8bc", X"0534", X"0809", X"e984", X"083f", X"fcd9", X"fa9b", X"0c1d", X"0b71",
                                                        X"12d1", X"0569", X"fb0e", X"0cb3", X"fdf1", X"0832", X"0439", X"f9d7", X"f6a6", X"0551", X"04ef", X"f80e", X"0507", X"f508",
                                                        X"0e1b", X"0bf0", X"fdc8", X"f625", X"efe1", X"1237", X"f2a9", X"fdf9", X"e37f", X"f6eb", X"0be7", X"f08e", X"ebab", X"035b",
                                                        X"ea01", X"f8fc", X"f7c2", X"f2c8", X"06c3", X"f97f", X"f130", X"fe80", X"f831", X"f283", X"e7f6", X"e71a", X"074a", X"ed7b",
                                                        X"ffa6", X"f3aa", X"ec63", X"fe86", X"0943", X"f95c", X"0118", X"0082", X"ef13", X"f69c", X"ffb7", X"ed5d", X"f666", X"fb5f",
                                                        X"eb6d", X"fa2a", X"f1ce", X"fad5", X"03da", X"0319", X"f6b4", X"f1e9", X"fb7e", X"0248", X"0980", X"f5a5", X"f24e", X"e76a",
                                                        X"030b", X"11c7", X"fc6a", X"04ec", X"01ef", X"065a", X"fe5c", X"0515", X"0295", X"fa14", X"f3a9", X"f8ff", X"05b8", X"fbae",
                                                        X"fd76", X"f15f", X"065b", X"0547", X"081b", X"fe9e", X"f54b", X"030e", X"f8ac", X"f948", X"01b8", X"03e5", X"fe8b", X"03f9",
                                                        X"fc3c", X"07e6", X"f190", X"effe", X"04ec", X"0493", X"0e1a", X"fef7", X"e750", X"fcf6", X"f6f5", X"fc24", X"f1e4", X"fc12",
                                                        X"fc6f", X"0b6e", X"0302", X"0516", X"f9fe", X"f39c", X"0525", X"09e1", X"f704", X"f8c7", X"fa8e", X"f459", X"fd16", X"02f3",
                                                        X"f3ac", X"f162", X"f5bd", X"fcda", X"fac4", X"fe31", X"fba7", X"f2b3", X"0330", X"0455", X"fb02", X"f868", X"f5e8", X"fc37",
                                                        X"f977", X"03b2", X"efb3", X"f0b7", X"fb15", X"f20d", X"f451", X"fd86", X"04a0", X"02a3", X"fd83", X"f844", X"f428", X"f7f6",
                                                        X"fd4d", X"f2bc", X"0242", X"0844", X"f706", X"f761", X"fd9d", X"f4a6", X"f3ec", X"f0bc", X"f4ec", X"0608", X"f4b8", X"0601",
                                                        X"fac4", X"ff28", X"f120", X"ff50", X"fe33", X"0f90", X"e63a", X"0359", X"f91d", X"0145", X"ef51", X"fe09", X"011c", X"f918",
                                                        X"ff3b", X"fb99", X"f3ca", X"fd1d", X"061b", X"f712", X"fe9b", X"0a2c", X"fa50", X"fb41", X"06bd", X"01fb", X"fdad", X"0173",
                                                        X"f164", X"0204", X"feba", X"083d", X"17cb", X"01cb", X"e999", X"0729", X"0df6", X"16ca", X"0969", X"0522", X"02c8", X"0c38",
                                                        X"f834", X"006b", X"f546", X"fbf2", X"fb3f", X"0d54", X"049e", X"fd32", X"f849", X"00a7", X"0a4b", X"067d", X"f449", X"0c39",
                                                        X"1320", X"0327", X"070a", X"0d6e", X"093c", X"f5b9", X"f57c", X"02a4", X"0766", X"0165", X"f7e6", X"0e61", X"f73e", X"f509",
                                                        X"f47e", X"f71c", X"015f", X"0105", X"027b", X"0e9f", X"0c75", X"e85a", X"fd08", X"fec2", X"0cc1", X"0107", X"0b36", X"008b",
                                                        X"01dc", X"f68e", X"07e2", X"1012", X"027a", X"fe51", X"0689", X"00a4", X"f2b0", X"e7a8", X"f9ac", X"04c9", X"0cf3", X"f03f",
                                                        X"f1c7", X"fa67", X"f59f", X"052d", X"f312", X"1502", X"f493", X"ff83", X"f247", X"06f6", X"ffb6", X"f3f6", X"f85a", X"09a8",
                                                        X"0d7e", X"0741", X"0b7e", X"0736", X"fcc0", X"12d2", X"f663", X"fa62", X"f6b2", X"02f9", X"fedf", X"040d", X"f495", X"f111",
                                                        X"0c45", X"026f", X"f6c7", X"03cf", X"f77c", X"f921", X"fe23", X"f8d6", X"ef7a", X"0a01", X"fbcb", X"f9ec", X"fd44", X"14b1",
                                                        X"f3b8", X"faf8", X"0efd", X"0754", X"fcae", X"fae0", X"f513", X"07f5", X"f9ef", X"f9fc", X"ed1a", X"f34e", X"f344", X"03be",
                                                        X"ff04", X"0223", X"008a", X"f4e7", X"fde5", X"0097", X"02d5", X"0a58", X"f888", X"0f58", X"0d63", X"0742", X"0bba", X"f43a",
                                                        X"063b", X"03b5", X"09c2", X"0ebb", X"06ed", X"f8c8", X"1911", X"0fcb", X"01c3", X"0044", X"e8c5", X"04c3", X"0f73", X"0412",
                                                        X"151b", X"f346", X"0260", X"069e", X"06d2", X"0ca0", X"0a5f", X"f0d5", X"f7b1", X"1209", X"0b11", X"08cd", X"ea99", X"0270",
                                                        X"0351", X"02e6", X"f69b", X"1786", X"072b", X"fedd", X"ffd8", X"0bd2", X"0391", X"f0eb", X"f7da", X"03ba", X"0706", X"f3d7",
                                                        X"fd7f", X"003e", X"f1a1", X"ee6a", X"efa8", X"0b06", X"f84e", X"fadc", X"029f", X"fc9a", X"f46d", X"ffa0", X"f945", X"00e3",
                                                        X"f6f9", X"0655", X"f9d9", X"0011", X"0935", X"01d5", X"f46b", X"ef65", X"f25f", X"03cc", X"f5c5", X"10de", X"f466", X"ef09",
                                                        X"ed5f", X"f74e", X"ff15", X"0763", X"102a", X"f1a0", X"0ff2", X"fd5e", X"f653", X"097d", X"faa2", X"fead", X"f5d6", X"fee1",
                                                        X"0e15", X"079b", X"0a95", X"f7e4", X"1886", X"ee0c", X"0ddd", X"f837", X"0f64", X"fbcd", X"f357", X"f0a0", X"f67f", X"07cd",
                                                        X"0043", X"1ea1", X"f272", X"f479", X"0dfe", X"09d6", X"0c33", X"f469", X"12aa", X"0359", X"fa24", X"030e", X"0288", X"e40a",
                                                        X"0b17", X"05ef", X"084f", X"f2d5", X"ef9b", X"ef17", X"2197", X"1469", X"06bc", X"029d", X"056a", X"022a", X"f72b", X"04e5",
                                                        X"09ab", X"0f0d", X"01c7", X"069e", X"1a8e", X"fd79", X"0c42", X"1743", X"ff04", X"1d92", X"08c0", X"f993", X"f9ef", X"0436",
                                                        X"0eb3", X"0fe5", X"18d5", X"0585", X"0b15", X"0e49", X"12e2", X"0d75", X"061d", X"06f1", X"0920", X"18ca", X"103f", X"fbee",
                                                        X"f101", X"fcdd", X"113b", X"0ac5", X"14cf", X"047c", X"fbe0", X"114c", X"0503", X"fcea", X"0dd5", X"01c7", X"00ed", X"0fc7",
                                                        X"f5cb", X"065b", X"f27b", X"04f6", X"00d7", X"0c38", X"0dc1", X"ff1d", X"fce0", X"083d", X"0102", X"191b", X"f732", X"fdfa",
                                                        X"041d", X"1204", X"126d", X"0358", X"13ce", X"f9c4", X"1fb5", X"0e42", X"f587", X"2358", X"01b5", X"f947", X"064f", X"0571",
                                                        X"eda4", X"ffe4", X"03ab", X"f21f", X"0e86", X"0638", X"0138", X"f95c", X"00a5", X"117d", X"f98b", X"f0ae", X"f65a", X"ff2f",
                                                        X"fb30", X"0091", X"fe11", X"0572", X"f682", X"f794", X"06fd", X"f625", X"e9b2", X"0ed8", X"ee26", X"02d0", X"fd93", X"f5ee",
                                                        X"fab6", X"fc0c", X"eb88", X"f683", X"f754", X"08cb", X"f1ff", X"dba9", X"ffaa", X"f501", X"e6de", X"0b91", X"04b0", X"0457",
                                                        X"0a69", X"082e", X"f1cc", X"0406", X"e9d5", X"fec2", X"06da", X"fe4a", X"0e7f", X"e7fd", X"e9c9", X"f24f", X"ec05", X"f563",
                                                        X"f5b2", X"081a", X"014f", X"fa65", X"ff54", X"fb27", X"eacf", X"0f38", X"069b", X"f9a0", X"f2b7", X"0171", X"0065", X"fa7d",
                                                        X"0a6f", X"f6f4", X"fe4c", X"0f55", X"f282", X"005f", X"0690", X"0094", X"00a6", X"fa25", X"1566", X"0b02", X"1e6e", X"10e5",
                                                        X"f99f", X"03b3", X"ffec", X"f9ea", X"fd8b", X"0465", X"0a23", X"1406", X"07a2", X"1522", X"13be", X"f8cb", X"08f7", X"0906",
                                                        X"fd39", X"0918", X"0b70", X"01bd", X"0610", X"00ae", X"f9b7", X"0b2b", X"f98c", X"0d22", X"080d", X"0a03", X"fbe6", X"f7c2",
                                                        X"fda5", X"f6d7", X"0230", X"0e55", X"f678", X"0793", X"08f1", X"fd74", X"f7ab", X"1757", X"fcf3", X"0cd3", X"0226", X"0f65",
                                                        X"f21b", X"0a66", X"fcc3", X"ee16", X"0005", X"f6fe", X"06be", X"0220", X"02cb", X"f456", X"02de", X"fbd6", X"07d4", X"1297",
                                                        X"029c", X"0314", X"ffe9", X"0e80", X"0883", X"e68c", X"fd9a", X"fa20", X"11ef", X"ffb5", X"f6c2", X"0ef8", X"fdb3", X"0a12",
                                                        X"ef83", X"03f2", X"fcad", X"0889", X"008c", X"f7d8", X"fff1", X"02e4", X"015b", X"eeb2", X"fad9", X"f676", X"fb5b", X"f7e0",
                                                        X"faaf", X"fc34", X"fff6", X"f431", X"f865", X"f88a", X"fd00", X"06cb", X"fa5f", X"0746", X"f2f1", X"edf7", X"ec6e", X"004b",
                                                        X"edb4", X"047a", X"f13c", X"fe3f", X"f0fa", X"f7e8", X"fd8c", X"f6db", X"ed0e", X"ed73", X"f268", X"e56e", X"f28c", X"f722",
                                                        X"fe68", X"f5e1", X"e336", X"fef6", X"f4ea", X"ffda", X"007a", X"ec75", X"f9c9", X"fc41", X"f5ef", X"ebee", X"fbe9", X"e5cb",
                                                        X"f59f", X"ec5b", X"fc5d", X"e471", X"f965", X"e416", X"f042", X"ef5a", X"04c3", X"f8df", X"faf2", X"f56d", X"ec05", X"ee54",
                                                        X"f5ef", X"e494", X"ff33", X"f992", X"fd08", X"ea12", X"f2c9", X"e8fd", X"0715", X"f217", X"e6a1", X"fc66", X"f28d", X"f856",
                                                        X"ed12", X"0c6a", X"0464", X"03e5", X"f598", X"ef72", X"f147", X"f505", X"e3dc", X"e9bb", X"07f0", X"f3cd", X"0943", X"010b",
                                                        X"fa4f", X"f437", X"f26f", X"f965", X"f47a", X"073e", X"e5f1", X"f0db", X"fb94", X"f755", X"0978", X"0049", X"fced", X"faa8",
                                                        X"0a21", X"f08e", X"f9b4", X"fc20", X"fb0a", X"146e", X"f19f", X"f128", X"fe66", X"ed23", X"0d9f", X"fcb2", X"0317", X"fe56",
                                                        X"f163", X"04b0", X"fe81", X"ea61", X"000c", X"f8a6", X"0339", X"04af", X"ef55", X"0173", X"fd73", X"f666", X"0433", X"0608",
                                                        X"0f54", X"006b", X"06d9", X"0a21", X"072b", X"04c3", X"010a", X"ffd2", X"0230", X"fe9f", X"0567", X"fc22", X"08a4", X"071d",
                                                        X"0363", X"fe64", X"00d5", X"0386", X"0a19", X"0cc2", X"fd10", X"0992", X"fdf5", X"0f7c", X"06c4", X"0539", X"f838", X"093e",
                                                        X"1a1c", X"1ab0", X"11f0", X"0853", X"164d", X"feb4", X"0a31", X"0b27", X"fa15", X"06ee", X"f7d6", X"1541", X"0b76", X"07da",
                                                        X"00ce", X"1b08", X"05a6", X"11cf", X"1254", X"fdfa", X"011a", X"0ea1", X"1ccf", X"fb7e", X"0f99", X"00d5", X"0862", X"12e3",
                                                        X"09a9", X"0244", X"099b", X"014d", X"0c6a", X"1edc", X"0fa8", X"0a0a", X"0d3f", X"11cb", X"0dd1", X"05b9", X"0be6", X"fd76",
                                                        X"1252", X"0ee2", X"1ab7", X"032a", X"0d2e", X"f70f", X"07b0", X"1031", X"088c", X"04f4", X"055a", X"f908", X"08dd", X"07b8",
                                                        X"0b2b", X"1f5b", X"07a4", X"0255", X"051e", X"f887", X"fe5d", X"0bb8", X"0410", X"0a9f", X"e863", X"f14a", X"04b0", X"0310",
                                                        X"f297", X"f472", X"0f3f", X"09d5", X"fd35", X"08b3", X"ff98", X"ec45", X"07b3", X"159b", X"fd91", X"f876", X"f594", X"02f1",
                                                        X"f5fc", X"fd37", X"04ad", X"0bd2", X"0a2c", X"f994", X"f0ce", X"fb0e", X"fc67", X"034a", X"09df", X"1169", X"f8d6", X"f6a0",
                                                        X"0565", X"ffca", X"e5ea", X"f0a3", X"f373", X"f77d", X"fc77", X"fb36", X"fe06", X"fcb7", X"f139", X"004d", X"ff15", X"e779",
                                                        X"ff27", X"eff8", X"ef45", X"0d00", X"03c1", X"039a", X"e5ed", X"f236", X"fcbf", X"ff5b", X"036b", X"f4c8", X"f2f4", X"023e",
                                                        X"f279", X"eebb", X"ed92", X"fb84", X"ed8d", X"0219", X"ea62", X"ff85", X"f8d4", X"018f", X"fc2f", X"f95f", X"0f36", X"f4d8",
                                                        X"f904", X"fcb7", X"06f9", X"f454", X"0213", X"0ac8", X"0344", X"049e", X"fea6", X"01a5", X"022f", X"f99c", X"fd07", X"f680",
                                                        X"0c6b", X"f379", X"02d4", X"f980", X"f778", X"01ce", X"f3ea", X"0565", X"06af", X"ec23", X"009e", X"08c2", X"ffc1", X"039d",
                                                        X"f622", X"0816", X"fdb8", X"040a", X"fd6d", X"e737", X"fa6d", X"0b46", X"01c0", X"0d8b", X"fc1f", X"0175", X"0706", X"030c",
                                                        X"04ce", X"fca5", X"f06b", X"116f", X"ffd2", X"0441", X"01e4", X"f6c2", X"0590", X"ec8e", X"f770", X"f606", X"f943", X"e92d",
                                                        X"ef84", X"fd3f", X"e929", X"f879", X"f185", X"e7ff", X"f9ec", X"f54b", X"fb3d", X"fa6a", X"0234", X"fb69", X"edf4", X"e71b",
                                                        X"f019", X"0747", X"1488", X"f2b0", X"fa6a", X"f5c7", X"fc5f", X"f729", X"0df1", X"fa00", X"f6b2", X"15b2", X"ec24", X"f857",
                                                        X"0b86", X"f12c", X"002d", X"0662", X"f9ba", X"0091", X"f5bb", X"f79e", X"012b", X"ff0f", X"08d3", X"031f", X"0c7f", X"1802",
                                                        X"ffa9", X"ec6c", X"133a", X"197f", X"f11f", X"094c", X"05c4", X"0903", X"0554", X"08ea", X"0bf3", X"fdf1", X"f4c1", X"0a8e",
                                                        X"02db", X"0dd0", X"fe4f", X"f1bc", X"e982", X"00e6", X"0cd5", X"f9d3", X"0104", X"f93c", X"0346", X"0a3a", X"0175", X"0814",
                                                        X"feba", X"0353", X"fe54", X"0ca2", X"f92b", X"0b9a", X"0b18", X"08e0", X"04d5", X"0dbd", X"0926", X"002a", X"1d60", X"06c6",
                                                        X"0049", X"ed2c", X"0032", X"0eb9", X"f82b", X"0e49", X"045a", X"0860", X"0056", X"fe1d", X"0d79", X"feba", X"0891", X"04fd",
                                                        X"171d", X"047c", X"0066", X"f372", X"158a", X"0d8e", X"fe14", X"082a", X"f416", X"fdc2", X"0c2d", X"fb99", X"f868", X"fc19",
                                                        X"fbe8", X"15a0", X"0fae", X"e5e1", X"fe20", X"f4ed", X"1d19", X"ff16", X"0989", X"f01a", X"f238", X"0f31", X"2246", X"fc59",
                                                        X"12a0", X"028b", X"f2d4", X"0413", X"0200", X"fdb3", X"014f", X"05c6", X"0dc0", X"0000", X"00c2", X"0024", X"f68d", X"ffe0",
                                                        X"fa4b", X"0339", X"0547", X"0227", X"f94c", X"f195", X"fbfe", X"fcb6", X"10c0", X"0399", X"0db6", X"f736", X"03e6", X"fbd6",
                                                        X"f4ef", X"eda7", X"0b8a", X"0c97", X"0b0c", X"0a25", X"0d21", X"ff7e", X"f5cf", X"fb5f", X"08ec", X"f956", X"f87c", X"fff0",
                                                        X"f8ab", X"0134", X"f718", X"0244", X"fe34", X"ff20", X"fd81", X"fc28", X"0416", X"f9f5", X"fc58", X"f82b", X"010d", X"08be",
                                                        X"e611", X"05d4", X"010c", X"0f25", X"f655", X"ef2c", X"0629", X"0bc4", X"19a6", X"015a", X"0951", X"0737", X"fcca", X"f6e2",
                                                        X"06b8", X"f4e0", X"f066", X"1225", X"0051", X"ffb5", X"012a", X"044e", X"068c", X"0cfd", X"08ea", X"0d08", X"f24d", X"003a",
                                                        X"f63a", X"fb38", X"e816", X"04f7", X"fdf7", X"fe72", X"081c", X"ef54", X"fd6f", X"054c", X"fb58", X"fe81", X"08ed", X"fc0b",
                                                        X"eed3", X"fcab", X"033d", X"fa8e", X"fbe7", X"fa00", X"fc33", X"0c22", X"fddd", X"09d6", X"071c", X"0620", X"f4b7", X"0a4e",
                                                        X"0981", X"f99d", X"007d", X"0130", X"0ccf", X"fc48", X"fd3f", X"f734", X"0650", X"00a4", X"02ed", X"050c", X"063a", X"0777",
                                                        X"0714", X"f1ff", X"0d9a", X"048a", X"0644", X"027b", X"029a", X"fff6", X"fe86", X"f5a2", X"03f3", X"fb80", X"f423", X"0886",
                                                        X"fc69", X"13bb", X"f848", X"f04e", X"ff7e", X"fcb8", X"03ae", X"0913", X"f588", X"facc", X"f453", X"e099", X"fddb", X"03b7",
                                                        X"f158", X"16fd", X"ef71", X"f95f", X"0351", X"f624", X"f382", X"f0ef", X"ee96", X"0b76", X"f8aa", X"f9df", X"f9b3", X"040c",
                                                        X"feab", X"f5ba", X"fb4a", X"ff92", X"f61b", X"fcf1", X"0af4", X"f937", X"fb10", X"00e4", X"fcea", X"fa66", X"0009", X"0618",
                                                        X"fa1f", X"fbe7", X"f8be", X"0844", X"fe99", X"1bf3", X"f943", X"eaf5", X"f9fe", X"0e44", X"08d7", X"0cb2", X"0664", X"0297",
                                                        X"123c", X"02f9", X"0a9b", X"f8d9", X"0261", X"fd3b", X"f903", X"f239", X"f9d3", X"0f41", X"1935", X"1eca", X"f9c7", X"0a36",
                                                        X"fd23", X"fed9", X"1744", X"ffbe", X"fdbd", X"17a7", X"00ba", X"0b8d", X"0bd7", X"fdac", X"0ede", X"f3d2", X"1e50", X"1605",
                                                        X"fc26", X"1465", X"f1b8", X"0926", X"003a", X"0bd2", X"0db1", X"ea1a", X"147e", X"1fb2", X"01df", X"0ec5", X"069a", X"007b",
                                                        X"047b", X"2432", X"034f", X"fbb3", X"fd0f", X"05a3", X"1f43", X"0b0b", X"05d2", X"0f8b", X"1041", X"0d34", X"1964", X"02af",
                                                        X"14a8", X"0a75", X"1171", X"176e", X"fd7a", X"fae6", X"f586", X"114f", X"0e42", X"0ff4", X"052d", X"117a", X"0605", X"0557",
                                                        X"fbd8", X"fba6", X"0a54", X"eefa", X"0c86", X"047a", X"f75f", X"f58e", X"05ce", X"0f31", X"e79a", X"0e22", X"f89d", X"0a78",
                                                        X"121e", X"f3ea", X"ecd0", X"0d1e", X"0326", X"e594", X"ff42", X"098d", X"fea3", X"f740", X"0bcb", X"fe11", X"ed1a", X"04ed",
                                                        X"f170", X"14d7", X"1023", X"f7b2", X"0233", X"f8a8", X"f883", X"f976", X"e889", X"f5d6", X"12b6", X"0247", X"0979", X"f789",
                                                        X"e3a6", X"f543", X"f5c9", X"ec52", X"03a6", X"0197", X"028f", X"f547", X"fb69", X"e8b1", X"f4bb", X"ff06", X"f78c", X"f500",
                                                        X"0089", X"f39e", X"01e5", X"f7ef", X"f14f", X"0852", X"f124", X"f763", X"edaa", X"e67d", X"f812", X"e6ea", X"0299", X"f46e",
                                                        X"ee1a", X"0b49", X"03e9", X"ef7b", X"ffde", X"0ae9", X"0339", X"04c9", X"f1e8", X"f6f8", X"f5cf", X"ead7", X"f70c", X"fa33",
                                                        X"e450", X"ee54", X"feaf", X"0441", X"0049", X"fda1", X"f213", X"ff41", X"f95c", X"f8d7", X"024e", X"f967", X"eff2", X"fda8",
                                                        X"fb18", X"f8de", X"03e6", X"f982", X"fd71", X"f86e", X"0adf", X"ec73", X"ff8c", X"0044", X"eee4", X"fcff", X"f6ca", X"f962",
                                                        X"f4a9", X"018f", X"fe23", X"f2b1", X"00b2", X"02b8", X"ffb1", X"e9b4", X"eb96", X"ff49", X"feb3", X"f154", X"ef7f", X"f9be",
                                                        X"f3e8", X"f88a", X"014c", X"f42d", X"fdff", X"f7a1", X"fbbb", X"0d02", X"03f2", X"f02d", X"e1fb", X"05e9", X"0df8", X"0586",
                                                        X"f249", X"ff88", X"f0da", X"ffc8");
  SIGNAL data_int                         : std_logic_vector(DataWidth - 1 DOWNTO 0) := X"ffc8";
  SIGNAL addr_unsigned                    : unsigned(AddrWidth - 1 DOWNTO 0);  -- generic width

BEGIN
  addr_unsigned <= unsigned(addr);

  SinglePortRAM_generic_process: PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF enb = '1' THEN
        IF we = '1' THEN
          ram(to_integer(addr_unsigned)) <= din;
          data_int <= din;
        ELSE
          data_int <= ram(to_integer(addr_unsigned));
        END IF;
      END IF;
    END IF;
  END PROCESS SinglePortRAM_generic_process;

  dout <= data_int;

END rtl;

