-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/amc_model_w16a16/amc_cnn_16w16a_src_SinglePortRAM_generic_block371.vhd
-- Created: 2023-07-03 13:16:52
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: amc_cnn_16w16a_src_SinglePortRAM_generic_block371
-- Source Path: amc_model_w16a16/DUT HDL/Dense Layer 1/Dense Layer 1/Weight Storage21/SinglePortRAM_generic
-- Hierarchy Level: 4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY amc_cnn_16w16a_src_SinglePortRAM_generic_block371 IS
  GENERIC( AddrWidth                      : integer := 1;
           DataWidth                      : integer := 1
           );
  PORT( clk                               :   IN    std_logic;
        enb                               :   IN    std_logic;
        din                               :   IN    std_logic_vector(DataWidth - 1 DOWNTO 0);  -- generic width
        addr                              :   IN    std_logic_vector(AddrWidth - 1 DOWNTO 0);  -- generic width
        we                                :   IN    std_logic;  -- ufix1
        dout                              :   OUT   std_logic_vector(DataWidth - 1 DOWNTO 0)  -- generic width
        );
END amc_cnn_16w16a_src_SinglePortRAM_generic_block371;


ARCHITECTURE rtl OF amc_cnn_16w16a_src_SinglePortRAM_generic_block371 IS

  -- Local Type Definitions
  TYPE ram_type IS ARRAY (2**AddrWidth - 1 DOWNTO 0) of std_logic_vector(DataWidth - 1 DOWNTO 0);

  -- Signals
  SIGNAL ram                              : ram_type := (X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"1ef8", X"20a1", X"09e9", X"e198", X"e8d3", X"e2e2",
                                                        X"0268", X"0cd3", X"ff42", X"0e38", X"2863", X"09a4", X"dfb0", X"0454", X"f13b", X"280f", X"2eb5", X"0a17", X"02c4", X"e25a",
                                                        X"10c5", X"1945", X"0909", X"0d69", X"0781", X"1154", X"15de", X"16da", X"08b4", X"1e8c", X"0a1d", X"2991", X"1fec", X"e68e",
                                                        X"ecf7", X"1c2d", X"e1c6", X"f0a5", X"10ab", X"dc93", X"f07c", X"dfc6", X"013c", X"e783", X"ea6e", X"de75", X"f88e", X"fc4d",
                                                        X"16cd", X"1ebf", X"fb8a", X"191d", X"1dbf", X"e874", X"08ec", X"090c", X"2368", X"1461", X"1773", X"004a", X"d205", X"f371",
                                                        X"07eb", X"df0a", X"1aa6", X"f6f7", X"eb0d", X"d8b9", X"d86e", X"110e", X"0b6f", X"0e19", X"fdf3", X"efdc", X"18d1", X"0f29",
                                                        X"0e58", X"0e4b", X"1585", X"f4f4", X"ffb9", X"1108", X"edac", X"d112", X"e7b8", X"fc27", X"017e", X"ecff", X"f80c", X"f59b",
                                                        X"00ba", X"ff3c", X"2510", X"daec", X"0a40", X"f4c4", X"fde6", X"05ac", X"01d8", X"0330", X"eaae", X"0b2f", X"0acc", X"f876",
                                                        X"f3ed", X"07eb", X"1468", X"ec47", X"ec38", X"1433", X"f2b6", X"1fd0", X"188d", X"256f", X"04d6", X"de74", X"f3d1", X"ea29",
                                                        X"113e", X"f399", X"f728", X"0320", X"1cc1", X"ff2d", X"f7c6", X"fbea", X"fd29", X"1854", X"eb0a", X"e155", X"ea3e", X"fcd4",
                                                        X"209c", X"f466", X"fc59", X"012b", X"0081", X"e5cd", X"df21", X"0ea7", X"01f0", X"e52d", X"f515", X"fe03", X"1cd0", X"11c9",
                                                        X"fdbd", X"d7ae", X"fcc6", X"dd08", X"05da", X"e9b4", X"1c09", X"1d1a", X"16e2", X"1a8f", X"15bd", X"ff13", X"f2d8", X"090d",
                                                        X"2dcd", X"dd97", X"f39a", X"fe25", X"242c", X"06d8", X"0e20", X"f126", X"1430", X"e11c", X"28f4", X"e254", X"11f8", X"e647",
                                                        X"fc7f", X"fa4b", X"e44a", X"0236", X"0eff", X"f512", X"ef8d", X"05b0", X"f15f", X"0cb5", X"e865", X"f57a", X"f94b", X"1ddc",
                                                        X"0c1f", X"1775", X"e610", X"0914", X"15f5", X"1dde", X"f07f", X"e624", X"0a49", X"ff7d", X"f5f6", X"0abc", X"204a", X"fab4",
                                                        X"346b", X"ee7d", X"249c", X"f560", X"e9ba", X"1fa6", X"ffca", X"da48", X"f079", X"e53a", X"f81a", X"f57d", X"eab5", X"f117",
                                                        X"06ab", X"f592", X"0e14", X"ed2c", X"0316", X"f8c9", X"0214", X"232e", X"0898", X"f72f", X"04c6", X"1a80", X"f8dc", X"e705",
                                                        X"f3b1", X"ef44", X"211f", X"09b7", X"e7b9", X"d1f3", X"ec42", X"1e33", X"f390", X"0307", X"f57a", X"e1a7", X"ff59", X"047d",
                                                        X"27fc", X"f62b", X"0adc", X"0231", X"e08a", X"0f5f", X"e6de", X"fa7f", X"1d66", X"1c39", X"ff6b", X"093a", X"df40", X"1584",
                                                        X"e04a", X"196c", X"25f1", X"f83a", X"262d", X"00d2", X"16ed", X"de03", X"da06", X"079e", X"fb94", X"f5ae", X"ed06", X"16d6",
                                                        X"1576", X"0c62", X"ec0d", X"18a2", X"d2aa", X"fb38", X"e389", X"06ce", X"e18c", X"eea5", X"e0f8", X"cdb0", X"fc37", X"0f7a",
                                                        X"ffa5", X"0d0f", X"fdc4", X"e98e", X"ff86", X"0483", X"fad8", X"e5e5", X"f300", X"e3e5", X"061e", X"f059", X"f697", X"de33",
                                                        X"ebc4", X"1f17", X"0c59", X"f1c3", X"1ae2", X"0abe", X"0286", X"d2ad", X"e24a", X"eab0", X"076b", X"1268", X"fad9", X"1058",
                                                        X"04c0", X"f900", X"092b", X"f0a0", X"ed85", X"deed", X"f4ab", X"d735", X"117f", X"0dd8", X"fe58", X"23ae", X"0edc", X"e54e",
                                                        X"f882", X"fb11", X"f629", X"1859", X"02e5", X"f222", X"f897", X"0de0", X"eb8e", X"085c", X"0a95", X"ce20", X"0432", X"1de2",
                                                        X"1023", X"f3d1", X"e822", X"f1fb", X"08fc", X"0824", X"ef6c", X"f3e0", X"eacb", X"20ea", X"2d61", X"1e6b", X"1dd8", X"d5fb",
                                                        X"f59d", X"f7bd", X"070f", X"0ef6", X"05f7", X"01e5", X"0527", X"0463", X"e5c8", X"1e54", X"fb0b", X"37de", X"f14c", X"fb68",
                                                        X"0ea7", X"f80f", X"f9bc", X"1a7a", X"f137", X"fae7", X"1510", X"f2c0", X"1ac8", X"0be7", X"20db", X"062e", X"e544", X"f09b",
                                                        X"f02a", X"fe14", X"2393", X"1720", X"3ecf", X"334d", X"1103", X"1bea", X"293a", X"43f1", X"fd4d", X"1088", X"249d", X"fcdb",
                                                        X"f087", X"f40f", X"3719", X"f045", X"efa9", X"1688", X"1708", X"1a56", X"39c1", X"2372", X"2a90", X"0248", X"116b", X"3134",
                                                        X"fe34", X"eb83", X"07e6", X"047c", X"0e6a", X"f7b7", X"1a1b", X"0dfa", X"1cb3", X"1b53", X"2818", X"eab4", X"d53a", X"0fbc",
                                                        X"3433", X"2108", X"0b71", X"2997", X"0826", X"2935", X"2c2b", X"211f", X"00ab", X"e81b", X"ec49", X"3671", X"f7a2", X"fb8d",
                                                        X"1d68", X"ed30", X"09d3", X"0b1a", X"dd01", X"ebe5", X"db0e", X"ea06", X"2073", X"20f0", X"0ac7", X"0e56", X"1333", X"eb0e",
                                                        X"e632", X"0e45", X"20d7", X"fd0a", X"1bf9", X"10b0", X"0449", X"0686", X"f3cb", X"f058", X"288a", X"0695", X"f3c4", X"e556",
                                                        X"1307", X"df12", X"0b20", X"faf2", X"ea6b", X"1f08", X"ea68", X"09c1", X"2cb6", X"1d48", X"fc7f", X"e12c", X"f5fb", X"05a9",
                                                        X"db98", X"048c", X"1bb2", X"f47e", X"fc65", X"e4de", X"08e1", X"f233", X"eef8", X"d423", X"e368", X"fad6", X"ec68", X"0bd7",
                                                        X"ee23", X"f2ce", X"e169", X"1152", X"066d", X"18b4", X"13e8", X"e0da", X"daaa", X"ddfe", X"f08c", X"f782", X"0f77", X"1886",
                                                        X"fc7b", X"1d76", X"0ba2", X"1fb2", X"1779", X"cafa", X"0236", X"da59", X"20a5", X"16cf", X"d236", X"f2b3", X"eeec", X"19b1",
                                                        X"05fa", X"ef41", X"ebbc", X"fd6f", X"eab7", X"f0d6", X"f15f", X"22ec", X"d62b", X"f0d3", X"dca7", X"0d72", X"eb0c", X"16f2",
                                                        X"1269", X"e9d2", X"dc2c", X"e574", X"e6c5", X"0f6b", X"fe00", X"f939", X"015b", X"0c2b", X"fd06", X"e429", X"1257", X"e7fa",
                                                        X"dfff", X"e553", X"0e55", X"0c1b", X"e06c", X"08d8", X"1393", X"10b9", X"e67a", X"03ba", X"eab1", X"e97d", X"db38", X"1331",
                                                        X"0675", X"eeb4", X"0205", X"e0b8", X"ffc1", X"e2dd", X"e5ed", X"fca3", X"ff0c", X"ed95", X"07c6", X"f728", X"f91f", X"e81b",
                                                        X"0adf", X"03f9", X"ec6f", X"21ac", X"12bc", X"f153", X"ed94", X"06cc", X"e923", X"20c6", X"fde7", X"0e88", X"1c8f", X"13c6",
                                                        X"e928", X"d746", X"20f9", X"059c", X"000b", X"eb17", X"d912", X"217d", X"f066", X"f863", X"f97b", X"ecd6", X"0eae", X"0a98",
                                                        X"ee20", X"0650", X"f09e", X"e4ae", X"e457", X"01d7", X"1bd6", X"f7c3", X"d161", X"ff85", X"2a52", X"ecc2", X"e0d0", X"eb83",
                                                        X"13d2", X"125f", X"05ee", X"1565", X"0446", X"f735", X"f7a7", X"08e7", X"f440", X"fd73", X"0cce", X"f3ad", X"1e34", X"07ff",
                                                        X"d8ac", X"fa39", X"ed63", X"1250", X"1c60", X"0e41", X"f69a", X"15c4", X"ffd0", X"06f8", X"ffa1", X"f13e", X"d96d", X"0f9a",
                                                        X"1d56", X"ef4d", X"f6f1", X"fa4f", X"fe24", X"084a", X"dab2", X"0db5", X"0d16", X"0932", X"f108", X"0ad9", X"fcd9", X"f48e",
                                                        X"c715", X"eaa1", X"0af2", X"ed0b", X"1cb3", X"e948", X"08cd", X"069c", X"f220", X"f462", X"0bac", X"01b1", X"da81", X"1240",
                                                        X"039b", X"f3ef", X"1104", X"e937", X"ec2b", X"f3eb", X"092c", X"f2b6", X"eddc", X"0413", X"1498", X"e807", X"e6d1", X"e8f8",
                                                        X"ea15", X"dc56", X"10f3", X"1983", X"f29c", X"fc09", X"f92c", X"fb11", X"f55b", X"06ad", X"0c30", X"fbb6", X"019f", X"13fc",
                                                        X"ea33", X"1929", X"f6d9", X"fa05", X"1f67", X"e634", X"1d93", X"12a9", X"eda6", X"fe1c", X"decc", X"ea27", X"e75e", X"f454",
                                                        X"2382", X"08fc", X"fbc3", X"f6aa", X"0d1f", X"0303", X"fe02", X"fbcc", X"ef8d", X"ef3a", X"ff8c", X"e684", X"ed1b", X"2084",
                                                        X"fb63", X"ffbc", X"f9f9", X"1841", X"fbd9", X"1e00", X"1171", X"024f", X"ef2d", X"16e1", X"2c0d", X"15f6", X"2996", X"dd98",
                                                        X"dcab", X"fa17", X"0d2b", X"1a46", X"df34", X"03f1", X"0111", X"0c1f", X"049a", X"318a", X"ffc0", X"11fa", X"dd66", X"044f",
                                                        X"fc67", X"202b", X"ed84", X"f275", X"0248", X"13bc", X"0a39", X"2671", X"0ca4", X"10f5", X"2e65", X"107e", X"2741", X"ea43",
                                                        X"0ddb", X"05b7", X"ea74", X"1004", X"1c4c", X"e6d3", X"f9fd", X"f3c6", X"1a01", X"0954", X"1427", X"0de8", X"2549", X"3ac4",
                                                        X"fcec", X"1885", X"db93", X"0033", X"2f49", X"178a", X"2f89", X"1021", X"2b4a", X"24c2", X"3a67", X"1821", X"10a9", X"facd",
                                                        X"21e8", X"0bea", X"1123", X"02fe", X"1173", X"079a", X"10fb", X"1ac9", X"0227", X"21fc", X"fb18", X"259d", X"1e14", X"1e00",
                                                        X"e3eb", X"35eb", X"0625", X"1189", X"1eb6", X"0f8b", X"ef0d", X"06a9", X"0031", X"f9b5", X"eb9c", X"17ee", X"ec3a", X"28cd",
                                                        X"3526", X"06a4", X"04a7", X"d0dd", X"1b49", X"1c86", X"1749", X"fae0", X"efd5", X"1930", X"0761", X"010c", X"1782", X"1095",
                                                        X"0471", X"0739", X"ea22", X"0471", X"f6e2", X"0698", X"f84b", X"0c75", X"046f", X"fd46", X"0033", X"0189", X"ef87", X"0d0a",
                                                        X"18e8", X"ffb2", X"0465", X"ecc8", X"e54d", X"0978", X"f31f", X"fb6f", X"056c", X"ecfe", X"f860", X"1434", X"fc50", X"f989",
                                                        X"f7c6", X"eff0", X"1034", X"1cd9", X"074e", X"1d95", X"e726", X"e31e", X"fc21", X"d6a9", X"f117", X"13df", X"184b", X"03ec",
                                                        X"0a3b", X"fcb6", X"e133", X"e770", X"f3ba", X"f461", X"01fc", X"05bd", X"d874", X"f99d", X"ef74", X"e843", X"de1d", X"db2c",
                                                        X"0145", X"0500", X"111f", X"e4e2", X"e034", X"fce2", X"dde2", X"0877", X"e0e9", X"f1cd", X"d560", X"05df", X"dd17", X"eba3",
                                                        X"e6a1", X"c471", X"ec6e", X"f8bb", X"fe95", X"d246", X"e628", X"ed0c", X"f398", X"fd31", X"f372", X"e829", X"fd27", X"edea",
                                                        X"da77", X"ea84", X"fbe2", X"cab6", X"0044", X"ec4a", X"f18d", X"01f8", X"e9c8", X"ddcd", X"da4f", X"d887", X"f02a", X"e5ec",
                                                        X"f735", X"fea8", X"fcaa", X"f4ad", X"e67b", X"cd2b", X"d7b6", X"fe8c", X"ed2a", X"e920", X"e46c", X"0538", X"fb11", X"0b69",
                                                        X"f898", X"0fde", X"db82", X"e961", X"f9de", X"eb14", X"f1dc", X"d366", X"f6cb", X"0f5e", X"1ed5", X"0fa5", X"19b5", X"e256",
                                                        X"0265", X"ea32", X"fbd8", X"09f7", X"ffaf", X"f0aa", X"16f8", X"05e0", X"2761", X"fa20", X"097f", X"0927", X"e6c5", X"20c9",
                                                        X"e91d", X"0238", X"0843", X"1683", X"feda", X"ee8f", X"1940", X"116f", X"17ee", X"ed77", X"ffdd", X"092a", X"f800", X"edea",
                                                        X"df63", X"f4ce", X"1d23", X"02ba", X"d906", X"ea68", X"ea95", X"12d6", X"f11a", X"f878", X"0ae9", X"eeb5", X"2efa", X"17df",
                                                        X"1a3d", X"f86c", X"07b5", X"fb6b", X"020e", X"1688", X"e09e", X"f94c", X"0fb8", X"0ece", X"f01c", X"f742", X"1cf9", X"0e13",
                                                        X"2128", X"22f2", X"ef5a", X"dc3d", X"23f4", X"eaec", X"0799", X"1b57", X"e5d3", X"e97e", X"0f9f", X"1f2d", X"05e9", X"1439",
                                                        X"e829", X"2583", X"f919", X"fa0f", X"0d0a", X"eec9", X"1d88", X"f930", X"1321", X"1700", X"007d", X"1486", X"121d", X"0389",
                                                        X"00d4", X"21d8", X"e3f0", X"f164", X"e98a", X"f7e2", X"01d5", X"003d", X"fbee", X"fae7", X"1495", X"fc28", X"0fd2", X"19a1",
                                                        X"fd42", X"0eda", X"0b53", X"0be8", X"19e7", X"d56d", X"10c6", X"ff83", X"fcfc", X"0515", X"0934", X"f6ba", X"efd1", X"eed9",
                                                        X"2387", X"133a", X"f523", X"23a3", X"0c84", X"0bdb", X"f356", X"cf65", X"07b3", X"1a77", X"015b", X"1cf7", X"df1f", X"fd22",
                                                        X"0ba8", X"06be", X"1e7a", X"f512", X"16dd", X"2534", X"ef40", X"0d61", X"f81b", X"10b0", X"ec17", X"ea4b", X"1b0c", X"e96d",
                                                        X"0c05", X"06fe", X"1dac", X"fdd2", X"17c3", X"f029", X"044c", X"f8ee", X"1f46", X"0914", X"f71d", X"e968", X"f2a5", X"e22b",
                                                        X"0439", X"0ab3", X"e81d", X"16f6", X"e70c", X"e351", X"e4c3", X"03f8", X"14d4", X"0e99", X"0ab7", X"0a7a", X"17ab", X"1800",
                                                        X"f2d1", X"ff3b", X"08d5", X"e367", X"08a5", X"fc3d", X"f87a", X"11c2", X"fcbc", X"1301", X"fd1a", X"fd7b", X"e9a7", X"e024",
                                                        X"07c2", X"d7b4", X"04db", X"0c77", X"e565", X"1759", X"f58e", X"cefd", X"f601", X"1203", X"cefd", X"ed40", X"0277", X"08e9",
                                                        X"e70e", X"e823", X"fe60", X"ed7c", X"e7ee", X"f830", X"d2c4", X"ef95", X"fab7", X"f2e5", X"05af", X"f04c", X"ffa2", X"099c",
                                                        X"fa2a", X"f5c1", X"f0c3", X"e465", X"f013", X"da7d", X"04ad", X"e0d2", X"1633", X"ffdc", X"fba2", X"03e6", X"156a", X"0a65",
                                                        X"13f6", X"f428", X"0fdb", X"ef64", X"ce49", X"dcca", X"ef7c", X"129e", X"ecee", X"f970", X"e9d4", X"cfca", X"d666", X"1403",
                                                        X"ebb1", X"f61b", X"0973", X"e11e", X"ec5b", X"f9d5", X"e9b3", X"09b4", X"12bc", X"df0a", X"f605", X"f9d6", X"069d", X"02ae",
                                                        X"1637", X"f9fc", X"f0fb", X"fc89", X"1347", X"1503", X"f951", X"f602", X"f713", X"e5c7", X"0088", X"f1b1", X"de01", X"0526",
                                                        X"d1ff", X"17e4", X"ec0c", X"dae3", X"1e5c", X"013d", X"f3c5", X"d019", X"f346", X"e3fd", X"fe46", X"eafe", X"eac2", X"19e2",
                                                        X"23fe", X"dc56", X"f86d", X"dc68", X"1295", X"f38e", X"f7b4", X"0bee", X"16db", X"129a", X"f2b5", X"101c", X"145f", X"259f",
                                                        X"ec5c", X"fd65", X"eda7", X"e1b0", X"15f7", X"0369", X"00a8", X"edad", X"1b91", X"f0f1", X"1437", X"df78", X"117a", X"f465",
                                                        X"0683", X"fa07", X"30d2", X"dd2a", X"f4d5", X"0890", X"0138", X"13d9", X"3916", X"1212", X"1b84", X"0ae9", X"fe0d", X"eb89",
                                                        X"1722", X"ffcb", X"30fc", X"2616", X"2223", X"01fb", X"1cf3", X"28f8", X"38c3", X"0e83", X"27a1", X"3095", X"44b9", X"02cd",
                                                        X"0c48", X"f293", X"0f1f", X"3531", X"f939", X"180c", X"02f1", X"e033", X"fc36", X"1bdb", X"3628", X"070d", X"345f", X"1821",
                                                        X"fb4c", X"1f06", X"3483", X"1a00", X"0683", X"2d59", X"2713", X"326e", X"1885", X"eb00", X"32d9", X"0e98", X"0e47", X"2f02",
                                                        X"f20c", X"2883", X"fb48", X"f48a", X"1772", X"ff8a", X"fba9", X"1a91", X"13f8", X"10eb", X"e0eb", X"e82f", X"2a98", X"40ea",
                                                        X"2bd2", X"098d", X"3970", X"1a0e", X"05ad", X"1a1c", X"03cc", X"fbce", X"1986", X"105f", X"2211", X"2166", X"fbf2", X"264b",
                                                        X"2561", X"109e", X"f3e7", X"1de4", X"e2aa", X"1f68", X"1dc4", X"fc94", X"2aa2", X"2774", X"0f94", X"f0f6", X"daec", X"fb77",
                                                        X"090c", X"0650", X"ee6a", X"1c8a", X"1585", X"f986", X"039f", X"e2e0", X"fb65", X"ebbc", X"ecf7", X"e612", X"f7b0", X"2208",
                                                        X"17c6", X"1221", X"fee1", X"f542", X"1ca7", X"e85e", X"fe97", X"0ece", X"cd8d", X"0548", X"fba3", X"095a", X"dff5", X"f351",
                                                        X"ebd7", X"f01b", X"014c", X"f35e", X"f163", X"e9c3", X"defc", X"f705", X"06d2", X"070b", X"166d", X"0243", X"dd64", X"d23a",
                                                        X"fe10", X"009b", X"fd7b", X"df7a", X"d9c5", X"0701", X"dec8", X"0e28", X"fb15", X"decd", X"e5a8", X"f145", X"d109", X"e490",
                                                        X"d8d2", X"0009", X"1078", X"f7e8", X"f3d1", X"e390", X"0332", X"eda6", X"f8fa", X"e63b", X"ecf8", X"e7f1", X"0295", X"cb6e",
                                                        X"e639", X"deb0", X"e61b", X"e7ad", X"eb34", X"d8d6", X"ef9d", X"f803", X"d5be", X"eab1", X"dd71", X"fdca", X"0371", X"dd7b",
                                                        X"e9cd", X"ecab", X"faf9", X"fb96", X"d294", X"03b6", X"ea27", X"0e59", X"eaac", X"d597", X"cd6d", X"e4d6", X"df0d", X"d56b",
                                                        X"e7c4", X"e31c", X"ef3a", X"f000", X"e6d8", X"e537", X"d905", X"ee83", X"ff09", X"ff33", X"f0cc", X"d52a", X"cb88", X"f99a",
                                                        X"1433", X"ede6", X"e3f1", X"f157", X"feb1", X"f60f", X"d8ca", X"e61e", X"1061", X"03d3", X"01cc", X"e200", X"1981", X"111e",
                                                        X"e94d", X"ceab", X"f774", X"21c6", X"e2c1", X"eeca", X"f51e", X"fe49", X"e2b6", X"f2f8", X"1012", X"e12f", X"070f", X"e925",
                                                        X"07d7", X"e54d", X"eba3", X"1004", X"f600", X"eefb", X"09cd", X"ff52", X"1329", X"165e", X"18cf", X"feaa", X"0cd2", X"1e43",
                                                        X"1c0b", X"faad", X"0e02", X"06c1", X"f6cc", X"fc25", X"ecba", X"0b3e", X"21fd", X"17f3", X"e3ed", X"18f6", X"07f2", X"fab6",
                                                        X"0cee", X"062a", X"0e12", X"f112", X"fb03", X"f05e", X"2545", X"4346", X"1a23", X"0cbd", X"f4ff", X"3220", X"2698", X"efeb",
                                                        X"eddc", X"14b8", X"f00d", X"f9e8", X"1fd0", X"30ed", X"059b", X"1f21", X"074b", X"1167", X"2216", X"1996", X"4934", X"364e",
                                                        X"fbe1", X"24ca", X"1d09", X"16b8", X"3b43", X"2314", X"188a", X"f9fe", X"0e0b", X"1308", X"07eb", X"1c87", X"ecf2", X"307e",
                                                        X"08fb", X"fcfa", X"2264", X"202e", X"f3f6", X"224d", X"1fb5", X"048f", X"1e88", X"04c0", X"f796", X"2e43", X"33ce", X"0c3d",
                                                        X"e6ee", X"e533", X"3b08", X"02d8", X"1a06", X"eeba", X"1584", X"1733", X"2d93", X"22fa", X"db9f", X"f298", X"dd5b", X"2dd6",
                                                        X"33f4", X"0abf", X"0c4d", X"fd24", X"e2ff", X"32c7", X"0c63", X"0396", X"0661", X"ee7e", X"1972", X"0846", X"de87", X"10c1",
                                                        X"057d", X"e668", X"0ffb", X"1661", X"f254", X"0284", X"09d7", X"ed85", X"012d", X"1c26", X"0d3e", X"f399", X"18c6", X"018f",
                                                        X"0ada", X"e679", X"043f", X"e87e", X"1768", X"ebda", X"e6f6", X"fa2e", X"023f", X"07c7", X"1020", X"f46f", X"1d24", X"00a9",
                                                        X"2329", X"06a6", X"0cc4", X"069a", X"eb12", X"df70", X"07cd", X"0bd0", X"0f78", X"1763", X"ff3a", X"e493", X"f041", X"e8e1",
                                                        X"dce6", X"10e8", X"eff9", X"02d3", X"fa07", X"ebe9", X"0101", X"f928", X"f9ea", X"0fdb", X"eb98", X"fbb8", X"f8a2", X"f90e",
                                                        X"e1ba", X"017e", X"038f", X"f7fc", X"e1a0", X"261c", X"0a71", X"0d68", X"04a3", X"eb5b", X"01fb", X"e7d3", X"e848", X"ee12",
                                                        X"e617", X"dfbe", X"f59b", X"d8a9", X"cfce", X"f7d0", X"0baf", X"ddd8", X"14f4", X"1c55", X"04dd", X"ff95", X"114f", X"fed4",
                                                        X"eb6d", X"17c1", X"eeda", X"e597", X"ea6a", X"f85c", X"f967", X"e46e", X"fd38", X"0190", X"0758", X"e075", X"e619", X"ee1b",
                                                        X"e16e", X"f081", X"f7bc", X"d489", X"09aa", X"dc6d", X"ef78", X"049d", X"0760", X"e961", X"17da", X"06c6", X"ea06", X"fd56",
                                                        X"e1bb", X"fdf3", X"fa71", X"e909", X"e1b6", X"0faa", X"faed", X"e378", X"0f55", X"e7e2", X"16c5", X"1479", X"1762", X"0212",
                                                        X"dd6c", X"1161", X"f19d", X"1e0c", X"17de", X"0ded", X"0e1f", X"d3f3", X"0719", X"f529", X"f70f", X"1781", X"dbc1", X"d771",
                                                        X"f467", X"1b2e", X"de5f", X"fb1b", X"ff66", X"de3f", X"0572", X"e58a", X"e585", X"031e", X"f6dc", X"1625", X"f8a9", X"07c6",
                                                        X"111a", X"0ef4", X"ec90", X"f03c", X"e6af", X"0d59", X"fcbd", X"1260", X"ea78", X"1e94", X"125d", X"0bb2", X"04f7", X"0608",
                                                        X"1e63", X"fbb8", X"dcf5", X"11fe", X"1312", X"f0ee", X"eed4", X"2452", X"0324", X"f909", X"0038", X"f0fc", X"f3dd", X"d1fc",
                                                        X"0a8a", X"efe6", X"176b", X"0457", X"01f0", X"f9d0", X"00a5", X"0c4f", X"fdbb", X"de80", X"0b26", X"fdc9", X"f6fb", X"14b8",
                                                        X"00e6", X"157e", X"e7d7", X"0755", X"0726", X"1d0d", X"08c2", X"e6a7", X"e502", X"0f9e", X"f1f8", X"09b9", X"e1ac", X"0598",
                                                        X"0eda", X"e9b5", X"1661", X"f000", X"ee39", X"f37c", X"fce2", X"0c23", X"fd8a", X"1e85", X"0103", X"e4ed", X"f797", X"1c5c",
                                                        X"e1fc", X"f156", X"0074", X"18e3", X"01dc", X"e647", X"f4ac", X"10c8", X"f502", X"09b5", X"f610", X"1da1", X"0928", X"0114",
                                                        X"ee08", X"e83e", X"f91b", X"1845", X"04e6", X"f021", X"f9df", X"058d", X"0bfa", X"ec6f", X"09d0", X"e93c", X"d40a", X"131c",
                                                        X"1c0c", X"edb1", X"0582", X"110b", X"f545", X"f416", X"1cf8", X"edd4", X"0e43", X"f098", X"da5b", X"e827", X"e2b8", X"f791",
                                                        X"f8be", X"0a08", X"08e7", X"e8c4", X"144d", X"0f4f", X"ec63", X"1f88", X"f258", X"de5a", X"1198", X"fbb5", X"ec14", X"0d14",
                                                        X"dd3e", X"ed9b", X"0e08", X"f1b8", X"149f", X"dec0", X"f60c", X"185f", X"f50e", X"081e", X"0261", X"fd3e", X"ee06", X"15e1",
                                                        X"0036", X"2b53", X"ea60", X"0814", X"e54c", X"e9e8", X"ff72", X"1a63", X"036a", X"dc6e", X"f449", X"ed7e", X"20d3", X"fb7f",
                                                        X"029c", X"fc57", X"0179", X"ea25", X"2057", X"072d", X"fc50", X"ed7d", X"f137", X"e575", X"27fc", X"0ae0", X"ee14", X"0de7",
                                                        X"f756", X"fe59", X"03fd", X"1e12", X"16fd", X"f69e", X"00ca", X"00a9", X"e15c", X"fea2", X"0018", X"fb78", X"0945", X"e773",
                                                        X"1bd7", X"1b11", X"11ea", X"0b9f", X"ff59", X"d320", X"f054", X"f5ae", X"f069", X"e53e", X"d7ec", X"f11d", X"12ac", X"16d2",
                                                        X"0912", X"1fac", X"fe07", X"06f0");
  SIGNAL data_int                         : std_logic_vector(DataWidth - 1 DOWNTO 0) := X"06f0";
  SIGNAL addr_unsigned                    : unsigned(AddrWidth - 1 DOWNTO 0);  -- generic width

BEGIN
  addr_unsigned <= unsigned(addr);

  SinglePortRAM_generic_process: PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF enb = '1' THEN
        IF we = '1' THEN
          ram(to_integer(addr_unsigned)) <= din;
          data_int <= din;
        ELSE
          data_int <= ram(to_integer(addr_unsigned));
        END IF;
      END IF;
    END IF;
  END PROCESS SinglePortRAM_generic_process;

  dout <= data_int;

END rtl;

