-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/amc_model_w16a16/amc_cnn_16w16a_src_SinglePortRAM_generic_block405.vhd
-- Created: 2023-07-03 13:16:56
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: amc_cnn_16w16a_src_SinglePortRAM_generic_block405
-- Source Path: amc_model_w16a16/DUT HDL/Dense Layer 1/Dense Layer 1/Weight Storage52/SinglePortRAM_generic
-- Hierarchy Level: 4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY amc_cnn_16w16a_src_SinglePortRAM_generic_block405 IS
  GENERIC( AddrWidth                      : integer := 1;
           DataWidth                      : integer := 1
           );
  PORT( clk                               :   IN    std_logic;
        enb                               :   IN    std_logic;
        din                               :   IN    std_logic_vector(DataWidth - 1 DOWNTO 0);  -- generic width
        addr                              :   IN    std_logic_vector(AddrWidth - 1 DOWNTO 0);  -- generic width
        we                                :   IN    std_logic;  -- ufix1
        dout                              :   OUT   std_logic_vector(DataWidth - 1 DOWNTO 0)  -- generic width
        );
END amc_cnn_16w16a_src_SinglePortRAM_generic_block405;


ARCHITECTURE rtl OF amc_cnn_16w16a_src_SinglePortRAM_generic_block405 IS

  -- Local Type Definitions
  TYPE ram_type IS ARRAY (2**AddrWidth - 1 DOWNTO 0) of std_logic_vector(DataWidth - 1 DOWNTO 0);

  -- Signals
  SIGNAL ram                              : ram_type := (X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"04e4", X"1fce", X"ebde", X"f972", X"0ac7", X"235e",
                                                        X"e049", X"32b6", X"fba3", X"b2c5", X"e21d", X"00bf", X"f648", X"f25d", X"feaa", X"ff6f", X"f2b2", X"09d5", X"edf0", X"ded1",
                                                        X"06fb", X"1acb", X"146e", X"05d5", X"26b6", X"d366", X"f05e", X"f76e", X"079b", X"2a09", X"f0c9", X"08cc", X"f39e", X"0915",
                                                        X"102c", X"eb64", X"0ab6", X"18c8", X"fbd1", X"fc8e", X"16a4", X"ed7d", X"fb53", X"0b23", X"ea5e", X"f6bc", X"f59d", X"f4d8",
                                                        X"0d5a", X"f8fc", X"104f", X"3353", X"02dc", X"14cc", X"17a4", X"f636", X"2eeb", X"20e4", X"0d2e", X"0547", X"e27e", X"241f",
                                                        X"f1ef", X"0658", X"0f3d", X"1f4c", X"f157", X"d99a", X"085f", X"eb38", X"3039", X"eb2f", X"ce5b", X"096b", X"11be", X"f4f2",
                                                        X"f632", X"eb4a", X"ee65", X"f00f", X"0c65", X"07c5", X"013d", X"012c", X"0ed5", X"f9e4", X"0bfb", X"ec60", X"0cf1", X"1af8",
                                                        X"e918", X"1007", X"e55d", X"02d0", X"daee", X"f6de", X"041c", X"ed42", X"02f2", X"e4d8", X"09f1", X"0f56", X"fa38", X"d865",
                                                        X"d2c3", X"1c87", X"ed0d", X"f896", X"eacc", X"fa1b", X"e0e9", X"fe3d", X"e77d", X"f31a", X"f935", X"e85c", X"02f3", X"0254",
                                                        X"07e2", X"c38d", X"1493", X"076c", X"05e1", X"0bef", X"1683", X"0d82", X"f053", X"0db9", X"0893", X"e9ec", X"e214", X"1665",
                                                        X"2125", X"1d80", X"042f", X"d717", X"0ed4", X"0820", X"03ad", X"ffd6", X"e7ca", X"04e7", X"0157", X"01f0", X"1fee", X"0133",
                                                        X"0e24", X"eb49", X"07bf", X"20d2", X"eff4", X"e638", X"0261", X"f769", X"f9d4", X"eed7", X"e8bb", X"f508", X"26b2", X"0ca3",
                                                        X"0d22", X"f7dc", X"fa3c", X"f6b7", X"1993", X"2212", X"055e", X"ed68", X"1dfb", X"337a", X"f3af", X"0ce5", X"f6a6", X"1a92",
                                                        X"17bc", X"1485", X"0c6c", X"f417", X"1083", X"2668", X"3173", X"07b9", X"1542", X"eea5", X"0d71", X"fd4c", X"faae", X"0398",
                                                        X"066d", X"027d", X"e242", X"e9db", X"29d5", X"f4bd", X"fac9", X"06e1", X"f423", X"29fb", X"0e14", X"0e00", X"041e", X"e097",
                                                        X"076a", X"fd51", X"06c3", X"182a", X"ed9b", X"e691", X"ea55", X"f4b0", X"f04d", X"0c9c", X"23a4", X"13a8", X"1326", X"1764",
                                                        X"273b", X"e572", X"fe66", X"08ed", X"0035", X"0ea5", X"dc1c", X"eb63", X"02c6", X"090c", X"ffd0", X"1a19", X"075f", X"13a0",
                                                        X"eb43", X"305b", X"0463", X"d1cc", X"eddf", X"e6e0", X"1ad8", X"11b2", X"08ec", X"021e", X"0b61", X"01c1", X"0467", X"0cf7",
                                                        X"1747", X"185b", X"f6f0", X"ff78", X"14b5", X"e140", X"fb9a", X"ef05", X"0f6b", X"0530", X"0d9e", X"04fe", X"e762", X"f295",
                                                        X"f7fd", X"1b73", X"027a", X"24e2", X"fc1b", X"0510", X"d85e", X"dec8", X"0065", X"fb4c", X"109b", X"055a", X"1170", X"0e70",
                                                        X"1b67", X"f28e", X"f4d7", X"dcb6", X"ecdc", X"0ea0", X"fbf3", X"0cf3", X"ed11", X"e071", X"e479", X"f71a", X"0c61", X"f9b5",
                                                        X"eca8", X"ee2f", X"03c3", X"f21b", X"eae6", X"f2c2", X"f473", X"05ef", X"03db", X"00b4", X"f2ce", X"dca6", X"fac1", X"0271",
                                                        X"f75a", X"fc88", X"e076", X"ec6e", X"142c", X"1a02", X"f1a5", X"3867", X"0866", X"0c3e", X"eb9e", X"020f", X"2f72", X"fb9c",
                                                        X"f20b", X"f7c2", X"ef9f", X"0d21", X"0b8c", X"ef1d", X"0cd3", X"162e", X"1a5c", X"0cca", X"0462", X"fdd5", X"eb11", X"002a",
                                                        X"e181", X"f7af", X"fb49", X"f931", X"1c1b", X"0db2", X"da7b", X"d94f", X"f2af", X"129b", X"0f1f", X"05a5", X"e6e9", X"ffb1",
                                                        X"0934", X"f8d3", X"d99e", X"fd3c", X"e078", X"0447", X"f9b2", X"027e", X"ea4c", X"e902", X"064f", X"ebb9", X"eb1b", X"ffef",
                                                        X"0dfc", X"0a20", X"0e5f", X"e068", X"e366", X"29a3", X"dc78", X"0cf0", X"f137", X"048c", X"00c9", X"faac", X"ed08", X"e8ca",
                                                        X"fe18", X"188d", X"1245", X"0e46", X"fe2e", X"f03b", X"d6f5", X"2923", X"e999", X"0186", X"fd23", X"12b8", X"edcf", X"efe7",
                                                        X"0c37", X"f4e6", X"002e", X"fbf1", X"f229", X"f026", X"0782", X"db65", X"2dfa", X"2140", X"e76f", X"f597", X"2b78", X"edb5",
                                                        X"0607", X"fa77", X"1fb6", X"f89f", X"f72f", X"13e5", X"ea9c", X"07a0", X"0c6e", X"d348", X"13ea", X"fac7", X"ff57", X"159b",
                                                        X"f88f", X"e642", X"15bb", X"0864", X"15b8", X"f442", X"f6f4", X"e3d4", X"f394", X"016f", X"fbad", X"df71", X"07bb", X"fc64",
                                                        X"15b1", X"f570", X"0d40", X"fe35", X"12a9", X"0983", X"23b4", X"f715", X"f60f", X"f1f3", X"2ff3", X"0771", X"f583", X"e415",
                                                        X"d45d", X"0884", X"1916", X"03dc", X"2feb", X"f4c3", X"0dcd", X"03db", X"04a7", X"013a", X"102c", X"dd4b", X"296b", X"0d80",
                                                        X"22ba", X"03e6", X"175e", X"f30f", X"1fa2", X"04a4", X"2a57", X"fb1e", X"08d5", X"0438", X"fc23", X"f8f5", X"104a", X"fb4d",
                                                        X"0f1a", X"2517", X"1232", X"fadf", X"1708", X"efb5", X"f8f0", X"188a", X"0b40", X"15ec", X"fe8b", X"0c80", X"241b", X"ea99",
                                                        X"f1fa", X"d6a0", X"f34e", X"0776", X"131b", X"15bd", X"ff7d", X"d976", X"e1bd", X"f265", X"016f", X"094c", X"ebab", X"ed86",
                                                        X"1c66", X"036a", X"eef7", X"1341", X"ed6c", X"1708", X"fb1e", X"f54c", X"2692", X"d2b6", X"144e", X"2320", X"0d02", X"0fd2",
                                                        X"e753", X"e300", X"1314", X"1866", X"e793", X"dbfb", X"e350", X"0860", X"f1e7", X"217c", X"d4e0", X"d91e", X"e35f", X"1105",
                                                        X"eacf", X"f4fe", X"feb9", X"f213", X"e792", X"efbd", X"0b69", X"2d19", X"e925", X"f240", X"f583", X"203f", X"e616", X"df48",
                                                        X"febf", X"efa3", X"ee4c", X"f587", X"01c0", X"0bde", X"e675", X"0123", X"095a", X"0d20", X"1e1c", X"144c", X"fe38", X"0f83",
                                                        X"151c", X"0479", X"14e0", X"1efe", X"0d78", X"2381", X"df3d", X"f4dd", X"1455", X"ec63", X"0f4d", X"2184", X"06a7", X"0050",
                                                        X"1cdf", X"eea2", X"0eb2", X"1253", X"ebe4", X"e855", X"e572", X"1eb8", X"0007", X"ff5d", X"eb6d", X"0b08", X"f19b", X"1bc2",
                                                        X"32be", X"08fe", X"0350", X"0b37", X"ee33", X"dae2", X"f82d", X"ff40", X"1a18", X"171a", X"1042", X"0e47", X"fcfb", X"12de",
                                                        X"f7f6", X"e1bf", X"0ba6", X"0f91", X"f411", X"fd5f", X"e555", X"03a1", X"f42c", X"0a59", X"ec5b", X"01ef", X"e5f2", X"0a21",
                                                        X"026a", X"0162", X"e709", X"171c", X"fa30", X"eee1", X"120a", X"dbee", X"ec67", X"f042", X"fdfd", X"f7f6", X"2059", X"f677",
                                                        X"edbf", X"ef94", X"f26b", X"e1f4", X"ef20", X"16f1", X"2613", X"f430", X"fad7", X"dca3", X"05fb", X"32aa", X"e563", X"e983",
                                                        X"19d4", X"199a", X"d023", X"f4a3", X"fbfc", X"e9bc", X"fb6e", X"15b5", X"1b29", X"0076", X"072b", X"d7ef", X"d429", X"0ddb",
                                                        X"f791", X"1de6", X"d499", X"eb86", X"f4d2", X"0518", X"02e0", X"fb94", X"e64a", X"2e3b", X"193f", X"0aa4", X"f23e", X"e77a",
                                                        X"df52", X"2a3b", X"fbc6", X"01f7", X"0a39", X"0a46", X"fd46", X"eb1d", X"fc13", X"10a7", X"02c1", X"054f", X"2711", X"0bcb",
                                                        X"f539", X"d6d0", X"f370", X"e994", X"f112", X"1b00", X"1acc", X"145c", X"0fcf", X"ee36", X"1da6", X"f492", X"121f", X"f812",
                                                        X"1a22", X"044f", X"f6ac", X"de13", X"f772", X"fba5", X"ecda", X"fe43", X"23b7", X"1c8a", X"0099", X"fab1", X"15d6", X"0fa4",
                                                        X"ffe3", X"05ad", X"fd4f", X"05d6", X"fa21", X"f67f", X"e9ba", X"e273", X"f51f", X"0721", X"2153", X"fa69", X"e69e", X"e6ed",
                                                        X"2b56", X"e643", X"02f5", X"e126", X"1780", X"1efc", X"2763", X"fc6c", X"2767", X"fb5e", X"f966", X"1e06", X"fbc7", X"22b6",
                                                        X"f6b8", X"fc16", X"fc08", X"12ae", X"fc19", X"2f3a", X"f8ad", X"0d40", X"0f01", X"1c28", X"e07f", X"0d68", X"fa33", X"13e3",
                                                        X"ef75", X"00db", X"186e", X"e775", X"08fc", X"d6bf", X"0303", X"009f", X"0c17", X"1014", X"1ce4", X"12ae", X"0b27", X"deec",
                                                        X"f57a", X"1f15", X"1c7f", X"0538", X"e30d", X"1fdb", X"001e", X"1941", X"eed2", X"2d05", X"186e", X"f220", X"fba4", X"fa67",
                                                        X"13f7", X"dcf8", X"f877", X"0747", X"189a", X"0ea4", X"db0b", X"f04e", X"0012", X"ed0e", X"f7f6", X"291a", X"0635", X"0173",
                                                        X"02bb", X"f895", X"d846", X"c866", X"01cd", X"f706", X"22b7", X"fda6", X"07bc", X"e16e", X"1321", X"1051", X"feaf", X"2c83",
                                                        X"189a", X"1b9c", X"019e", X"e980", X"0233", X"e267", X"0a34", X"0499", X"fdfd", X"eb8f", X"010b", X"1125", X"e329", X"e400",
                                                        X"f1a6", X"1f74", X"f640", X"f032", X"f89e", X"1a5c", X"ed3a", X"e8a9", X"088e", X"00cc", X"f1bf", X"2335", X"f872", X"1572",
                                                        X"1947", X"14b0", X"08ac", X"fe1c", X"1722", X"ed76", X"1af6", X"eab3", X"f8e9", X"d65a", X"ea56", X"1bb3", X"13fc", X"e2a2",
                                                        X"e4b7", X"fdbd", X"0818", X"0be3", X"0960", X"dc58", X"0756", X"073c", X"1885", X"13fc", X"1355", X"0b76", X"f988", X"f32e",
                                                        X"0fc2", X"122c", X"fbfd", X"d8df", X"f308", X"fb1e", X"0639", X"1fee", X"0a04", X"0c0a", X"fd10", X"da55", X"1c8c", X"01e9",
                                                        X"f0c2", X"18b4", X"db0c", X"08ba", X"fdf7", X"e19b", X"feea", X"02d1", X"f3ef", X"1154", X"2404", X"fe82", X"137e", X"e834",
                                                        X"d250", X"1f1c", X"ec6c", X"ec66", X"1866", X"ea7f", X"020c", X"0887", X"0d2b", X"e729", X"0cbf", X"ffb2", X"1f89", X"089a",
                                                        X"ed44", X"e84b", X"08e1", X"17dc", X"ed43", X"f497", X"fc87", X"08f2", X"efd2", X"1078", X"17b7", X"fe22", X"19df", X"0827",
                                                        X"0410", X"f0c1", X"1c9e", X"e711", X"d579", X"0420", X"fdd9", X"1e15", X"21b8", X"05b7", X"fbb9", X"f47e", X"0cae", X"16c8",
                                                        X"f7cd", X"0753", X"1cd5", X"ecbf", X"fb57", X"e1ff", X"eca0", X"045d", X"fddb", X"fe29", X"ea07", X"ea88", X"dbc1", X"f646",
                                                        X"faae", X"e6cc", X"13f9", X"064e", X"1c45", X"2025", X"00e2", X"e70e", X"d7d8", X"164d", X"fbcd", X"f663", X"0314", X"1915",
                                                        X"f4f2", X"11b8", X"13a2", X"ece9", X"0758", X"ed2c", X"049d", X"0254", X"fdbd", X"f6af", X"0631", X"0c53", X"efa6", X"fa20",
                                                        X"0753", X"0e9a", X"0d35", X"0965", X"050b", X"0781", X"0b0a", X"20b9", X"01fc", X"fe9b", X"1a72", X"12c8", X"0ebe", X"e286",
                                                        X"fe1e", X"fe5c", X"f093", X"e692", X"f55f", X"e094", X"f3d6", X"05b3", X"1276", X"2969", X"efd8", X"1610", X"f500", X"0108",
                                                        X"0c4c", X"0132", X"179e", X"f952", X"0742", X"0de7", X"007d", X"ede9", X"fff2", X"09d0", X"0118", X"dee5", X"f517", X"f6e3",
                                                        X"f2af", X"3529", X"eb5f", X"db0d", X"1048", X"00e2", X"ee13", X"10d1", X"f417", X"f61a", X"f2af", X"0df7", X"f7dd", X"e5d9",
                                                        X"ecd9", X"f96d", X"08c4", X"1adb", X"1abc", X"dcec", X"014c", X"f3f9", X"d5d9", X"003e", X"02ef", X"e535", X"00fe", X"f4b5",
                                                        X"ed10", X"e1ee", X"f241", X"1d85", X"ee8e", X"23ce", X"1bd2", X"ecca", X"0309", X"1578", X"25d1", X"09d2", X"fbab", X"e483",
                                                        X"eaf6", X"009b", X"0db3", X"d5c2", X"eb85", X"030a", X"ff22", X"1730", X"e5da", X"ed5b", X"df44", X"f63f", X"1a52", X"13bf",
                                                        X"e99a", X"d884", X"0ba4", X"fd91", X"05ae", X"f3db", X"fb4e", X"e94f", X"0023", X"15ef", X"e515", X"d0a7", X"fa7d", X"f4aa",
                                                        X"fcd7", X"e21d", X"df8e", X"0166", X"f6aa", X"0e7f", X"eeea", X"189d", X"fc9b", X"109b", X"fb3d", X"0086", X"32fe", X"f235",
                                                        X"0c8f", X"ef66", X"fc4e", X"f388", X"f0c2", X"f237", X"0562", X"13b3", X"14dd", X"2ac2", X"0539", X"ede1", X"21ba", X"f41c",
                                                        X"dbe2", X"edfc", X"f292", X"ec6a", X"d9a7", X"0e35", X"18a0", X"f9fd", X"2094", X"f6ec", X"11eb", X"2bd5", X"2db6", X"121b",
                                                        X"dfa5", X"f389", X"2409", X"0aa1", X"03b4", X"1a2f", X"ee37", X"06a6", X"d3e5", X"062c", X"1911", X"1641", X"eac0", X"f1c0",
                                                        X"1454", X"1112", X"1589", X"e17e", X"12f5", X"0b34", X"f9f8", X"112e", X"e998", X"e694", X"e812", X"e46e", X"ed11", X"f3b0",
                                                        X"ffff", X"20d3", X"2f66", X"1e74", X"fdaf", X"dff8", X"f01b", X"1404", X"ef63", X"e799", X"2215", X"0e62", X"1cb5", X"fb27",
                                                        X"ee59", X"1014", X"e279", X"eed6", X"21f2", X"2194", X"0295", X"d824", X"1151", X"06e3", X"1379", X"0b4f", X"128e", X"e3d8",
                                                        X"e5a6", X"e558", X"e7a6", X"e246", X"0ff8", X"f3a6", X"245f", X"f2dc", X"0773", X"f40e", X"11b3", X"0762", X"04b2", X"01f1",
                                                        X"04e8", X"eb2b", X"0840", X"14cd", X"0886", X"f132", X"01d8", X"e4d7", X"f58f", X"0a00", X"fc83", X"ec57", X"2822", X"2cb1",
                                                        X"ff1c", X"fe70", X"0f26", X"13f7", X"faa8", X"f647", X"14bb", X"e6a0", X"1395", X"d503", X"0626", X"128e", X"fbae", X"c40f",
                                                        X"ecff", X"259f", X"0fa4", X"0987", X"1bd6", X"0eba", X"02ce", X"0df9", X"2822", X"0d99", X"f4d5", X"2589", X"0aa7", X"0bd4",
                                                        X"037d", X"0040", X"e378", X"f980", X"ff47", X"0446", X"f214", X"11d0", X"fea8", X"f527", X"147c", X"0737", X"fe46", X"e81d",
                                                        X"f806", X"f793", X"f81b", X"08e4", X"fbd2", X"d9f4", X"0835", X"fe42", X"0fc0", X"f26c", X"0165", X"063f", X"0dd1", X"f9dc",
                                                        X"fa42", X"fb8e", X"1b76", X"13bd", X"f6e7", X"ff2b", X"2dab", X"efae", X"f7a0", X"0918", X"0cce", X"f787", X"f0ee", X"dc72",
                                                        X"0af3", X"ec0f", X"13d7", X"db8b", X"0aad", X"f967", X"ecba", X"0b71", X"222c", X"ed21", X"eb85", X"fdbd", X"f2a4", X"024b",
                                                        X"e3f9", X"dc97", X"11ee", X"049a", X"10dd", X"e7de", X"0113", X"1064", X"061a", X"0eb2", X"11f2", X"dbf1", X"0b61", X"1233",
                                                        X"ee32", X"0a77", X"0e20", X"0c8d", X"edaa", X"f885", X"ea8e", X"f3b2", X"0ea0", X"0107", X"f7af", X"044c", X"df90", X"d001",
                                                        X"f381", X"fe93", X"df37", X"efcc", X"f5a8", X"0e99", X"e649", X"fd53", X"12bf", X"187a", X"009a", X"1e81", X"02d4", X"fc9d",
                                                        X"0d07", X"eefb", X"edeb", X"1ee8", X"1147", X"0647", X"f56f", X"f765", X"1d43", X"0cad", X"0248", X"2300", X"fa10", X"f478",
                                                        X"0e6f", X"0ab5", X"0336", X"f5b3", X"fbf7", X"fd57", X"13da", X"0bbd", X"2965", X"f2b3", X"0699", X"f869", X"03ca", X"e8d4",
                                                        X"1ae5", X"0bd1", X"08be", X"fb76", X"26d0", X"0a44", X"f790", X"fa9d", X"23a5", X"fd5f", X"e7f2", X"ed85", X"f30c", X"fefa",
                                                        X"e8ec", X"fe7d", X"13a3", X"ed37", X"067c", X"fc62", X"ebc1", X"f9f9", X"ea9c", X"145a", X"03a7", X"11a7", X"f8b4", X"fadf",
                                                        X"fefc", X"f59f", X"0787", X"dd5f", X"265d", X"fa59", X"195c", X"ff91", X"21cf", X"fc4d", X"0146", X"1d47", X"0fbd", X"1fc3",
                                                        X"fa56", X"df07", X"e582", X"fe16", X"fa77", X"0170", X"09b6", X"fc3a", X"df77", X"0ba9", X"1b8d", X"1511", X"dc50", X"0c72",
                                                        X"1356", X"00ff", X"0eba", X"10a2", X"ef60", X"f5c2", X"e80e", X"13b9", X"e7cd", X"ed70", X"0dd3", X"e1e0", X"f49f", X"fecc",
                                                        X"faf3", X"edb3", X"e103", X"01e7", X"0696", X"e1e8", X"f036", X"0e5f", X"fb8c", X"08f9", X"1251", X"f31e", X"0ef9", X"cce2",
                                                        X"2831", X"00f9", X"0faf", X"ff79", X"00a3", X"0fa5", X"f4f1", X"f488", X"12d9", X"fa2c", X"f30d", X"22e5", X"21df", X"0753",
                                                        X"178b", X"f2c3", X"d31a", X"0bcf", X"f40a", X"f275", X"136f", X"0ed8", X"e6e9", X"081c", X"fc7b", X"edbe", X"ec52", X"dbb0",
                                                        X"efad", X"022c", X"f722", X"f0a0", X"ded5", X"170c", X"fb94", X"f670", X"14d3", X"00a3", X"f985", X"0285", X"1519", X"f6cf",
                                                        X"fd98", X"ec6b", X"fbec", X"0205", X"fc7e", X"ebcd", X"00ed", X"0790", X"0b69", X"eb80", X"3490", X"0408", X"f608", X"0771",
                                                        X"216c", X"db8a", X"0a32", X"f1d5", X"182d", X"0523", X"f3f9", X"e4c4", X"f5e4", X"dbfb", X"f9c5", X"f4b5", X"1528", X"fdd2",
                                                        X"fae2", X"1a32", X"0dba", X"fc36", X"fb9e", X"d6f4", X"f8e5", X"fed8", X"0088", X"04de", X"050b", X"e1ad", X"0aff", X"ee34",
                                                        X"1fd7", X"fc5b", X"edeb", X"e385", X"15fd", X"14f7", X"0113", X"00e8", X"15cf", X"06e1", X"1a50", X"f484", X"1858", X"e604",
                                                        X"fd95", X"110f", X"198b", X"f196", X"0202", X"ef3d", X"f8ec", X"fea3", X"0a31", X"065a", X"f130", X"0e77", X"10e2", X"f7fb",
                                                        X"cc10", X"da5e", X"e271", X"1a85", X"fd98", X"f415", X"102b", X"1501", X"f582", X"d5f9", X"dcdc", X"f72f", X"fdb6", X"1ee8",
                                                        X"dd61", X"f3f3", X"dcdb", X"d621", X"0610", X"094b", X"14fd", X"f087", X"df28", X"0076", X"fc4e", X"0ca1", X"ec4d", X"2011",
                                                        X"14e0", X"f003", X"fe0d", X"0922", X"09a0", X"ddd4", X"eeef", X"f33b", X"1330", X"0437", X"f8be", X"fcfe", X"fea5", X"e7f9",
                                                        X"08da", X"2ac6", X"1246", X"1b26", X"db19", X"2c73", X"dec2", X"e951", X"05ea", X"ed9a", X"e69e", X"1838", X"f26a", X"fd05",
                                                        X"0ceb", X"26da", X"ff10", X"db4d", X"095b", X"f9f9", X"e2e4", X"04dd", X"342d", X"0ff0", X"fc6a", X"167c", X"11c8", X"f3a9",
                                                        X"09f7", X"0fb9", X"fedb", X"0179", X"067f", X"f5ef", X"269c", X"13ce", X"05aa", X"f0dc", X"1390", X"f422", X"029d", X"0961",
                                                        X"09a1", X"e32c", X"0b15", X"e9a3", X"20d2", X"094f", X"0b72", X"fa86", X"f2c0", X"16fa", X"dee4", X"ddb9", X"e5b8", X"fb21",
                                                        X"e595", X"161c", X"1237", X"0dfe", X"fe4c", X"e7d4", X"0443", X"117c", X"fde2", X"27d0", X"0deb", X"eb6e", X"fe37", X"f5a0",
                                                        X"eb2f", X"fdd3", X"07d1", X"ef26", X"f9c3", X"edc5", X"f3d2", X"f626", X"f9da", X"e893", X"1898", X"2369", X"1d40", X"1367",
                                                        X"f230", X"fb13", X"0da5", X"1ae1", X"fa73", X"003e", X"e4fc", X"ee0c", X"0b24", X"08cf", X"151d", X"e8c8", X"1767", X"f13b",
                                                        X"0455", X"138b", X"0150", X"dc17", X"d7e9", X"2119", X"f585", X"e97c", X"dd2b", X"12fd", X"eb99", X"1593", X"1cd9", X"ecc1",
                                                        X"0d0d", X"f55c", X"04d1", X"f726", X"f65d", X"ec6b", X"07ad", X"1327", X"13ec", X"0b9a", X"0917", X"edf2", X"1fdf", X"ed49",
                                                        X"1fa5", X"2490", X"0031", X"f01a", X"2b76", X"00d9", X"fa92", X"0e11", X"1817", X"0687", X"06a3", X"076b", X"014b", X"1f45",
                                                        X"0e64", X"ff60", X"1139", X"0c6b", X"e4fc", X"34a7", X"eedd", X"11c8", X"0e75", X"f663", X"f042", X"1391", X"07f7", X"ef79",
                                                        X"2b3f", X"fe25", X"0158", X"ea89", X"1f90", X"e352", X"066f", X"1d6f", X"0edc", X"0ffb", X"df19", X"f243", X"df3e", X"dfd5",
                                                        X"02f1", X"efa1", X"fafa", X"e427", X"f2ba", X"f1b4", X"11d1", X"f23d", X"02c3", X"047c", X"faf9", X"0a66", X"0724", X"09b3",
                                                        X"25a3", X"0254", X"0ba3", X"0733", X"0c3f", X"0f4c", X"17ef", X"0ad6", X"0377", X"e61d", X"195a", X"0f02", X"1fb6", X"0a8a",
                                                        X"0fd7", X"e822", X"ce60", X"d283", X"ef00", X"ee98", X"dcca", X"1319", X"f8de", X"035d", X"0045", X"0bba", X"0d07", X"0615",
                                                        X"eb60", X"211a", X"fa5c", X"1510", X"fc36", X"eade", X"fba2", X"f48d", X"d87f", X"1a35", X"e8a6", X"e164", X"1d32", X"0dc6",
                                                        X"0263", X"06f2", X"0dd0", X"f407", X"db67", X"0a15", X"10f8", X"db1d", X"e61e", X"0183", X"f8f1", X"feba", X"0d8c", X"df03",
                                                        X"0563", X"0b69", X"f679", X"11c5", X"ee0b", X"e77a", X"0273", X"1b9b", X"1b0a", X"ea2b", X"f81f", X"08fb", X"20c4", X"eed8",
                                                        X"d8f6", X"22d1", X"0492", X"1c31", X"eef6", X"3826", X"ed70", X"ea7b", X"ff31", X"12bb", X"ef06", X"f515", X"eb1c", X"fae2",
                                                        X"0683", X"1da1", X"ee4c", X"e071", X"e336", X"0696", X"12f3", X"28b9", X"112d", X"13c4", X"099d", X"f9d4", X"f3b7", X"0386",
                                                        X"fd76", X"e1bd", X"d254", X"04e0", X"e14e", X"03f4", X"ec40", X"0781", X"0d91", X"1e85", X"0b00", X"eee3", X"1f80", X"fdc4",
                                                        X"20cb", X"d9e6", X"002c", X"1296", X"19a7", X"ed69", X"16a7", X"d9a7", X"ee20", X"1676", X"fec5", X"218a", X"00df", X"0cba",
                                                        X"018c", X"fae7", X"02f9", X"d51e", X"2496", X"1162", X"cb3e", X"f556", X"ff69", X"e22a", X"ddde", X"1567", X"235b", X"00a9",
                                                        X"0b4d", X"0b18", X"fb9a", X"ed3c", X"19d9", X"0d94", X"142a", X"10a1", X"e601", X"feff", X"efa6", X"fd87", X"04f6", X"efc4",
                                                        X"1929", X"158a", X"1b56", X"f713", X"fea3", X"fb45", X"05a7", X"2cb9", X"f8ac", X"0671", X"146d", X"0762", X"e918", X"f745",
                                                        X"f5f9", X"e0e0", X"02f2", X"02fb", X"056d", X"e741", X"fa35", X"e069", X"064f", X"f6a3", X"ff74", X"14a9", X"06a8", X"0092",
                                                        X"fade", X"ff42", X"084c", X"e683", X"e4f4", X"0fcc", X"1274", X"f7e4", X"f0a8", X"d334", X"e597", X"33e6", X"e236", X"def4",
                                                        X"f728", X"f326", X"eaf6", X"fe07");
  SIGNAL data_int                         : std_logic_vector(DataWidth - 1 DOWNTO 0) := X"fe07";
  SIGNAL addr_unsigned                    : unsigned(AddrWidth - 1 DOWNTO 0);  -- generic width

BEGIN
  addr_unsigned <= unsigned(addr);

  SinglePortRAM_generic_process: PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF enb = '1' THEN
        IF we = '1' THEN
          ram(to_integer(addr_unsigned)) <= din;
          data_int <= din;
        ELSE
          data_int <= ram(to_integer(addr_unsigned));
        END IF;
      END IF;
    END IF;
  END PROCESS SinglePortRAM_generic_process;

  dout <= data_int;

END rtl;

