-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/amc_model_w16a16/amc_cnn_16w16a_src_SinglePortRAM_generic_block423.vhd
-- Created: 2023-07-03 13:16:58
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: amc_cnn_16w16a_src_SinglePortRAM_generic_block423
-- Source Path: amc_model_w16a16/DUT HDL/Dense Layer 1/Dense Layer 1/Weight Storage69/SinglePortRAM_generic
-- Hierarchy Level: 4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY amc_cnn_16w16a_src_SinglePortRAM_generic_block423 IS
  GENERIC( AddrWidth                      : integer := 1;
           DataWidth                      : integer := 1
           );
  PORT( clk                               :   IN    std_logic;
        enb                               :   IN    std_logic;
        din                               :   IN    std_logic_vector(DataWidth - 1 DOWNTO 0);  -- generic width
        addr                              :   IN    std_logic_vector(AddrWidth - 1 DOWNTO 0);  -- generic width
        we                                :   IN    std_logic;  -- ufix1
        dout                              :   OUT   std_logic_vector(DataWidth - 1 DOWNTO 0)  -- generic width
        );
END amc_cnn_16w16a_src_SinglePortRAM_generic_block423;


ARCHITECTURE rtl OF amc_cnn_16w16a_src_SinglePortRAM_generic_block423 IS

  -- Local Type Definitions
  TYPE ram_type IS ARRAY (2**AddrWidth - 1 DOWNTO 0) of std_logic_vector(DataWidth - 1 DOWNTO 0);

  -- Signals
  SIGNAL ram                              : ram_type := (X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000",
                                                        X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"0000", X"070e", X"e028", X"f4e6", X"17fe", X"e291", X"fa7a",
                                                        X"0a46", X"06a1", X"1815", X"2e6e", X"d146", X"2517", X"fc89", X"bfce", X"0541", X"3d7b", X"dae5", X"fd9e", X"1826", X"cbb8",
                                                        X"183d", X"f305", X"ef32", X"11f9", X"e4ac", X"ff7b", X"079f", X"f2a7", X"28a1", X"0442", X"e9c7", X"1e43", X"006f", X"f910",
                                                        X"00f6", X"f9a2", X"1da5", X"235e", X"efbd", X"1f46", X"de55", X"273f", X"f72c", X"f999", X"d1c0", X"e974", X"e686", X"e28d",
                                                        X"f833", X"09f9", X"03b9", X"f0e1", X"d6ac", X"0f6c", X"efc9", X"0aa3", X"23ca", X"45c9", X"e5d7", X"de32", X"14c5", X"f9e6",
                                                        X"f120", X"2c18", X"1dbe", X"f51e", X"f70f", X"3ba9", X"1066", X"f605", X"0847", X"20aa", X"f5c8", X"f375", X"00d4", X"df69",
                                                        X"d536", X"de94", X"1bf0", X"ec49", X"e62f", X"f47c", X"15e2", X"dc9a", X"f1be", X"f3b1", X"2039", X"19d3", X"0bab", X"ff5e",
                                                        X"f50f", X"1fd3", X"d33b", X"e247", X"0ae6", X"0d57", X"0ded", X"0028", X"f8b7", X"e1b5", X"1506", X"1153", X"1331", X"fd4f",
                                                        X"07a5", X"1149", X"f840", X"197a", X"e8df", X"faae", X"c3eb", X"f882", X"0bb5", X"03e2", X"141e", X"2a16", X"f2d8", X"1a60",
                                                        X"e6ff", X"18bb", X"19db", X"21fd", X"121f", X"186d", X"1584", X"f5b8", X"0646", X"07c9", X"e812", X"fea4", X"f57d", X"2280",
                                                        X"ece2", X"04bc", X"ffb3", X"1af6", X"f70a", X"2709", X"11db", X"f8a0", X"e53f", X"e498", X"fb07", X"ff75", X"17dc", X"eee0",
                                                        X"ebe8", X"f1ef", X"f1ad", X"0939", X"e763", X"fb1a", X"0ce0", X"fc04", X"e99e", X"ff70", X"152a", X"ed42", X"0b8c", X"e2d4",
                                                        X"e590", X"e632", X"f474", X"0243", X"18da", X"18d6", X"1bfc", X"34f7", X"e029", X"309a", X"00a3", X"ee90", X"e5c4", X"f01d",
                                                        X"d878", X"e31a", X"1db0", X"0573", X"feff", X"c8b1", X"f7f4", X"e972", X"186a", X"ff01", X"f398", X"f731", X"e50b", X"1361",
                                                        X"038b", X"f452", X"cae5", X"df58", X"f770", X"ea3a", X"1e32", X"2371", X"0618", X"ea5e", X"f6de", X"187a", X"c1ab", X"3835",
                                                        X"f126", X"01de", X"d83b", X"dba0", X"004e", X"05dc", X"0915", X"1384", X"1155", X"11c0", X"daba", X"2255", X"d35d", X"170d",
                                                        X"e1e4", X"fd10", X"e534", X"18cc", X"2b37", X"01f1", X"f83a", X"16e2", X"c7d3", X"ff2b", X"115c", X"041c", X"1c4b", X"05ae",
                                                        X"19df", X"2925", X"f29a", X"2c42", X"fe6c", X"fb5c", X"f5b8", X"caa4", X"ec9f", X"1af1", X"f285", X"0679", X"1124", X"2b02",
                                                        X"0308", X"f8c3", X"fc4b", X"fa9c", X"fa49", X"f888", X"0ba6", X"ded1", X"e465", X"d16f", X"f10a", X"1dc1", X"3287", X"fc4d",
                                                        X"f02f", X"3677", X"ebc2", X"11d5", X"1104", X"f540", X"deb5", X"175c", X"11db", X"d872", X"e8f7", X"0210", X"0a5f", X"2945",
                                                        X"069f", X"0418", X"1673", X"0dfc", X"ece2", X"f416", X"0bf0", X"0712", X"d4c4", X"fbe5", X"e049", X"1bad", X"cbb9", X"ec9a",
                                                        X"0a07", X"def3", X"1c9c", X"f8d6", X"ffe9", X"31c2", X"0b6d", X"087b", X"fa1a", X"0514", X"f246", X"2227", X"ecfc", X"f592",
                                                        X"d36c", X"d7e0", X"f4bd", X"0287", X"27ff", X"f6a8", X"ee79", X"d08b", X"e8c7", X"14b7", X"02d2", X"f876", X"fc7a", X"fe62",
                                                        X"cc72", X"0348", X"eb74", X"f261", X"1690", X"0eac", X"2527", X"01d2", X"0aab", X"2173", X"f747", X"f606", X"edb3", X"062f",
                                                        X"25ac", X"066c", X"0913", X"dbcf", X"2227", X"e78d", X"f903", X"f140", X"f033", X"fc2a", X"f771", X"d82c", X"0896", X"e181",
                                                        X"ffe5", X"0a43", X"16d4", X"2601", X"f3e8", X"272b", X"e01a", X"d906", X"0004", X"1b91", X"0aaf", X"e158", X"0515", X"e9d3",
                                                        X"f1ec", X"dd7d", X"f29f", X"37bd", X"cd50", X"0839", X"e8b8", X"dc30", X"efd2", X"00af", X"e60d", X"12b9", X"e9bc", X"efe3",
                                                        X"25dd", X"da02", X"e41a", X"0fb5", X"06b3", X"05e5", X"dd5a", X"1c1a", X"fd6b", X"d940", X"164f", X"022c", X"fd9e", X"1b47",
                                                        X"0261", X"f3bf", X"13bf", X"119e", X"f413", X"e1e4", X"0426", X"35b5", X"f9b5", X"2fb3", X"de1f", X"1692", X"eafb", X"075e",
                                                        X"e20d", X"d3e9", X"dd3f", X"f4ab", X"f531", X"1a91", X"fa12", X"226c", X"05e6", X"1b89", X"0208", X"f136", X"d8fe", X"08d3",
                                                        X"fd62", X"0a78", X"16d8", X"0e00", X"1fd4", X"21e2", X"f73c", X"ea0d", X"ea6e", X"21e3", X"1b0d", X"2292", X"f3b5", X"2b90",
                                                        X"e276", X"ec92", X"2888", X"e3d0", X"f5d7", X"f7f4", X"fd80", X"1845", X"0736", X"d09b", X"10e9", X"faef", X"0b1a", X"ee68",
                                                        X"c9f8", X"11d9", X"f1fb", X"f3d4", X"fc42", X"ead6", X"0d1a", X"360b", X"ee08", X"e37d", X"1225", X"cb70", X"2062", X"2937",
                                                        X"0310", X"0775", X"cb21", X"17a1", X"f58f", X"0661", X"fc85", X"dcb8", X"e0c9", X"e6d6", X"1a43", X"ea42", X"f990", X"0b89",
                                                        X"eb31", X"e0cb", X"0d00", X"fa1a", X"fa8a", X"14c0", X"de90", X"e812", X"dfa1", X"f8d6", X"0d01", X"0e2f", X"2516", X"f99d",
                                                        X"f161", X"33ef", X"e968", X"16b6", X"1c70", X"1c3b", X"f587", X"1ccf", X"ed23", X"df6c", X"29c6", X"ea6a", X"e68e", X"fe9f",
                                                        X"2fdd", X"e30e", X"1725", X"2c99", X"1bb4", X"2fc6", X"ef80", X"2034", X"0767", X"27f2", X"ec61", X"1cd1", X"d679", X"ec88",
                                                        X"049d", X"eafb", X"fb65", X"2256", X"f3a1", X"f0b2", X"e5dc", X"ecf1", X"fb71", X"1fd3", X"20da", X"fd0e", X"f5dc", X"eb63",
                                                        X"f17c", X"e13f", X"160b", X"f0f5", X"fd24", X"f907", X"03c5", X"0cda", X"ef25", X"1c52", X"155f", X"e725", X"de75", X"f97d",
                                                        X"e99d", X"0ec4", X"1dd9", X"f213", X"d6d4", X"e3f9", X"3039", X"201b", X"fcf6", X"177e", X"f391", X"f0b6", X"f005", X"1df1",
                                                        X"d2c6", X"37a3", X"1239", X"0cda", X"2e98", X"eebc", X"0860", X"193c", X"0c52", X"f9f4", X"f699", X"cda1", X"ed1a", X"e12b",
                                                        X"0a5b", X"2959", X"f964", X"0122", X"f67c", X"c4b5", X"d1fa", X"ed8d", X"dd1c", X"298e", X"0a6a", X"e462", X"f6ae", X"d77b",
                                                        X"160c", X"ea97", X"f21a", X"f31a", X"cdc9", X"0b33", X"e510", X"2466", X"11bc", X"f61d", X"1a03", X"1bd2", X"2a94", X"ed6c",
                                                        X"02f1", X"3335", X"fefb", X"e944", X"082e", X"2b9f", X"fd9d", X"0c1f", X"db4f", X"0cfd", X"1f98", X"e695", X"29b0", X"eb04",
                                                        X"22e0", X"f761", X"ed3d", X"ff8d", X"02a3", X"fef9", X"f16d", X"1bf7", X"1d6d", X"08d8", X"f71b", X"f5d2", X"d651", X"ee7e",
                                                        X"1031", X"f41c", X"ee10", X"fa86", X"10cc", X"3735", X"15aa", X"f626", X"e856", X"1a74", X"f0bf", X"19c2", X"ffc8", X"fc1e",
                                                        X"d768", X"de0b", X"faa3", X"f077", X"e4da", X"f77f", X"0a16", X"f789", X"e381", X"1b0a", X"0189", X"ff3e", X"db85", X"024c",
                                                        X"f9ff", X"1c02", X"1e09", X"e8a1", X"fc37", X"0da5", X"fde4", X"09ba", X"ffb7", X"0c05", X"1e6a", X"16bc", X"e71c", X"3536",
                                                        X"0f91", X"3f60", X"ee4a", X"d0ab", X"03b4", X"fa35", X"128a", X"2df7", X"1430", X"03c1", X"1b9f", X"cdae", X"f8da", X"1728",
                                                        X"0c22", X"0091", X"f836", X"1697", X"0a2c", X"0f2b", X"f81c", X"d2e4", X"dcbb", X"d3ff", X"14bb", X"d676", X"0546", X"cca9",
                                                        X"10c9", X"1d77", X"f226", X"0c1e", X"1d5e", X"2e65", X"f982", X"00be", X"1a59", X"f6d0", X"ee7e", X"e417", X"1ba8", X"05c6",
                                                        X"faad", X"1c55", X"ff80", X"f54b", X"ef0b", X"f701", X"daf5", X"2010", X"d36a", X"101b", X"07b1", X"ee29", X"ea34", X"19ea",
                                                        X"fd2e", X"03d7", X"fd0d", X"0b5f", X"eb5b", X"fd38", X"f5d7", X"31f5", X"eccb", X"2ac7", X"dfd4", X"177c", X"1103", X"dc06",
                                                        X"1952", X"d1ff", X"0c00", X"e64c", X"0c08", X"e10c", X"00cc", X"030f", X"e180", X"0b9e", X"199d", X"e401", X"d26d", X"f992",
                                                        X"018e", X"e2ca", X"efc1", X"01c9", X"25a5", X"0980", X"f5a7", X"0954", X"efd5", X"e65c", X"0242", X"2a31", X"0497", X"1554",
                                                        X"f033", X"e3c4", X"eaaa", X"f989", X"ee60", X"1a0f", X"f9c4", X"f0d6", X"f3d7", X"efb4", X"fe75", X"f8f2", X"f707", X"2601",
                                                        X"ed0c", X"11a5", X"e1f3", X"1479", X"2036", X"1581", X"fcf1", X"250c", X"2572", X"e9c7", X"0bf4", X"18ab", X"eca2", X"f700",
                                                        X"14a6", X"eb5a", X"eaea", X"00aa", X"e67b", X"d5bd", X"194d", X"fb45", X"ecae", X"e302", X"09a2", X"fb88", X"1d54", X"ee43",
                                                        X"1b60", X"dbd7", X"048a", X"066e", X"1abc", X"31fc", X"ffbf", X"dacc", X"fc5c", X"f6e4", X"04c2", X"1db4", X"227b", X"d76e",
                                                        X"0ade", X"e7d8", X"d753", X"1614", X"25a1", X"2501", X"e6c6", X"1a89", X"e0f3", X"0dd3", X"d92f", X"e6ff", X"f969", X"1404",
                                                        X"fda9", X"ec50", X"1139", X"e00d", X"da87", X"056a", X"fa6c", X"f558", X"c55f", X"08b5", X"d820", X"f498", X"1676", X"cdcb",
                                                        X"044c", X"33cc", X"e9a2", X"0a0e", X"17c0", X"415a", X"f1ab", X"d257", X"f5c4", X"318d", X"fa19", X"0629", X"f457", X"e7a5",
                                                        X"2118", X"d8b5", X"ef48", X"0121", X"fb29", X"0524", X"f216", X"dccd", X"f684", X"095d", X"0700", X"201c", X"bd1c", X"3c0f",
                                                        X"f880", X"cbb8", X"f533", X"d0be", X"0092", X"24ec", X"ea3b", X"2069", X"08f5", X"eaee", X"f86f", X"0ad7", X"09aa", X"1e02",
                                                        X"c731", X"2566", X"02ad", X"2be9", X"22bc", X"fafd", X"137e", X"122a", X"eafd", X"0dbd", X"22d6", X"0cf9", X"e590", X"0a9a",
                                                        X"f8e5", X"19f5", X"e79b", X"1fba", X"eec9", X"1257", X"e046", X"f144", X"fd02", X"fbea", X"2dd8", X"f29f", X"206a", X"f3c6",
                                                        X"0e73", X"e55e", X"f9ac", X"1eca", X"0be9", X"ec69", X"dfce", X"f727", X"1a01", X"08aa", X"d9a7", X"11d1", X"0e4a", X"06a1",
                                                        X"124e", X"fb23", X"f556", X"1ebe", X"f223", X"10e8", X"277b", X"2d76", X"e786", X"d7b7", X"f91b", X"089b", X"fb48", X"1107",
                                                        X"e68c", X"f13f", X"f65e", X"f92b", X"e846", X"ecec", X"0865", X"fa3a", X"d537", X"460f", X"e278", X"e06b", X"15c3", X"f5ce",
                                                        X"e99d", X"f293", X"0712", X"03f9", X"ef5a", X"ed58", X"1cfa", X"0c67", X"0e41", X"2af6", X"eea6", X"1c8b", X"f145", X"ea75",
                                                        X"dc0d", X"f39c", X"0832", X"1869", X"1c9d", X"0962", X"0a82", X"fa47", X"f3e0", X"ecdf", X"ee05", X"1785", X"069d", X"f08a",
                                                        X"d95a", X"ebe1", X"d992", X"ec11", X"fc72", X"2136", X"dd76", X"e529", X"f3c1", X"3799", X"029b", X"0236", X"1413", X"fff8",
                                                        X"ecca", X"19d4", X"e697", X"fb9a", X"d5e4", X"f371", X"e3dc", X"238d", X"1dce", X"0926", X"f491", X"f427", X"fb55", X"fd9c",
                                                        X"f6e3", X"3c91", X"de75", X"11d4", X"f4d4", X"d5ec", X"13f1", X"ef6a", X"ef28", X"e454", X"f300", X"ed84", X"2673", X"f537",
                                                        X"02f4", X"e368", X"ee5d", X"0c44", X"fb30", X"3329", X"f13c", X"010b", X"1628", X"f1ed", X"01e3", X"00da", X"1cd9", X"e968",
                                                        X"03f3", X"2fbd", X"19fe", X"123b", X"1e9f", X"05f9", X"10dd", X"0531", X"e599", X"e50d", X"1380", X"f393", X"31b0", X"2179",
                                                        X"f148", X"15ff", X"03b4", X"3136", X"e303", X"0320", X"f563", X"2bda", X"e46f", X"0770", X"0220", X"1465", X"17f2", X"1157",
                                                        X"ecc4", X"f5eb", X"fa10", X"f4b1", X"ff0e", X"381d", X"17df", X"ec97", X"f4b0", X"ff7a", X"1cd9", X"fcd8", X"d7b4", X"121c",
                                                        X"d3b8", X"f774", X"fa97", X"073f", X"19db", X"f9c6", X"026a", X"1860", X"eed5", X"1d35", X"e5c5", X"1b65", X"c1db", X"f255",
                                                        X"e0eb", X"fa63", X"f591", X"d7b4", X"f402", X"fceb", X"287b", X"10ac", X"e8eb", X"ed37", X"e5eb", X"0ca8", X"f0e0", X"cfeb",
                                                        X"d1d1", X"0899", X"e1de", X"e790", X"e772", X"fa6c", X"efdf", X"0654", X"13b1", X"e5fa", X"0af3", X"1d90", X"e185", X"0113",
                                                        X"e0e1", X"1143", X"df83", X"070b", X"00c4", X"dee0", X"1d21", X"f854", X"16f7", X"f66f", X"2ad6", X"f3cf", X"fe36", X"1191",
                                                        X"1791", X"148d", X"008b", X"1ef5", X"dd4e", X"198c", X"fe1d", X"010f", X"2bf0", X"f5ad", X"f1d0", X"e6b7", X"de59", X"03b7",
                                                        X"f3e9", X"012c", X"0b24", X"ed0c", X"f361", X"0878", X"1e72", X"0984", X"da74", X"1eac", X"f2e5", X"d5f7", X"066e", X"049e",
                                                        X"fd62", X"e20a", X"efb0", X"f4c6", X"fb39", X"1617", X"0ae8", X"20ee", X"dd06", X"194a", X"f9ca", X"e0f8", X"e553", X"0a6e",
                                                        X"1e3c", X"14e7", X"f572", X"e8f5", X"00ec", X"fa4b", X"ff3a", X"0b2a", X"ee98", X"076e", X"0643", X"3bb2", X"ec47", X"e3e9",
                                                        X"1864", X"00ed", X"d9f1", X"1a7a", X"e8f5", X"ef8d", X"f751", X"daec", X"f9b5", X"1324", X"0dfb", X"3086", X"f602", X"0689",
                                                        X"ed8c", X"e2a8", X"e421", X"fbd3", X"d57e", X"1535", X"e569", X"ef25", X"180d", X"2a54", X"0105", X"102b", X"1d91", X"377a",
                                                        X"dd64", X"2ec3", X"0b1d", X"d070", X"260a", X"f2fa", X"046d", X"036a", X"f77c", X"fa92", X"1a38", X"f3e6", X"0fc2", X"fe4c",
                                                        X"ec8e", X"1f46", X"f7a4", X"4bf8", X"e854", X"0637", X"f2bf", X"c6b9", X"e773", X"f040", X"300e", X"e111", X"1cfa", X"2ff8",
                                                        X"f5e0", X"ff7e", X"f64c", X"187d", X"15a1", X"170c", X"fc9c", X"0348", X"1ef9", X"efe7", X"047c", X"fdb4", X"f815", X"e931",
                                                        X"023e", X"d84f", X"ee58", X"f23a", X"f6e6", X"f1bb", X"c633", X"18a1", X"edfb", X"efb3", X"169d", X"f644", X"0ad8", X"03ac",
                                                        X"133e", X"0c86", X"0fc0", X"26bb", X"e523", X"ebb9", X"0667", X"3c60", X"c951", X"f4b4", X"ecac", X"fe1a", X"10c8", X"fb34",
                                                        X"05f1", X"f9cb", X"0f51", X"0c17", X"ea4a", X"f956", X"088c", X"e048", X"e212", X"11e0", X"0948", X"1f9d", X"f5fc", X"f999",
                                                        X"f7d2", X"f787", X"f760", X"2b0e", X"f1ce", X"0fd8", X"1509", X"e37d", X"039e", X"f7fc", X"fdf7", X"f37f", X"e863", X"f796",
                                                        X"ea54", X"1312", X"1301", X"fb56", X"1ac7", X"1b85", X"eb0b", X"f5d6", X"ee92", X"1df5", X"dd37", X"fdb3", X"f91f", X"0484",
                                                        X"e7aa", X"1d5f", X"0664", X"2236", X"20e7", X"f53a", X"eac9", X"e38d", X"0a1b", X"f60d", X"219a", X"3f31", X"0590", X"e1ff",
                                                        X"0bbf", X"13a1", X"ca5f", X"38eb", X"ebb9", X"da5f", X"d15e", X"f51c", X"14e8", X"403a", X"ef38", X"ef13", X"fdf9", X"fba5",
                                                        X"1e02", X"2886", X"1ef5", X"221f", X"db69", X"022a", X"dce7", X"19b7", X"3615", X"f5f8", X"cdf4", X"e599", X"e684", X"f7af",
                                                        X"f7bc", X"1c34", X"0f11", X"1b56", X"031e", X"18cc", X"1e98", X"3ac0", X"f74b", X"118c", X"df1c", X"f408", X"e454", X"de14",
                                                        X"39c2", X"e5dd", X"eb37", X"d59b", X"f2f3", X"237a", X"0f37", X"272d", X"f649", X"0258", X"f8ae", X"048f", X"e5a5", X"e272",
                                                        X"f33b", X"fb0d", X"fa05", X"1877", X"1446", X"2d6f", X"e1e2", X"003b", X"1e5f", X"1037", X"f654", X"fd67", X"ffd7", X"137f",
                                                        X"1683", X"f3a9", X"d7dd", X"e1ad", X"ee73", X"0357", X"0a77", X"d56f", X"e164", X"eadc", X"e193", X"180f", X"db74", X"3ce0",
                                                        X"f6a0", X"db80", X"06d1", X"fc13", X"f675", X"17b3", X"0a66", X"e971", X"0d13", X"258f", X"073a", X"ebce", X"fe11", X"00a6",
                                                        X"eafe", X"214e", X"0087", X"3079", X"0ac5", X"f53a", X"f17c", X"f342", X"ea25", X"131e", X"1ecd", X"d74f", X"dc41", X"edec",
                                                        X"012d", X"0165", X"ebed", X"0950", X"efd2", X"1f70", X"1262", X"f625", X"fa12", X"269e", X"1745", X"0534", X"021e", X"f233",
                                                        X"107a", X"06f4", X"e182", X"2c53", X"b6de", X"0deb", X"0a2d", X"03af", X"1fa6", X"0806", X"f47a", X"0c29", X"30db", X"f73b",
                                                        X"ea8c", X"e0e7", X"d398", X"f715", X"1b02", X"1f1d", X"fbbc", X"12b2", X"f723", X"db28", X"0bbe", X"f351", X"089e", X"f252",
                                                        X"fa90", X"f3a3", X"0b1a", X"df57", X"158e", X"dde1", X"f71a", X"30ce", X"33c2", X"2178", X"dbfc", X"1386", X"101e", X"f928",
                                                        X"00ab", X"0cd2", X"1b40", X"ea1b", X"0562", X"e373", X"034b", X"056a", X"0cb7", X"113b", X"efda", X"fdf2", X"ddeb", X"faa7",
                                                        X"f81c", X"f139", X"fde8", X"ec78", X"0545", X"0418", X"ef89", X"f4c8", X"1316", X"e398", X"eb72", X"0f94", X"f992", X"064c",
                                                        X"f710", X"dc30", X"f6e1", X"f31d", X"ee83", X"12d1", X"0a1b", X"1ed1", X"ebd5", X"1728", X"ff59", X"1504", X"0292", X"eb4c",
                                                        X"ffb0", X"1c5b", X"e38f", X"1a0a", X"14d6", X"0e91", X"fc14", X"267b", X"2abd", X"f348", X"0a3c", X"d008", X"1380", X"1f64",
                                                        X"f2e1", X"2bff", X"d54d", X"13e7", X"fead", X"f1b1", X"0453", X"f3f6", X"0736", X"ffe4", X"0762", X"16f2", X"fd67", X"cf0e",
                                                        X"ef2e", X"ef90", X"0e5a", X"1b95", X"1896", X"2f39", X"02c8", X"047f", X"f00c", X"ed2c", X"d54b", X"e5b4", X"18cb", X"e8d6",
                                                        X"0bcb", X"e582", X"efea", X"dce5", X"0f0b", X"1c78", X"e1ab", X"21bc", X"e7e1", X"0710", X"ff15", X"f464", X"e04d", X"2e6c",
                                                        X"e641", X"20a5", X"0aaf", X"d32a", X"e8b8", X"2197", X"0c52", X"2113", X"cf91", X"373c", X"f452", X"22be", X"d6dd", X"e153",
                                                        X"0302", X"fcba", X"d94f", X"e898", X"fe6b", X"f99b", X"05f2", X"1146", X"175e", X"3440", X"1144", X"18fd", X"f4c9", X"e7db",
                                                        X"1a76", X"f4ad", X"e3de", X"f93c", X"25a7", X"de81", X"0918", X"1ea5", X"04d2", X"03b7", X"18f7", X"f649", X"d51f", X"fd7c",
                                                        X"ef34", X"e7b1", X"ecf4", X"e584", X"0d08", X"1e02", X"2620", X"f8c1", X"fbb5", X"cea4", X"12d9", X"e422", X"e743", X"fe48",
                                                        X"f31f", X"21af", X"0831", X"0dd9", X"e68c", X"ffb4", X"e8a0", X"1ab3", X"0293", X"01a4", X"f3f5", X"2f63", X"0a8a", X"f7c1",
                                                        X"05cb", X"1e00", X"0e40", X"0561", X"d4b9", X"0846", X"1717", X"f558", X"fbf7", X"f282", X"2b0e", X"0483", X"ef09", X"ba88",
                                                        X"067b", X"fe96", X"043a", X"1d78", X"ea36", X"3c8e", X"ef0e", X"d551", X"0edd", X"f507", X"e20f", X"da2a", X"3656", X"17ef",
                                                        X"ee81", X"f64a", X"e807", X"2249", X"fff3", X"2c26", X"25a7", X"eed9", X"eb75", X"e8c9", X"e49d", X"e9ac", X"0395", X"00ec",
                                                        X"f426", X"0007", X"00c7", X"2f76", X"e64f", X"dec7", X"2a48", X"0985", X"fe06", X"1ab2", X"efe0", X"135f", X"f524", X"e79e",
                                                        X"c89c", X"d638", X"e66d", X"e3f8", X"0218", X"0b01", X"e88d", X"14fa", X"107d", X"f2d1", X"17c3", X"349a", X"ec9c", X"11ef",
                                                        X"07cc", X"061d", X"d362", X"fa9c", X"0be4", X"f9ac", X"13aa", X"de79", X"ea3d", X"dcb1", X"d8a6", X"0ac0", X"ef1c", X"006f",
                                                        X"de64", X"ee5c", X"fd6d", X"fe51", X"df1c", X"e280", X"1acd", X"f9a4", X"ff05", X"f4af", X"1b22", X"1adb", X"08e2", X"3714",
                                                        X"f3de", X"1ae9", X"ee7a", X"f55b", X"d57c", X"e988", X"f6bd", X"de90", X"f466", X"02be", X"f72b", X"2f44", X"1743", X"c8b5",
                                                        X"f0c2", X"0b91", X"c70b", X"2525", X"f647", X"0e0e", X"2453", X"eea4", X"00ae", X"08ff", X"0219", X"01b5", X"0c90", X"131f",
                                                        X"0304", X"ed5a", X"f3cd", X"185e", X"da52", X"f1a3", X"f99c", X"294a", X"cf84", X"1229", X"d828", X"0991", X"18d5", X"f179",
                                                        X"e9a2", X"1048", X"0783", X"1a02", X"1043", X"099a", X"dfb0", X"fe8d", X"e439", X"fb2a", X"1cdd", X"ff24", X"ee7e", X"fe44",
                                                        X"0274", X"043f", X"1c75", X"f74e", X"ee73", X"277a", X"1c0e", X"0dd3", X"f0b9", X"16b6", X"e9ec", X"ed93", X"13c2", X"128c",
                                                        X"0e68", X"d45e", X"189e", X"efa4", X"ee2b", X"c97d", X"dbc1", X"e7ab", X"fb83", X"04f9", X"f34d", X"012b", X"f680", X"1e5a",
                                                        X"08bb", X"e6ef", X"e272", X"f728", X"2202", X"0941", X"0a76", X"2c8b", X"0856", X"fe41", X"0eca", X"2b27", X"fa35", X"3a2c",
                                                        X"d9b8", X"0dba", X"04ad", X"db92", X"0957", X"dd66", X"1944", X"ff6d", X"0457", X"2523", X"e1cc", X"ddde", X"ef54", X"e309",
                                                        X"c029", X"f773", X"e6fd", X"f795", X"20b5", X"e6c4", X"f81a", X"f52a", X"1102", X"f83d", X"0771", X"203b", X"1591", X"063d",
                                                        X"ea3c", X"0da3", X"f27d", X"e3b5", X"f39a", X"060f", X"e7a5", X"f34f", X"e494", X"1705", X"ef8e", X"12e5", X"0175", X"f359",
                                                        X"ff24", X"1d10", X"f3be", X"238f", X"1ddb", X"21bc", X"ea6f", X"deff", X"ee1e", X"f8fd", X"ef16", X"1bc7", X"2117", X"e713",
                                                        X"00e7", X"f1e5", X"ec66", X"d608", X"f2bc", X"000a", X"29b2", X"2c9c", X"0b51", X"d6f9", X"f1dd", X"fc20", X"0e44", X"291c",
                                                        X"e237", X"22f6", X"0929", X"f20e", X"f520", X"0b4f", X"f6e8", X"3520", X"c40e", X"f92a", X"112f", X"1f34", X"faa2", X"1ca0",
                                                        X"e17e", X"036f", X"03f7", X"ebe3", X"ed22", X"4c14", X"06bf", X"1b13", X"1943", X"2c20", X"bef8", X"465e", X"d585", X"1ec3",
                                                        X"ebad", X"ce59", X"f863", X"f5c4");
  SIGNAL data_int                         : std_logic_vector(DataWidth - 1 DOWNTO 0) := X"f5c4";
  SIGNAL addr_unsigned                    : unsigned(AddrWidth - 1 DOWNTO 0);  -- generic width

BEGIN
  addr_unsigned <= unsigned(addr);

  SinglePortRAM_generic_process: PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF enb = '1' THEN
        IF we = '1' THEN
          ram(to_integer(addr_unsigned)) <= din;
          data_int <= din;
        ELSE
          data_int <= ram(to_integer(addr_unsigned));
        END IF;
      END IF;
    END IF;
  END PROCESS SinglePortRAM_generic_process;

  dout <= data_int;

END rtl;

